# Install Library

In [ ]:
!pip install transformers
!pip install datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Collecting datasets
  Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.12)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 9.2 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.4 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 12.1 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 16.0 MB/s eta 0:00:00
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.3.2 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Import Library

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer
from google.colab import drive

# Connect to Drive

In [ ]:
# Path folder tempat file CSV berada
folder_path = "/content/drive/MyDrive/File/CODES/Summarize/4_Summary_Suara_Entertain_50_Base1/Sum_Suara_Entertain_50_Base1"

# Mengambil semua file dengan ekstensi .csv dalam folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith(".csv")]

# Membaca dan menggabungkan semua file
dataframes = []
for file_name in csv_files:
    file_path = os.path.join(folder_path, file_name)
    df = pd.read_csv(file_path)
    dataframes.append(df)

# Menggabungkan semua DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

In [ ]:
# Menyimpan hasil penggabungan ke file baru
output_path = os.path.join(folder_path, "/content/drive/MyDrive/File/CODES/Similarity/4_Similarity_Suara_Entertain_Base1/suara_nas_ent_50_base1_concat.csv")
combined_df.to_csv(output_path, index=False)

In [ ]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7459 entries, 0 to 7458
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         7459 non-null   object
 1   category      7459 non-null   object
 2   publish_date  7459 non-null   object
 3   author        7459 non-null   object
 4   article_url   7459 non-null   object
 5   content       7459 non-null   object
 6   summary       7459 non-null   object
dtypes: object(7)
memory usage: 408.0+ KB

In [ ]:
combined_df.head()

,title,category,publish_date,author,article_url,content,summary
0,"Tiba-Tiba Jadi Suami Beristri Dua di Film, Ibr...",Entertainment,2024-09-30,Yazir Farouk,https://www.suara.com/entertainment/2024/09/30...,Drama percintaan di film Laut Tengah ternyata ...,Drama percintaan di film Laut Tengah ternyata ...
1,"Rujuk dengan Ira Nandha, Elmer Syaherman Terny...",Entertainment,2024-09-30,Yohanes Endra,https://www.suara.com/entertainment/2024/09/30...,Rumah tangga Elmer Syaherman dan Ira Nandha se...,Rumah tangga Elmer Syaherman dan Ira Nandha se...
2,"Sudah Keluar, Hasil Visum Lolly untuk Buktikan...",Entertainment,2024-09-30,Yazir Farouk,https://www.suara.com/entertainment/2024/09/30...,"Hasil visum lanjutan anak Nikita Mirzani, Laur...","Hasil visum lanjutan anak Nikita Mirzani, Laur..."
3,Putri Marissya Icha Bikin Konten Nyindir Pakai...,Entertainment,2024-09-30,Yohanes Endra,https://www.suara.com/entertainment/2024/09/30...,Marissya Icha belakangan ini disorot karena du...,Marissya Icha belakangan ini disorot karena du...
4,"Kibarkan Bendera Finis MotoGP Mandalika, Maia ...",Entertainment,2024-09-30,Yazir Farouk,https://www.suara.com/entertainment/2024/09/30...,"Momen istri Irwan Mussry, Maia Estianty, mengi...","Momen istri Irwan Mussry, Maia Estianty, mengi..."

In [ ]:
nan_summary = combined_df[combined_df['summary'].isna()]


nan_summary

Empty DataFrame
Columns: [title, category, publish_date, author, article_url, content, summary]
Index: []

In [ ]:
combined_df=combined_df.dropna()

# Duplicate

In [ ]:
data = combined_df.copy()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7459 entries, 0 to 7458
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         7459 non-null   object
 1   category      7459 non-null   object
 2   publish_date  7459 non-null   object
 3   author        7459 non-null   object
 4   article_url   7459 non-null   object
 5   content       7459 non-null   object
 6   summary       7459 non-null   object
dtypes: object(7)
memory usage: 408.0+ KB

# Tokenize

Mencoba kode lain agar tokenize lebih mudah di pahami

# Word Embedding

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch

# Memuat IndoBERT dan tokenizer
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1", use_fast=True)
model = AutoModel.from_pretrained("indobenchmark/indobert-base-p1")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

In [ ]:
# Fungsi untuk mendapatkan embedding dari IndoBERT
def get_embeddings(input_ids):
    with torch.no_grad():
        outputs = model(input_ids=input_ids)
    # Mengambil hidden states dari layer terakhir dan rata-rata embeddingsnya
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings

# Fungsi untuk mengonversi tokenized data ke dalam bentuk input_ids dan mendapatkan embedding
def get_input_ids_and_embeddings(data_column):
    input_ids_list = []
    embeddings_list = []

    for text in data_column:
        # Tokenisasi
        tokens = tokenizer(text, padding='max_length', max_length=256, truncation=True, return_tensors="pt")
        input_ids = tokens['input_ids']  # Ambil input_ids
        input_ids_list.append(input_ids)

        # Mendapatkan embeddings
        embedding = get_embeddings(input_ids)
        embeddings_list.append(embedding)

    return input_ids_list, embeddings_list

# Dapatkan input_ids dan embeddings untuk title dan summary
title_input_ids, title_embeddings = get_input_ids_and_embeddings(data['title'])
summary_input_ids, summary_embeddings = get_input_ids_and_embeddings(data['summary'])

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

## Mengubah embeddings menjadi array numpy

In [ ]:
# Mengubah embeddings menjadi array numpy agar bisa disimpan dalam DataFrame
title_embeddings_array = np.vstack([embedding.numpy() for embedding in title_embeddings])
summary_embeddings_array = np.vstack([embedding.numpy() for embedding in summary_embeddings])

# Membuat DataFrame baru dengan embeddings numerik
data_embeddings = pd.DataFrame({
    'title_embeddings': list(title_embeddings_array),
    'summary_embeddings': list(summary_embeddings_array)
})

# Cosine Similarity

In [ ]:
# hitung cosine similarity pada matrix berita
cosine_sim = cosine_similarity(title_embeddings_array, summary_embeddings_array)
print(cosine_sim)

[[0.1895412  0.18991452 0.31942648 ... 0.8901996  0.6227047  0.7524663 ]
 [0.18490885 0.18900014 0.3200839  ... 0.8894562  0.62221617 0.75227356]
 [0.18342358 0.18436943 0.3213995  ... 0.8851769  0.6196641  0.74897105]
 ...
 [0.18328479 0.1868766  0.31759587 ... 0.88656986 0.6192827  0.74810344]
 [0.18436992 0.18661727 0.31954402 ... 0.8862506  0.6205713  0.7486057 ]
 [0.18124789 0.18543646 0.3180065  ... 0.8884693  0.62278837 0.75308275]]

In [ ]:
# membuat dataframe dari varible cosine similarity dengan baris dan kolom title
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['summary'], columns=data['title'])

print(cosine_sim_df.shape)

(7459, 7459)

## Check Similarity Result

In [ ]:
# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # The index is a summary, and you need to find the corresponding title
    # to access the similarity value. However, since you have both summaries
    # and titles as indices, you can access the similarity directly using
    # the index and the corresponding title from the 'data' DataFrame.

    title = data.loc[data['summary'] == index, 'title'].iloc[0] # Get the title for the current summary
    similarity_value = cosine_sim_df.loc[index, title]  # Access the similarity using both summary and title

    print(f"Title: {title}")
    print(f"Summary: {index}")
    print(f"Cosine Similarity: {similarity_value}\n")
    print("-" * 50)  # Pemisah antar pasangan

Streaming output truncated to the last 5000 lines.
Title: Sakit Hati Dibully, Aurel Hermansyah Luapkan Lewat Lagu
Summary: Aurel Hermansyah sering menjadi sasaran bully warganet, mulai dari fisik hingga tingkahnya yang selalu dianggap salah. Pandangan orang suka 'oh kamu kan artis, ini itu. Padahal sebenarnya sama-sama manusia pasti pernah merasakan capek, kecewa dan sedih," imbuhnya. Atta Halilintar kemudian menciptakan lagu berjudul Aku Juga Manusia. Isinya, memberikan semangat kepada Aurel Hermansyah untuk tak peduli pada ocehan orang. " Bukan hanya ingin Aurel Hermansyah bangkit, Atta Halilintar juga berharap sang istri atau siapapun yang merasa terpuruk bisa meluapkan emosi. Sebab ada penggalan lirik berisi, 'Menangislah, kita manusia. Namun tentunya, hal itu ditujukan kepada orang-orang yang tepat. " Soalnya kalau dipendam akan menjadi bom waktu," terang ibu dua anak ini.
Cosine Similarity: 0.7322392463684082

--------------------------------------------------
Title: Asila Maisa 'Malak' Dibelikan Tas Rp150 Juta, Ivan Gunawan: Ngapain Gue Beliin, Gila Kali!
Summary: Momen Asila Maisa minta dibelikan tas mewah merek Louis Vuitton seharga Rp 150 juta ke Ivan Gunawan kembali menuai hujatan dari publik. Terlebih ketika melihat reaksi sang desainer. Hujatan-hujatan tersebut dilontarkan netizen dalam konten yang diunggah akun TikTok manajemen Asila Maisa, @amteamofficial, pada Selasa 9 Juli 2024. " Terlihat Asila Maisa berulang kali memohon kepada Ivan Gunawan sambil memasang wajah memelas. Kemudian Ivan Gunawan merekam aksi putri Ramzi, "Guys, menurut kamu ya, anak lulus SMA minta dibeliin tas 150 juta pantes apa nggak?" imbuh pria yang akrab disapa Igun itu sambil bercanda. Sang ibu pun menegur putrinya untuk tidak bertingkah kelewatan. tegur Avi Basalamah yang tetap tidak diindahkan putrinya. " Walau sudah ditolak dan ditegur langsung, Asila Maisa tetap merengek hingga akhirnya mau tidak mau Ivan Gunawan mengabulkannya. " Belum tentu juga dibeliin sama orang tuanya. Alhamdulillah, gue nggak pernah diajarin untuk minta-minta," sindir @farida***. "
Cosine Similarity: 0.19528695940971375

--------------------------------------------------
Title: Kalah Mentereng dari Aaliyah Massaid, Intip Kado Fuji untuk Ultah Aurel Hermansyah
Summary: Berbanding terbalik dari Aaliyah Massaid, mantan pacar Thariq Halilintar, Fuji tidak menghadiri perayaan ulang tahun Aurel Hermansyah pada Rabu 10 Juli 2024. Kendati tidak hadir, Fuji memberikan ucapan sekaligus hadiah ulang tahun untuk Aurel Hermansyah yang genap berusia 26 tahun layaknya Aaliyah Massaid. Semula dikira hanya memberi ucapan, mantan pacar Thariq Halilintar itu belakangan diketahui juga ikut memberikan hadiah ulang tahun. Dia juga ikut terlibat dalam skenario kejutan ulang tahun sahabatnya. Pada kesempatan itu, Aaliyah Massaid menyerahkan satu unit tas branded dari rumah mode Chanel untuk Aurel. Hadiah tersebut merupakan hasil patungan dengan Thariq Halilintar. " Harga satu unit tas itu adalah sekitar Rp65 juta hingga Rp70 juta.
Cosine Similarity: 0.7438360452651978

--------------------------------------------------
Title: Usai Diperiksa Polisi Selama 10 Jam, Tiko Aryawardhana Suami BCL Cengengesan
Summary: Suami Bunga Citra Lestari, Tiko Aryawardhana muncul ke publik usai diperiksa atas laporan penggelapan dari sang mantan istri, Arina Winarto di Polres Metro Jakarta Selatan, Kamis 11 Juli 2024. Memakai kemeja biru, Tiko memamerkan senyumnya ke arah awak media usai hampir 10 jam berhadapan dengan penyidik. Pertama, Tiko Aryawardhana mengucap syukur setelah pemeriksaan. Ia bisa menjawab semua pertanyaan penyidik, yang diperkirakan berjumlah 40 sampai 50. “ Alhamdulillah pemeriksaan hari ini sudah selesai,” ujar Tiko Aryawardhana. Tidak diceritakan oleh Tiko Aryawardhana secara detail, poin apa saja yang ditanyakan penyidik. Jadi mohon jangan tuliskan nama BCL atau menggunakan foto dia di dalam pemberitaan, yang berkaitan dengan masalah ini,” tutur Tiko Aryawardhana. Tidak ada kata-kata apa pun yang terucap lagi dari Tiko. Laporan Arina Winarto atas dugaan penggelapan yang dilakukan Tiko Aryawardhana terdaftar di Polres Metro Jakarta Selatan sejak 2022. “Didapatkan adanya temuan perihal penggunaan dana sebesar Rp6,9 miliar yang tidak jelas peruntukkannya,” papar kuasa hukum Arina Winarto, Leo Siregar dalam keterangan tertulis, Senin 3 Juni 2024.
Cosine Similarity: 0.1646951138973236

--------------------------------------------------
Title: Hubungan Halda dan Jirayut Direstui, Raffi Ahmad Elus Kepala Bakal Sumbang Setengah Miliar
Summary: Halda Rianta belakangan sedang disorot perkara perjodohannya dengan penyanyi dangdut asal Thailand, Jirayut. Awalnya mereka berdua dipertemukan oleh Deddy Corbuzier lewat acara PodHub. Di situ, mereka dinilai punya chemistry dan banyak kecocokan. Usai acara tersebut, kedekatan mereka semakin terlihat. Beberapa kali keduanya membagikan momen saat sedang bersama. Tak tanggung-tanggung Halda dan Jirayut terlihat pamer kemesraan di foto dan video yang dibagikan di Instagram. Kebersamaan mereka pun langsung jadi sorotan Raffi Ahmad saat mereka menjadi bintang tamu di program FYP. Eh tapi benar, kalau lu nikah gue sumbang, benar. Gue kasih,” janji Raffi Ahmad seperti dikutip program FYP belum lama ini. Lah, banyak banget itu ya,” Halda menanggapi dengan logat Betawi. Raffi Ahmad pun menyuruh Halda untuk bicara dengan ibu Jirayut. Mama setuju nggak kalau Jirayut sama aku?" Raffi Ahmad pun hanya bisa kebingungan karena uangnya sudah dipastikan keluar bila jirayut dan Halda benar menikah. " Wah, berarti 500 juta gue entar keluar dong," ujar Raffi Ahmad sambil memegang kepalanya.
Cosine Similarity: 0.15948644280433655

--------------------------------------------------
Title: Terungkap Aaliyah Massaid Pernah Tinggalkan Angelina Sondakh, Pilih Diasuh Reza Artamevia
Summary: Kehidupan Aaliyah Massaid dan kakaknya, Zahwa Massaid sejak kecil penuh liku-liku. Kondisi ini terus bertahan sampai Adjie meninggal dunia pada 5 Februari 2011. Namun, Aaliyah Massaid cuma beberapa bulan tinggal bersama Angie selepas kepergian sang ayah. Jadi aku sempet awalnya tinggal sama Mama Angie. Sejak saat itu, Aaliyah dan Zahwa tumbuh bersama di bawah asuhan Reza Artamevia. Namun, hubungan mereka dengan Angie tetap berjalan baik sampai sekarang. Angie bahkan masih dinggap keluarga oleh Aaliyah Massaid dan dibuktikan ditempatkan spesial di acara lamarannya dengan Thariq Halilintar belum lama ini. Masih dianggap keluarga, Angie sampai menangis haru. Dia tak menyangka Aaliyah dan Zahwa punya hati yang besar. Ini karena Zahwa baru saja pulang ke Indonesia usai menempuh pendidikan beberapa tahun di Amerika Serikat.
Cosine Similarity: 0.5800132751464844

--------------------------------------------------
Title: 8 Potret Rumah Baru Frans Faisal yang Banyak Dapat Kritik dari Fuji, Belinya Cash Loh!
Summary: Frans Faisal dikabarkan baru membeli rumah, menyusul adik-adiknya, Fuji dan Fadly Faisal, yang justru lebih dulu punya. Profesi Frans pun paling beda dari dua adiknya tersebut. Fuji dan Fadly Faisal diketahui terjun ke dunia hiburan Tanah Air. Sementara Frans mewarisi jiwa dagang kedua orangtuanya, serta melanjutkan bisnis mendiang Vanessa Angel dan Bibi Ardiansyah. Baru-baru ini, Fuji merekam kunjungannya ke rumah Frans Faisal. Frans Faisal mengungkap luas rumahnya sekitar 320 meter persegi. Belum ada furniture apapun ditambahkan di ruang tamunya. Dapur kotor pun bersebelahan dengan dapur bersih. Pintu menuju dapur kotor tepat berada di sisi tangga menuju kamar ART di foto sebelumnya. Space kosong itu nantinya akan dibuat sebuah ruangan. Fuji banyak memberikan protes sekaligus saran untuk membobol dinding-dinding di rumah abangnya. Balkon dari lantai dua rumah Frans Faisal memiliki pemandangan serba hijau dari halaman rumah yang dipenuhi pepohonan. Itu dia potret rumah baru Fadly Faisal yang ternyata akan direnovasi sehingga masih kosong melompong. Kita tunggu hasilnya setelah direnovasi ya!
Cosine Similarity: 0.29787692427635193

--------------------------------------------------
Title: Salshabilla Adriani Diledek Syahrini Versi Kedua, Buntut Isu Rebut Pasangan Orang
Summary: Pernikahan Salshabilla Adriani dengan Ibrahim Risyad pada Kamis 11 Juli 2024 masih santer diterpa komentar negatif dari sejumlah kalangan warganet. "Salsha adalah Syahrini ke-2 yang dihujat habis-habisan karena menikah," kata netizen lain. Nah, ini namanya dilamar dan pertunangan, dapat restu dan doa yang terbaik dari orang tua ke dua belah pihak," ujar Helen Oktavia. Helen Oktavia menambahkan, Tuhan telah mengatur jodoh seseorang sehingga dianggap tak logis sindiran merebut jodoh orang yang dialamatkan kepada anaknya. Karena itu, Helen Oktavia juga menilai pertemuan hingga pernikahan Salshabilla Adriani dan Ibrahim Risyad sah-sah saja. " Apapun cara itu, cara Allah mempertemukan kamu dengan pasanganmu," ucap Helen Oktavia, dilansir pada Kamis 11 Juli 2024.
Cosine Similarity: 0.6131980419158936

--------------------------------------------------
Title: Nikita Mirzani Balas Menohok Saat Disebut Mirip Mpok Atiek: Yang Penting Hidupnya Nggak Minta-minta
Summary: Setelah Luna Maya dan Tamara Belszynski, kini Nikita Mirzani disebut mirip dengan Mpok Atiek oleh publik. Hal itu dilontarkan warganet saat bergabung dalam siaran langsung artis kontroversial itu. Alih-alih marah, Nikita Mirzani justru tidak mempermasalahkannya. Sebab, pelawak yang usianya sudah 68 tahun itu dulunya terbilang cantik. Kemudian, warganet yang lain mengejek paras Nikita Mirzani dengan menyamakan dengan Mpok Atiek. "' Jadi kalau disamain sama dia nggak ada masalah. Sebelum Nikita Mirzani, artis-artis yang dimiripkan dengan Mpok Atiek adalah Luna Maya dan Tamara Bleszynski.
Cosine Similarity: 0.8993873596191406

--------------------------------------------------
Title: Kembali ke Indonesia, Angelina Sondakh Belum Temui Zahwa Massaid dan Sibuk Lakukan Ini
Summary: Kedatangan Zahwa Massaid di Indonesi disambut hangat oleh keluarga. Bahkan Thariq sempat memamerkan kemesraan bersama Aaliyah Massaid di hadapan Zahwa Massaid. Bersama Keanu Massaid, Angie menikmati kenyamanan maskapai Etihad dalam perjalaanannya dari Spanyol. Termasuk membuat konten bersama di YouTube. Namun tampaknya hal itu diduga belum terjadi. Ibu anak ini ternyata diundang untuk menjadi bintang tamu dalam sebuah acara televisi. Cerita @keanu_massaid Summercamp di Spanyol yang ditemani @angelinasondakh09," bunyi keterangan dalam unggahan salah satu acara televisi yang dimaksud, dilansir pada Kamis 11 Juli 2024. Sementara di sisi lain, Zahwa Massaid memilih menghabiskan waktunya di luar rumah. Ini menjadi momen yang cukup lama usai dirinya menetap di Amerika Serikat. Ia mengenakan kaos hitam dipadukan dengan aksesoris kalung. Zahwa dan teman-temannyaa duduk dalam meja yang sama dan menikmati beberapa kudapan.
Cosine Similarity: 0.5296303033828735

--------------------------------------------------
Title: Pantas Sikapnya Dipuji Netizen, Arsy Hermansyah Ternyata Punya Garis Keturunan Bangsawan dan Raja
Summary: Arsy Hermansyah yang merupakan putri dari pasangan Anang Hermansyah dengan Ashanty baru-baru ini mencuri perhatian publik karena sikapnya. Keluarga besarnya pun datang termasuk diantaranya sang adik Arsy Hermansyah. Dikutip dari channel YouTube Atta Halilintar, Arsy Hermansyah menjadi sorotan lantaran sikapnya saat menemani anak dari Aurel Hermansyah yakni Ameena Hanna Nur Atta. Tak sedikit yang menyebut ia sebagai sosok yang pintar. Abdullah Siddik merupakan salah satu tokoh pahlawan asal Bengkulu selain Fatmawati Soekarno. Di masa perjuangan kemerdekaan, pria kelahiran Muara Aman 13 Juni 1913 ini dikenal sebagai diplomat ulung. Ia kerap mendampingi Presiden Soekarno, termasuk ketika sang Putra Fajar tersebut diasingkan di Bengkulu tahun 1938-1942. Di tahun 1947, ia pernah diangkat sebagai Kepala Pemerintahan Sumatera sebagai Wakil Gubernur Sumatera. Lebih jauh, bila dirunut dari leluhur garis ibu Abdullah Siddik, kakek buyut Ashanty merupakan bangsawan asal Belanda yakni Sir Edward Coles yang kemudian menikah dengan putri keturunan mantan penguasa Pangeran Ing Alaga dari Kerajaan Silebar. leluhur Paternal Nelemat, keturunan pagar Ruyung Pangeran Raja Chalippa.
Cosine Similarity: 0.18359756469726562

--------------------------------------------------
Title: Thariq Halilintar Suapi Makan Aaliyah Massaid di Depannya, Zahwa Geleng-Geleng Kepala
Summary: Aaliyah Massaid kini sudah berkumpul kembali bersama kakaknya, Zahwa Massaid. Zahwa diketahui baru tiba di Indonesia dari Amerika Serikat. Kepulangan Zahwa diduga karena ingin menyaksikan langsung pernikahan Aal, sapaan akrab Aaliyah, dengan Thariq Halilintar. Ketiganya tampak tengah makan bersama di meja makan. Tak sedikit yang ikut 'meleleh' melihat sikap manis Thariq ke Aal. " Sweet kata Zahwa ke Aal," kata pengguna TikTok. "Ya Allah bahagia banget lihat mereka tinggal tunggu Keanu dan Mami Angie ketemu," ujar yang lain. " Punya kakak sedekat ini, apa-apa curhat ke kaka," kata yang lain.
Cosine Similarity: 0.8716989159584045

--------------------------------------------------
Title: Shandy Aulia Bikin Pangling dengan Model Rambut Baru: Malah Kayak Anak SMA!
Summary: Shandy Aulia baru-baru ini sukses mengesankan netizen lewat penampilan barunya di Instagram. Aktris cantik berusia 37 tahun ini baru potong rambut. Kemarin, Rabu 10 Juli 2024, Shandy Aulia mengunggah potret cantiknya dalam balutan outfit motif bunga-bunga. Kali ini rambutnya lebih pendek di atas bahu. Sentuhan warna pirang di rambut baru Shandy Aulia membuat penampilannya kian fresh. Potret Shandy Aulia pamer model rambut baru ini banjir pujian. Tak sedikit yang memuji Shandy Aulia makin cantik. Sampai-sampai ada yang bilang kalau penampilan pemain film Cinta Itu Buta ini kayak anak SMA."Malah kayak anak SMA kakk imuttt bangetttt," kata netizen. " Tambah cantik," netizen lain ikut menimpali. " Shandy Aulia makin cantik dan awet muda ya?
Cosine Similarity: 0.6167539358139038

--------------------------------------------------
Title: Tingkahnya Dianggap Pecicilan, Asila Maisa Ramai Dibandingkan dengan Anak Artis yang Kalem
Summary: Putri semata wayang Ramzi dan Avi Basalamah, Asila Maisa belakangan ini kembali dihujat karena tingkahnya yang dinilai pecicilan dan sangat aktif. Seperti pada video yang beredar di media sosial baru-baru ini. Sembari dirias, Asila tidak berhenti menggerakkan tubuhnya. Asila Maisa juga menjahili penatas riasnya dengan menjulurkan lidahnya ketika sedang dipasangi bulu mata palsu. " Tingkah Asila Maisa yang tidak bisa diam itu malah dikritik oleh warganet. Anak-anak artis yang lain disebut lebih sopan dan kalem daripada Asila Maisa. Santun banget anaknya," kata @devina***. " Tetap anak Irfan Hakim yang best attitude, solehah semua," puji @titina***.
Cosine Similarity: 0.7271449565887451

--------------------------------------------------
Title: Beda Sikap Saat Dirias MUA, Asila Maisa dan Amora Lemos Ternyata Satu Almamater
Summary: Imbas video pecicilan saat dirias makeup artist viral, polah Asila Maisa santer dijadikan tandingan anak artis lain. Salah satu di antaranya adalah Amora Lemos. Dikutip pada Kamis 11 Juli 2024, berikut adalah perbandingan latar pendidikan hingga sikap Asila Maisa dan Amora Lemos saat dirias makeup artist. Amora LemosSelaras dengan Asila Maisa, Amora Lemos diketahui juga bersekolah di Highscope Indonesia Cabang TB Simatupang. Dia merupakan adik kelas Asila Maisa dan masih aktif bersekolah saat ini. Hal tersebut tertuang dari unggahannya pada Mei 2023 lalu. Sebelum naik panggung konser musik Kris Dayanti di The Star Theatre Singapura, Amora Lemos duduk anteng dan tak banyak berpolah ketika didandani makeup artist.
Cosine Similarity: 0.6906692385673523

--------------------------------------------------
Title: Azriel Hermansyah Dituding Tak Ajak Kris Dayanti Foto Berdua, Ashanty Pasang Badan Labrak Haters
Summary: Azriel Hermansyah mendadak dihujat lantaran dikira tak mengajak Kris Dayanti, ibu kandungnya foto bareng untuk acara wisuda. Kekasih Sarah Menzel itu sudah memberikan penjelasan panjang lebar terkait ketiadaan foto berdua dengan diva yang dulu akrab disapa KD atau Krisdayanti, tapi netizen tetap saja nyinyir sampai-sampai Ashanty harus menyemprot haters secara langsung. Sederet netizen lantas memprotes Azriel yang dianggap memberikan sikap berbeda pada Ashanty dan Kris Dayanti. " Ibu boleh banyak, tapi mimi cuma satu," tulis haters yang julid. "Ziel benar-benar terlihat banget membedakan Ashanty sama KD," imbuh lainnya. Tak berselang lama, Ashanty juga ikut 'melabrak' si haters. Lama-lama batas kesabaran saya ada batasnya. Kamu bully saya sama suami aja di potsingan saya atau di DM silakan. Tapi please, jangan comment atau hancurkan mental anak saya. Kalian ini suka banget suudzon, nggak tahu apa-apa main comment main nyakitin perasaan Jiel.
Cosine Similarity: 0.17150400578975677

--------------------------------------------------
Title: Usai Wisuda, Azriel Hermansyah Diberondong Pertanyaan Kapan Nikah
Summary: Anak kedua Anang Hermansyah dan Kris Dayanti, Azriel Hermansyah akhirnya merampungan kuliahnya di Universitas Bina Nusantara (Binus) Jakarta. Kedua orang tua kandung, orang tua angkat, dan sang kekasih, Sarah Menzel tampak hadir untuk mendampingi Jiel, panggilan akrabnya untuk menerima bukti kelulusannya. Di akun Instagramnya, Azriel membagikan potret dirinya saat hari spesialnya tersebut. Saya memilih untuk fokus pada hidup saya, impian saya, dan kebahagiaan saya,” tulis Azriel Hermansyah di Instagram, dilansir Kamis, 11 Juli 2024. Lebih lanjut, Azriel mengaku akan memprioritaskan hal-hal yang akan membuatnya bahagia guna mencapai impiannya. “ Sudah waktunya untuk memprioritaskan apa yang memberiku kegembiraan dan kepuasan, untuk mengejar impian yang membakar jiwaku,” lanjutnya. “ Sontak saja, unggahan Azriel tersebut langsung banyak mendapat respon dari warganet. “Kapan nikah?”tulis warganet “Jadi, kapan bakal nikahin Sarah?”todong warganet. “ Yang paling aku tunggu endingnya bahagia,” komentar warganet.
Cosine Similarity: 0.17172160744667053

--------------------------------------------------
Title: 7 Potret Liburan Putri Titian di Beach Club Bali, Deg-degan Pakai Bikini di Depan Junior Liem
Summary: Aktris cantik Putri Titian tengah menikmati liburannya di Bali. Ini adalah salah satu beach club ternama di Pulau Dewata untuk menikmati pantai dan sunset. Putri Titian mengaku dulu pernah ke tempat ini bersama Junior Liem saat masih PDKT. Mereka dikaruniai dua anak lelaki yakni Theodore Iori Liem dan Mykah Iago Liem dari pernikahan tersebut. Dalam captionnya, Putri Titian mengaku masih deg-degan lho memakai bikini di depan suami. Penasaran gimana serunya liburan mereka di beach club Bali? Intip potretnya dilansir dari akun Instagram pribadi sang artis, check this out! Ini potret Putri Titian bersama Junior Liem dan kedua anaknya di Potato Head Beach Club. Kelihatan banget Iori dan Iago sudah nggak sabar buat liburan nih! Suasana Bali begitu terasa di tempat ini.3. " Dulu waktu masih pdkt pernah ngedate di sini. Lalu sekarang kembali lagi ke pohe udah sama my halal boyfriend dan nambah dua monster kecil," kata Putri Titian dalam caption Instagram kemarin 10 Juli 2024. Putri Titian membagikan potretnya saat berenang bersama Junior Liem di kolam yang langsung menghadap pantai.
Cosine Similarity: 0.16146373748779297

--------------------------------------------------
Title: Atta Halilintar Minta Maaf ke Tompi, Imbas Tulis Harga Rumah Rp150 Miliar di YouTube

In [ ]:
# List to store the results
results = []

# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # Mendapatkan judul yang sesuai dengan summary berdasarkan index
    title = data.loc[data['summary'] == index, 'title'].iloc[0]
    similarity_value = cosine_sim_df.loc[index, title]  # Mengakses nilai similarity

    # Menyimpan pasangan dan nilai similarity ke dalam list
    results.append([title, index, similarity_value])

# Membuat DataFrame untuk hasilnya
similarity_df = pd.DataFrame(results, columns=['Title', 'Summary', 'Cosine Similarity'])

In [ ]:
similarity_df.head()

,Title,Summary,Cosine Similarity
0,"Tiba-Tiba Jadi Suami Beristri Dua di Film, Ibr...",Drama percintaan di film Laut Tengah ternyata ...,0.189541
1,"Rujuk dengan Ira Nandha, Elmer Syaherman Terny...",Rumah tangga Elmer Syaherman dan Ira Nandha se...,0.189
2,"Sudah Keluar, Hasil Visum Lolly untuk Buktikan...","Hasil visum lanjutan anak Nikita Mirzani, Laur...",0.3214
3,Putri Marissya Icha Bikin Konten Nyindir Pakai...,Marissya Icha belakangan ini disorot karena du...,0.221442
4,"Kibarkan Bendera Finis MotoGP Mandalika, Maia ...","Momen istri Irwan Mussry, Maia Estianty, mengi...",0.487217

## Save Similarity

In [ ]:
# Menyimpan DataFrame ke file CSV di lokasi yang ditentukan
similarity_df.to_csv('/content/drive/MyDrive/File/CODES/Similarity/4_Similarity_Suara_Entertain_Base1/similarity_suara_ent_base1.csv', index=False)