# Install Library

In [1]:
!pip install transformers
!pip install datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.50.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.29.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Collecting datasets
  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.14)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.29.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.5.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 8.6 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.2 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 13.9 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 11.6 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 14.3 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.5.0 dill-0.3.8 fsspec-2024.12.0 multiprocess-0.70.16 xxhash-3.5.0

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Import Library

In [3]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer
from google.colab import drive

# Connect to Drive

In [4]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
# Path folder tempat file CSV berada
combined_df = pd.read_csv('/content/drive/MyDrive/File/CODES/Summarize/6_Kapan_Lagi_clickbait/berlebihan/pre_berlebihan.csv')

combined_df.head()

,title,category,publish_date,article_url,content,label
0,Wanita dengan Tubuh Berisi Terbukti Bikin Pria...,Lifestyle,2019-09-16,https://lifestyle.kompas.com/read/2019/09/16/2...,"Berbagai usaha dilakukan, mulai dari olahraga ...",clickbait
1,Kronologi Lengkap Pemuda di Bandung Tusuk Gadi...,News,2019-10-09,https://regional.kompas.com/read/2019/09/10/23...,"RG (22), pemuda yang nekat menusuk Z (16), sis...",clickbait
2,"Sarapan Bikin Ngantuk, Mitos atau Fakta?",Lifestyle,2019-09-16,https://lifestyle.kompas.com/read/2019/09/16/2...,"Tak sedikit orang yang beranggapan, bahwa , p...",clickbait
3,Puisi Hairdryer Dian Sastro yang Tak Terduga d...,Entertainment,2019-10-09,https://entertainment.kompas.com/read/2019/09/...,"Puisi , karya artis peran , ramai diperbinca...",clickbait
4,"Unggah Foto Bersama Habibie, Syahrini: Semoga ...",Entertainment,2019-11-09,https://entertainment.kompas.com/read/2019/09/...,"Penyanyi , turut menyampaikan duka atas menin...",clickbait

In [7]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3789 entries, 0 to 3788
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         3789 non-null   object
 1   category      3789 non-null   object
 2   publish_date  3789 non-null   object
 3   article_url   3789 non-null   object
 4   content       3787 non-null   object
 5   label         3789 non-null   object
dtypes: object(6)
memory usage: 177.7+ KB

In [10]:
nan_summary = combined_df[combined_df['content'].isna()]


nan_summary

,title,category,publish_date,article_url,content,label
2516,"Tinggalkan Google, Wanita Ini Ungkap Rahasia R...",tekno,2019-09-18,https://tekno.tempo.co/read/1249203/tinggalkan...,NaN,clickbait
2603,"Robot Militer Otonom Diklaim Berbahaya, Apa Saja?",tekno,2019-09-18,https://tekno.tempo.co/read/1249237/robot-mili...,NaN,clickbait

In [11]:
combined_df=combined_df.dropna()

# Duplicate

In [12]:
data = combined_df.copy()

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3787 entries, 0 to 3788
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         3787 non-null   object
 1   category      3787 non-null   object
 2   publish_date  3787 non-null   object
 3   article_url   3787 non-null   object
 4   content       3787 non-null   object
 5   label         3787 non-null   object
dtypes: object(6)
memory usage: 207.1+ KB

# Tokenize

Mencoba kode lain agar tokenize lebih mudah di pahami

# Word Embedding

In [14]:
from transformers import AutoTokenizer, AutoModel
import torch

# Memuat IndoBERT dan tokenizer
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1", use_fast=True)
model = AutoModel.from_pretrained("indobenchmark/indobert-base-p1")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

In [16]:
# Fungsi untuk mendapatkan embedding dari IndoBERT
def get_embeddings(input_ids):
    with torch.no_grad():
        outputs = model(input_ids=input_ids)
    # Mengambil hidden states dari layer terakhir dan rata-rata embeddingsnya
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings

# Fungsi untuk mengonversi tokenized data ke dalam bentuk input_ids dan mendapatkan embedding
def get_input_ids_and_embeddings(data_column):
    input_ids_list = []
    embeddings_list = []

    for text in data_column:
        # Tokenisasi
        tokens = tokenizer(text, padding='max_length', max_length=256, truncation=True, return_tensors="pt")
        input_ids = tokens['input_ids']  # Ambil input_ids
        input_ids_list.append(input_ids)

        # Mendapatkan embeddings
        embedding = get_embeddings(input_ids)
        embeddings_list.append(embedding)

    return input_ids_list, embeddings_list

# Dapatkan input_ids dan embeddings untuk title dan summary
title_input_ids, title_embeddings = get_input_ids_and_embeddings(data['title'])
summary_input_ids, summary_embeddings = get_input_ids_and_embeddings(data['content'])

## Mengubah embeddings menjadi array numpy

In [17]:
# Mengubah embeddings menjadi array numpy agar bisa disimpan dalam DataFrame
title_embeddings_array = np.vstack([embedding.numpy() for embedding in title_embeddings])
summary_embeddings_array = np.vstack([embedding.numpy() for embedding in summary_embeddings])

# Membuat DataFrame baru dengan embeddings numerik
data_embeddings = pd.DataFrame({
    'title_embeddings': list(title_embeddings_array),
    'summary_embeddings': list(summary_embeddings_array)
})

# Cosine Similarity

In [18]:
# hitung cosine similarity pada matrix berita
cosine_sim = cosine_similarity(title_embeddings_array, summary_embeddings_array)
print(cosine_sim)

[[0.11928782 0.13128646 0.09800425 ... 0.2453731  0.18388554 0.17838743]
 [0.11780906 0.13218574 0.09750348 ... 0.24568364 0.18407705 0.17838702]
 [0.12166087 0.13311192 0.10015878 ... 0.24583969 0.18585397 0.18088758]
 ...
 [0.11826164 0.13033669 0.097785   ... 0.24760845 0.18356365 0.17760554]
 [0.11711738 0.12720458 0.09591059 ... 0.2458737  0.18277028 0.17562726]
 [0.11823764 0.13230564 0.09884524 ... 0.24757928 0.18535931 0.18107027]]

In [19]:
# membuat dataframe dari varible cosine similarity dengan baris dan kolom title
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['content'], columns=data['title'])

print(cosine_sim_df.shape)

(3787, 3787)

## Check Similarity Result

In [20]:
# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # The index is a summary, and you need to find the corresponding title
    # to access the similarity value. However, since you have both summaries
    # and titles as indices, you can access the similarity directly using
    # the index and the corresponding title from the 'data' DataFrame.

    title = data.loc[data['content'] == index, 'title'].iloc[0] # Get the title for the current summary
    similarity_value = cosine_sim_df.loc[index, title]  # Access the similarity using both summary and title

    print(f"Title: {title}")
    print(f"Summary: {index}")
    print(f"Cosine Similarity: {similarity_value}\n")
    print("-" * 50)  # Pemisah antar pasangan

Streaming output truncated to the last 5000 lines.
Cosine Similarity: 0.17044758796691895

--------------------------------------------------
Title: 5 Makanan Khas Keraton Yogyakarta yang Legendaris
Summary: BERKUNJUNG ke Yogyakarta rasanya belum lengkap tanpa mencicipi hidangan khas Kerajaan,. Makanan khas kerajaan Keraton Yogyakarta ini merupakan hidangan spesial untuk raja-raja Yogyakarta sejak ratusan tahun yang lalu.,Buat pelancong pasti penasaran dengan makanan yang disajikan untuk Sri Sultan? Dimasak oleh para abdi dalem di pawon atau dapur khusus yang berada di dalam keraton, penyajian makanan khas Kerajaan,untuk Sri Sultan ini punya tata caranya sendiri yang disebut tata cara ladosan dhahar dalem.,,Kira-kira seperti apa selera makanan para raja di Keraton Yogyakarta? Berikut ulasan selengkapnya seperti dirangkum dari,:,,Makanan Khas Kerajaan Keraton Yogyakarta yang satu ini sejenis salad versi Jawa. Berisi kombinasi antara selada, mentimun, tomat dan telur rebus.,Untuk siraman sausnya, ada kuning telur yang dicampur dengan merica, pala, gula pasir, garam, dan sedikit cuka. Kemudian ditambah sedikit air dan mentega. Selat usar ini memiliki cita rasa perpaduan manis dan asam yang pas. Klik halaman berikutnya untuk info lebih lanjut yang disarikan dari,.
Cosine Similarity: 0.1658741682767868

--------------------------------------------------
Title: Deretan Amalan Ringan, Nomor 2 Imbalannya Didoakan 70 Ribu Malaikat
Summary: banyak,yang bisa Anda jalankan. Meski sangat mudah dilakukan, amalan-amalan sunah tersebut memiliki pahala besar. Rasulullah SAW pun menganjurkan kepada umatnya agar selalu mengamalkan hal-hal kecil yang tentunya berpahala.,Terdapat delapan,yang berpahala besar: Berikut amalan tersebut sebagaimana dirangkum Okezone pada hari ini, Rabu 18 September 2019.,,,"Tidak ada seorang Muslim pun yang mendoakan kebaikan bagi saudaranya (sesama muslim) tanpa sepengetahuannya, melainkan malaikat akan berkata, "Dan bagimu juga kebaikan yang sama," (HR. Muslim no. 4912).,Mendoakan kebaikan sesama muslim memiliki keutamaan yang sangat besar. Seperti yang diterangkan dalam hadist di atas, Malaikat akan mencatat segala amal kebaikan manusia yang juga melakukan hal serupa.,,Menjenguk orang yang sedang sakit merupakan kewajiban seorang muslim kepada sesamanya. Perbuatan tersebut nyatanya memiliki pahala yang besar. Rasulullah SAW bersabda:,ÿ•Ÿêÿ∞Ÿéÿß ÿπŸéÿßÿØŸé ÿßŸÑÿ±ŸëŸéÿ¨ŸèŸÑŸè ÿ£ŸéÿÆŸéÿßŸáŸè ÿßŸÑŸíŸÖŸèÿ≥ŸíŸÑŸêŸÖŸé ŸÖŸéÿ¥ŸéŸâ ŸÅŸêŸäŸí ÿÆŸêÿ±ŸéÿßŸÅŸéÿ©Ÿê ÿßŸÑŸíÿ¨ŸéŸÜŸëŸéÿ©Ÿê ÿ≠Ÿéÿ™ŸëŸéŸâ ŸäŸéÿ¨ŸíŸÑŸêÿ≥Ÿé ŸÅŸéÿ•Ÿêÿ∞Ÿéÿß ÿ¨ŸéŸÑŸéÿ≥Ÿé ÿ∫ŸéŸÖŸéÿ±Ÿéÿ™ŸíŸáŸè ÿßŸÑÿ±ŸëŸéÿ≠ŸíŸÖŸéÿ©Ÿèÿå ŸÅŸéÿ•ŸêŸÜŸí ŸÉŸéÿßŸÜŸé ÿ∫ŸèÿØŸíŸàŸéÿ©Ÿã ÿµŸéŸÑŸëŸéŸâ ÿπŸéŸÑŸéŸäŸíŸáŸê ÿ≥Ÿéÿ®ŸíÿπŸèŸàŸíŸÜŸé ÿ£ŸéŸÑŸíŸÅŸé ŸÖŸéŸÑŸéŸÉŸç ÿ≠Ÿéÿ™ŸëŸéŸâ ŸäŸèŸÖŸíÿ≥ŸêŸäŸéÿå ŸàŸéÿ•ŸêŸÜŸí ŸÉŸéÿßŸÜŸé ŸÖŸéÿ≥Ÿéÿßÿ°Ÿã ÿµŸéŸÑŸëŸéŸâ ÿπŸéŸÑŸéŸäŸíŸáŸê ÿ≥Ÿéÿ®ŸíÿπŸèŸàŸíŸÜŸé ÿ£ŸéŸÑŸíŸÅŸé ŸÖŸéŸÑŸéŸÉŸç ÿ≠Ÿéÿ™ŸëŸéŸâ ŸäŸèÿµŸíÿ®Ÿêÿ≠Ÿé.,"Apabila seseorang menjenguk saudaranya yang muslim (yang sedang sakit), maka (seakan-akan) dia berjalan sambil memetik buah-buahan Surga sehingga dia duduk, apabila sudah duduk maka diturunkan kepadanya rahmat dengan deras. Apabila menjenguknya di pagi hari maka tujuh puluh ribu malaikat mendoakannya agar mendapat rahmat hingga waktu sore tiba. Apabila menjenguknya di sore hari, maka tujuh puluh ribu malaikat mendoakannya agar diberi rahmat hingga waktu pagi tiba." (HR. at-Tirmidzi, Ibnu Majah dan Imam Ahmad dengan sanad shahih).,3. Berdzikir,berikutnya adalah berdzikir. Selain mendapat pahala besar, dengan berdzikir maka kita akan selalu terfokus kepada Allah dan berserah diri kepadaNya. Dzikir juga menjadi bentuk pujian dan tanda rasa syukur selain berdoa.
Cosine Similarity: 0.1797855943441391

--------------------------------------------------
Title: Jamu Newcastle, Adrian: Liverpool Siap Bertarung untuk 3 Poin!
Summary: ‚Äì Penjaga gawang,, Adrian San Miguel, menatap optimis pertandingan kontra Newcastle United dalam pekan kelima Liga Inggris 2019-2020. Ia memastikan para pemain Liverpool siap bertarung untuk memperebutkan tiga poin dengan Newcastle.,Liverpool memang bakal bersua Newcastle di Anfield Stadium pada Sabtu 14 September 2019 malam WIB. Adrian memastikan kemenangan jadi target utama The Reds ‚Äìjulukan Liverpool. Hal ini diperlukan demi menjaga peluang Liverpool untuk menjadi juara di ajang Liga Inggris.,,,Sebab hingga pekan keempat Liga Inggris, skuad asuhan Jurgen Klopp berhasil bertengger di puncak klasemen sementara. Kemenangan yang berhasil diraih di seluruh laga musim ini membuat Adrian dan kawan-kawan total telah mengemas 12 angka, unggul dua poin dari Manchester City yang membuntuti di tempat kedua.,,Adrian pun berharap kondisi ini bisa terus terjaga. Karena itu, persiapan matang pun dilakukan para penggawa Liverpool sebelum menjamu Newcastle. Hal tersebut dilakukan karena Liverpool menyadari Newcastle bukanlah lawan yang mudah. Mereka bahkan berhasil mempermalukan Tottenham Hotspur dalam laga pekan kedua Liga Inggris dengan skor 1-0.
Cosine Similarity: 0.19440388679504395

--------------------------------------------------
Title: Performa Luar Biasa Bali United di Liga 1 2019
Summary: ‚Äì Bali United menampilkan performa luar biasa di,. Dari 17 pertandingan yang sudah dilalui, Laskar Serdadu Tridatu ‚Äìjulukan Bali United‚Äì mengoleksi 41 poin, hasil dari 13 menang, 2 imbang dan 2 kalah.,Bahkan dalam sembilan laga terakhir, Ilija Spasojevic dan kawan-kawan tidak terkalahkan dengan koleksi delapan menang dan satu imbang. Bahkan delapan kemenangan itu dicetak Stefano Lilipaly serta kolega secara beruntun, termasuk menang 2-1 atas PS TIRA-Persikabo, pesaing utama mereka dalam perebutan gelar juara Liga 1 2019.,,,Di sepanjang musim ini, pelatih Bali United Stefano Cugurra Teco memiliki dua pola andalan, yakni 4-4-2 dan 4-2-3-1. Ketika bermain 0-0 kontra Bhayangkara FC akhir pekan lalu, pelatih asal Brasil itu menurunkan formasi 4-4-2, dengan menempatkan Spasojevic dan Melvin Platje sebagai ujung tombak kembar.,,Sebelumnya saat meraih delapan kemenangan beruntun, Teco mengandalkan pola 4-2-3-1. Dalam pola tersebut, Teco mengandalkan Spasojevic sebagai ujung tombak, yang disokong playmaker sekelas Paulo Sergio.
Cosine Similarity: 0.1478222906589508

--------------------------------------------------
Title: Tuai Kontroversi, Livi Zheng Enggan Berkomentar
Summary: Sutradara film The Santri,,menolak untuk memberikan komentar terkait filmnya yang kini menjadi kontroversi. Menurut Livi, saat ini proses wawancara hanya bisa dilakukan kepada Imam Pituduh, Produser Eksekutif dari film,.,,‚ÄúKalau untuk The Santri, sementara ini yang bisa diwawancarai baru executive producer-nya saja. Semua wawancara langsung ke Pak Imam,‚Äù kata Livi Zheng saat dihubungi,melalui pesan singkat, Rabu 18 Oktober 2019.,Seperti diketahui, film terbaru Livi Zheng yang berjudul The Santri menuai kontroversi di masyarakat, khususnya kelompok keagamaan. Seperti misalnya ketua Umum Front Santri Indonesia (FSI), Hanfi Alathas yang menyoroti cerita di balik film The Santri, yang menurutnya tak mencerminkan akhlak santri serta tradisi di pesantren.,,Kritikan keras lainnya juga dilontarkan oleh Ustadz Maaher Atthuwailibi melalui unggahan di Facebooknya. Unggahan tersebut kemudian dibagikan sang ustadz di Instagram pribadinya.
Cosine Similarity: 0.46050775051116943

--------------------------------------------------
Title: Canggih, Nginap di Hotel China Dilayani Robot
Summary: Robot, robot dan robot. Itu lah yang akan kita temui jika menginap di salah satu hotel di Hangzhou, China. Berbeda pada umumnya, hotel ini tidak terlalu banyak memperjakan tenaga manusia.,Ini sudah menjadi bukti bahwa robot bisa menggantikan peran manusia dalam dunia kerja.,,Tak hanya robot, hotel ini juga dilengkapi teknologi kecerdasan buatan (,). Lalu apa rasanya menginap dan dilayani robot?,berkesempatan mengunjungi hotel yang bernama FlyZoo Hotel yang terletak di kompleks Alimall, tepat di sebelah kantor pusat Alibaba Hangzhou (Alibaba Campus) di wilayah Xixi, Hangzhou, China.,,Memasuki lobi hotel, kita tidak disambut oleh ucapan selamat datang dan tidak ada resepsionis, melainkan sebuah layar LED besar bertuliskan,.,Saat,, lagi-lagi bukan manusia yang melayani tamu, melainkan sebuah mesin untuk melakukan,.,juga bisa dilakukan melalui aplikasi sebelum tamu menginap.,Tentunya pembayaran di hotel ini menggunakan aplikasi pembayaran QR Code. Setelah sudah,dan melakukan pembayaran, maka tamu akan menuju kamar.,"Ada fitur pengenalan wajah, sehingga para tamu dapat membuka kunci pintu kamar dengan nyaman dan praktis," kata Director, Corporate Affairs Alibaba Group Dian Safitri di Hangzhou, China, Jumat 13 September 2019.,,Dengan sistem pengenalan wajah di hotel, para tamu juga dapat memindai wajah mereka sebagai bukti identitas untuk mengaktifkan elevator, mengakses,, ataupun bersantap di restoran.,Para tamu juga dapat memilih untuk tidak menggunakan sistem pengenalan wajah dan mengakses kamar mereka dan fasilitas hotel dengan cara manual.,Hotel ini terdiri dari 9 lantai.,pun menaiki lift ke lantai 8 dan memasuki sebuah kamar. Tampak tidak ada yang berbeda dibandingkan kamar hotel pada umumnya yang terdiri dari dari toilet, wastafel, kasur, televisi hingga sofa.
Cosine Similarity: 0.13379338383674622

--------------------------------------------------
Title: Video Call, Momen Terakhir Rio Febrian Bersama Ibunda
Summary: Penyanyi,mengaku beberapa kali berinteraksi dengan ibundanya Nancy Kosakoy sebelum dinyatakan wafat pada Senin 16 September.,Menurut,, kondisi sang ibu sempat dinyatakan normal - normal saja sebelum ia berangkat ke Hungaria pada Sabtu 14 September 2019. Rio pun beberapa kali video call dengan sang ibunda meski dalam keadaan sakit.,,"Beberapa hari sebelum berangkat ke Budapest. Masih normal - normal saja, sebelum berangkat ke Budapest pamit, sempat video call juga," ungkap Rio Febrian.,,,,,Namun selama komunikasi melalui video call ini, sang ibunda disebut Rio Febrian tak bisa berbicara apapun dan hanya memandangi wajahnya. "Ngomongnya sudah tidak bisa, hanya ngomong sama kakakku saja," lanjutnya.,Namun saat berada di Budapest ia sempat mendapat kabar dari sang kakak Shinta Shovya bahwa ibunda sedang dalam keadaan kritis.,"Saat berada di sana (Budapest) dapat kabar dari kakak kalau mama tidak sadar dan dibawa ke rumah sakit. Tapi sama dokternya masih diobservasi bilangnya," ungkapnya.,Dari sanalah,akhirnya memutuskan untuk izin ke Dubes Hungaria untuk kembali ke Indonesia guna melihat kondisi sang ibunda. Namun saat perjalanan menuju Surabaya inilah ibunda akhirnya menghembuskan napas terakhir di RS Panti Waluya Sawahan Surabaya pada Senin 16 September 2019 pukul 19.05 WIB.
Cosine Similarity: 0.1373622715473175

--------------------------------------------------
Title: Ducati Melempem di Misano, Domenicali Salahkan Aspal
Summary: ‚Äì CEO Ducati, Claudio Domenicali, mengomentari penampilan para pembalap Ducati di,Menurutnya, penampilan melempem yang ditunjukkan para pembalap Ducati di seri ini terjadi karena faktor aspal yang kurang mendukung.,Para pembalap Ducati memang tak bisa berbicara banyak kala mentas di Sirkuit Misano. Dua rider tim utama Ducati, Andrea Dovizioso dan Danilo Petrucci, hanya menyudahi balapan di urutan keenam dan ke-10. Sementara itu, Jack Miller dari tim satelit Ducati finis di urutan kesembilan dan rekan setimnya, Francesco Bagnaia, gagal menyentuh garis finis.,,,Mendapati hasil ini, Domenicali pun menuding kondisi aspal di Sirkuit Misano jadi penyebab utama. Ia menilai kondisi aspal saat ini kurang cocok dengan motor Ducati, Desmosdici. Karena itu, motor pun tak bisa berakselerasi dengan baik.,,Hal tersebut tentu saja sangat disayangkan oleh Domenicali. Sebab, Ducati sejatinya memiliki peluang besar untuk merebut hasil manis jika tak terkendala masalah tersebut. Sebab musim lalu, Ducati telah membuktikan diri mampu tampil apik di Sirkuit Misano dengan menempatkan Andrea Dovizioso di podium pertama.
Cosine Similarity: 0.11284902691841125

--------------------------------------------------
Title: Shandy Aulia Hobi Pilates saat Hamil, Apa Kata Dokter Kandungan?
Summary: Walau lagi hamil,,tak pantang beraktivitas fisik. Dia pun tetap rajin olahraga demi menjaga kebugaran tubuhnya.,Tapi ada-ada saja netizen julid mengomentari kebiasaan,tersebut. Artis cantik 32 tahun itu bahkan dicap niat rajin olahraga di tengah hamil muda untuk tujuan tak baik.,,,,Padahal menurut Spesialis Obstetri dan Ginekologi Dr dr Ali Sungkar, SpOG, ibu hamil sangat dianjurkan untuk olahraga. Jenisnya yang dipilih harus low impact, agar tidak membahayakan kehamilannya.,"Olahraga dianjurkan untuk ibu hamil untuk memenuhi kebutuhan pengenceran darah, jantungnya dilatih, sehingga punya toleransi untuk penambahan cairan dan oksigen dalam tubuh," ujar Dokter Ali Sungkar ditemui di kawasan Kuningan, Jakarta Selatan, Selasa 17 September 2019.,Dokter Ali Sungkar menyebutkan, olahraga low impact pada,antara lain berenang, jalan kaki, hingga sepeda statis.
Cosine Similarity: 0.531858503818512

--------------------------------------------------
Title: Tren Investasi Emas Digital, soal Fluktuasi Harga Bagaimana?
Summary: ‚Äì Emas merupakan investasi yang paling tua dan dilakukan secara turun temurun. Bahkan, emas pun bisa mengikuti tren teknologi yang terus berkembang.,Salah satunya, investasi emas digital. Berkembangnya investasi emas secara digital makin membuat komoditas ini digemari di berbagai kalangan.,,,Penasihat Keuangan, Prita Ghozie mengatakan bahwa emas juga merupakan salah satu instrumen investasi paling populer dan terus diminati. "(Emas) selalu ada dari tahun ke tahun. Cocok untuk mereka yang ingin lindung nilai karena harganya stabil," ujar Prita, Jakarta, Rabu 18 September 2019.,,,Meningkatnya permintaan akan investasi emas akhirnya menghadirkan cara baru dalam berinvestasi, yaitu melalui cicilan. Cara ini memungkinkan pembeli untuk membeli emas dengan cara yang lebih praktis, aman, dan tentunya secara online.,,,Menurutnya, cicil emas memungkinkan pembeli untuk mengunci harga di awal pembelian agar tidak terpengaruh pada fluktuasi harga yang terjadi saat melakukan angsuran. Pembeli dapat pilih sesuai gramasi yang diinginkan Atau sesuai dengan dana yang dimiliki.
Cosine Similarity: 0.24124470353126526

--------------------------------------------------
Title: Kopi Lucinta Luna Terancam Tak Dapat Sertifikat Halal
Summary: kontroversial,kembali membuat heboh. Kali ini dia mengenalkan bisnis kopinya yang diberi nama cukup vulgar, yaitu KO&THOL.,Majelis Ulama Indonesia (MUI) pun angkat bicara dengan kontroversi yang tengah terjadi ini. Wakil Ketua Komisi Hukum dan Perundangan MUI, Ikhsan Abdullah mengatakan, brand kopi yang diperkenalkan,itu tidak akan diberi sertifikat halal dari Lembaga Pengkajian Pangan, Obat-obatan, dan Kosmetika Majelis Ulama Indonesia (LPPOM MUI) karena mengandung unsur negatif.,,"Jika dia (Lucinta Luna) mengajukan sertifikat halal ke MUI, tidak akan diberi karena mengandung usur negatif, dan berdampak kepada pembentukan nilai di masyarakat. Jadi sudah dipastikan produk nama tersebut di MUI pasti ditolak," ujar Ihksan saat dihubungi Okezone, Rabu 18 September 2019.,Ikhsan juga memaparkan, selain merk kopi,tersebut, yang menjadi permasalahan selanjutnya adalah terdapat gambar yang memperlihatkan suatu anggota tubuh.
Cosine Similarity: 0.4932931959629059

--------------------------------------------------
Title: Ada Satu Catatan Buruk Ronaldo saat Bertemu Atletico Madrid, Apa Itu?
Summary: ‚Äì,memiliki catatan gol apik kontra Atletico Madrid. Dari 33 pertandingan di semua kompetisi kontra,‚Äìjulukan Atletico, pesepakbola 34 tahun itu mengoleksi 25 gol.,Dari 25 gol itu, delapan di antaranya diciptakan Ronaldo di ajang Liga Champions. Akan tetapi, ada satu fakta yang dapat mengganjal usaha Ronaldo dalam upaya membobol gawang lawan saat Juventus bertandang ke markas Atletico di,perdana Grup D Liga Champions 2019-2020, Kamis 19 September 2019 dini hari WIB. Apa itu?,,,Ternyata dari tujuh gol yang dibuat Ronaldo ke gawang Atletico di ajang Liga Champions, tidak ada satu pun yang dicetak di markas sang lawan. Dalam tiga kunjungan ke markas Atletico, Ronaldo tampil memble.,,Momen pertama tersaji di leg I perempatfinal Liga Champions 2014-2015, atau ketika Ronaldo masih membela Real Madrid. Saat itu, skor sama kuat 0-0. Kemudian, Ronaldo juga tidak mencetak gol saat Madrid takluk 1-2 dari Atletico di leg II semifinal Liga Champions 2016-2017.
Cosine Similarity: 0.21194104850292206

--------------------------------------------------
Title: Ini Cara Kementan Dalam Pengamanan Penyaluran Pupuk Bersubsidi
Summary: Pemerintah melakukan segala upaya melalui Perlindungan Petani untuk membantu petani dalam menghadapi permasalahan kesulitan. Seperti memperoleh prasarana dan sarana pertanian, kepastian usaha, resiko harga, atau kegagalan panen. Termasuk dalam mendapatkan pupuk bersubsidi.,Berdasarkan UU 19/2013 tentang perlindungan pemberdayaan petani, Pemerintah dan Pemerintah Daerah sesuai dengan kewenangannya dapat memberikan subsidi benih atau bibit tanaman, bibit atau bakalan ternak, pupuk, dan/atau alat dan mesin pertanian (Alsintan) sesuai dengan kebutuhan.,,Direktur Jenderal Prasarana dan Sarana Pertanian (PSP) Kementerian Pertanian (Kementan) Sarwo Edhy mengatakan, penyaluran pupuk bersubsidi harus diawasi dengan baik. Pola pengamanan dalam penyaluran pupuk bersubsidi juga dilakukan dengan berbagai cara.,"Pertama, pencirian pupuk bersubsidi. Petani harus bisa membedakan pupuk subsidi dengan pupuk non subsidi dan meminimalisir terjadinya penyimpangan. Maka pupuk bersubsidi diberi warna, yaitu Urea Pink dan ZA Oranye," jelas Sarwo Edhy, Jumat (13/92019).,Kemudian, dilakukan pemberlakuan kantong satu merk, bag code, stamp serta call centre pada kantong pupuk bersubsidi. Tujuannya untuk menghindari adanya fanatisme terhadap merk tertentu.,"Juga untuk memudahkan dalam pemenuhan bila terjadi kekurangan pasokan dan untuk menelusuri sumber pupuk berasal bila ditemukan penyimpangan pupuk bersubsidi di lapangan," kata Sarwo Edhy.,Selain itu, juga ada penanganan khusus daerah dengan kuos remote. Kios remote adalah kios yang melayani atau berada di daerah yang sulit dijangkau dalam keadaan normal karena berada di daerah terpencil.,"Langkah-langkah pelayanan kios remote meliputi penambahn gudang penyangga yang berfungsi sebagai titik suplai ke kios remote. Kemudian penyediaan sarana transportasi untuk ke kios remote yang dilaksanakan oleh anak perusahaan. Lalu menginventarisasi kebutuhan pupuk yang akan ditangani di wilayah kios remote," papar Sarwo Edhy.,Pengamanan lainnya berupa pemberlakuan kios pupuk lengkap di seluruh Indonesia. Yakni menyediakan pupuk secara lengkap (Urea, SP-36, ZA, NPK dan Organik) di kios-kios. Juga menigkatkan pelayanan kepada petani, menerapkan program ‚ÄúHET‚Äù tepat, dan dilakukan peningkatan efektifitas aparat di lapangan.,"Juga dilakukan monitoring stok pupuk bersubsidi secara online. System yang dibangun untuk melakukan monitoring stok secara periodic sampai dengan Lini IV. Dan dilanjutkan sistem penebusan pupuk secara online yakni dengan kartu tani," pungkas Sarwo Edhy.,
Cosine Similarity: 0.2152845710515976

--------------------------------------------------
Title: Cerita Umar Jaya, Pembunuh Bayaran Legendaris Paling Sadis di Indonesia

In [23]:
# List to store the results
results = []

# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # Mendapatkan judul yang sesuai dengan summary berdasarkan index
    title = data.loc[data['content'] == index, 'title'].iloc[0]
    similarity_value = cosine_sim_df.loc[index, title]  # Mengakses nilai similarity

    # Menyimpan pasangan dan nilai similarity ke dalam list
    results.append([title, index, similarity_value])

# Membuat DataFrame untuk hasilnya
similarity_df = pd.DataFrame(results, columns=['Title', 'Summary', 'Cosine Similarity'])

In [24]:
similarity_df.head()

,Title,Summary,Cosine Similarity
0,Wanita dengan Tubuh Berisi Terbukti Bikin Pria...,"Berbagai usaha dilakukan, mulai dari olahraga ...",0.119288
1,Kronologi Lengkap Pemuda di Bandung Tusuk Gadi...,"RG (22), pemuda yang nekat menusuk Z (16), sis...",0.132186
2,"Sarapan Bikin Ngantuk, Mitos atau Fakta?","Tak sedikit orang yang beranggapan, bahwa , p...",0.100159
3,Puisi Hairdryer Dian Sastro yang Tak Terduga d...,"Puisi , karya artis peran , ramai diperbinca...",0.632686
4,"Unggah Foto Bersama Habibie, Syahrini: Semoga ...","Penyanyi , turut menyampaikan duka atas menin...",0.144811

## Save Similarity

In [25]:
# Menyimpan DataFrame ke file CSV di lokasi yang ditentukan
similarity_df.to_csv('/content/drive/MyDrive/File/CODES/Similarity/6_Similarity_Berlebihan_Tambahan_Base1/similarity_berlebihan_tambah_base1.csv', index=False)