# Install Library

In [1]:
!pip install transformers
!pip install datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.50.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.29.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Collecting datasets
  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.14)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.29.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.5.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 3.6 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 4.7 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 10.1 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 5.8 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 10.6 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.5.0 dill-0.3.8 fsspec-2024.12.0 multiprocess-0.70.16 xxhash-3.5.0

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Import Library

In [3]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer
from google.colab import drive

# Connect to Drive

In [4]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
# Path folder tempat file CSV berada
combined_df = pd.read_csv('/content/drive/MyDrive/File/CODES/Similarity/7_Similarity_Nonrelevan_Tambahan_Base1/pre_nonrelevan.csv')

combined_df.head()

,title,content
0,Salmafina Sunan Ungkap Sunan Kalijaga Sudah Bi...,"Meski sempat menghilang dan membuat,khawatir, ..."
1,Satria Mulia Oplas Mirip Jimin BTS?,"Nama,mendadak jadi perbincangan fans K-Pop, kh..."
2,Meghan Markle Santai di Acara Olahraga dengan ...,mengejutkan banyak mata dengan kemunculannya d...
3,Mpok Alpa Berbagi Kisah Masa Kecil di Kampung ...,Nama Mpok Alpa mulai dikenal ketika videonya m...
4,Admin Lambe Turah Kenang Perjalanan Karier di ...,"YouTuber,mendapat kesempatan mendatangi salah ..."

In [7]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2967 entries, 0 to 2966
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    2967 non-null   object
 1   content  2963 non-null   object
dtypes: object(2)
memory usage: 46.5+ KB

In [8]:
nan_summary = combined_df[combined_df['content'].isna()]


nan_summary

                                                  title content
406   Teori Baru: Black Widow Ternyata Masih Hidup d...     NaN
1648  INFOGRAFIS: Batik Ternyata Ditemukan di Luar A...     NaN
2562  KAI Umumkan Layanan Kereta Ekspres untuk Wisat...     NaN
2770  INFOGRAFIS: Panduan Mengamankan Data Pribadi d...     NaN

In [9]:
combined_df=combined_df.dropna()

# Duplicate

In [10]:
data = combined_df.copy()

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2963 entries, 0 to 2966
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    2963 non-null   object
 1   content  2963 non-null   object
dtypes: object(2)
memory usage: 69.4+ KB

# Tokenize

Mencoba kode lain agar tokenize lebih mudah di pahami

# Word Embedding

In [12]:
from transformers import AutoTokenizer, AutoModel
import torch

# Memuat IndoBERT dan tokenizer
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1", use_fast=True)
model = AutoModel.from_pretrained("indobenchmark/indobert-base-p1")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

In [ ]:
# Fungsi untuk mendapatkan embedding dari IndoBERT
def get_embeddings(input_ids):
    with torch.no_grad():
        outputs = model(input_ids=input_ids)
    # Mengambil hidden states dari layer terakhir dan rata-rata embeddingsnya
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings

# Fungsi untuk mengonversi tokenized data ke dalam bentuk input_ids dan mendapatkan embedding
def get_input_ids_and_embeddings(data_column):
    input_ids_list = []
    embeddings_list = []

    for text in data_column:
        # Tokenisasi
        tokens = tokenizer(text, padding='max_length', max_length=256, truncation=True, return_tensors="pt")
        input_ids = tokens['input_ids']  # Ambil input_ids
        input_ids_list.append(input_ids)

        # Mendapatkan embeddings
        embedding = get_embeddings(input_ids)
        embeddings_list.append(embedding)

    return input_ids_list, embeddings_list

# Dapatkan input_ids dan embeddings untuk title dan summary
title_input_ids, title_embeddings = get_input_ids_and_embeddings(data['title'])
summary_input_ids, summary_embeddings = get_input_ids_and_embeddings(data['content'])

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

## Mengubah embeddings menjadi array numpy

In [ ]:
# Mengubah embeddings menjadi array numpy agar bisa disimpan dalam DataFrame
title_embeddings_array = np.vstack([embedding.numpy() for embedding in title_embeddings])
summary_embeddings_array = np.vstack([embedding.numpy() for embedding in summary_embeddings])

# Membuat DataFrame baru dengan embeddings numerik
data_embeddings = pd.DataFrame({
    'title_embeddings': list(title_embeddings_array),
    'summary_embeddings': list(summary_embeddings_array)
})

# Cosine Similarity

In [ ]:
# hitung cosine similarity pada matrix berita
cosine_sim = cosine_similarity(title_embeddings_array, summary_embeddings_array)
print(cosine_sim)

[[0.5278511  0.27399862 0.16771808 ... 0.13188232 0.12215213 0.25776255]
 [0.5217369  0.27286768 0.16877824 ... 0.13374084 0.12523636 0.25760067]
 [0.5229429  0.27306226 0.17305252 ... 0.13382775 0.12758663 0.2620887 ]
 ...
 [0.5214254  0.2743776  0.16847709 ... 0.13793203 0.12642518 0.25872248]
 [0.52287346 0.27379805 0.16911002 ... 0.13457265 0.12809786 0.25923714]
 [0.52326506 0.27314982 0.16869836 ... 0.13468611 0.1257148  0.261435  ]]

In [ ]:
# membuat dataframe dari varible cosine similarity dengan baris dan kolom title
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['content'], columns=data['title'])

print(cosine_sim_df.shape)

(2963, 2963)

## Check Similarity Result

In [ ]:
# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # The index is a summary, and you need to find the corresponding title
    # to access the similarity value. However, since you have both summaries
    # and titles as indices, you can access the similarity directly using
    # the index and the corresponding title from the 'data' DataFrame.

    title = data.loc[data['content'] == index, 'title'].iloc[0] # Get the title for the current summary
    similarity_value = cosine_sim_df.loc[index, title]  # Access the similarity using both summary and title

    print(f"Title: {title}")
    print(f"Summary: {index}")
    print(f"Cosine Similarity: {similarity_value}\n")
    print("-" * 50)  # Pemisah antar pasangan

Streaming output truncated to the last 5000 lines.
Title: Adegan Ciuman di Drama Ini Jadi Viral, Tapi Bukan Karena Keromantisannya!
Summary: "," menayangkan episode terbaru pada Sabtu (28/9). Di episode ke-4 itu, drama SBS ini menayangkan sebuah adegan mengejutkan antara Go Hae Ri (,) dan Ki Tae Woong (,).,,,Sebelum dipindahkan ke Maroko, Go Hae Ri rupanya memiliki perasaan suka pada Ki Tae Woong. Dalam keadaan mabuk saat nongkrong bersama tim NIS, Go Hae Ri dengan lantang menyatakan kepemilikannya atas Ki Tae Woong.,Menariknya, Go Hae Ri dengan berani mencium bibir Ki Tae Woong. Tingkah tak sadar agen cantik itu tentunya membuat tim NIS yang lain kaget termasuk Ki Tae Woong sendiri yang tampak hampir marah.,Adegan ciuman pertama di "Vagabond" antara Suzy dan Shin Sung Rok ini tentu saja membuat penonton heboh. Banyak yang menyebut Shin Sung Rok sangat beruntung karena berhasil mendapatkan ciuman Suzy.,,,"," tulis seorang fans. ",," sambung yang lain.,",," sahut fans lain. ",," pungkas fans yang lain.,Sementara itu, episode keempat "Vagabond" itu berhasil mencetak rekor rating baru dengan raihan 6,8 persen, 8,1 persen dan 10,2 persen. Drama yang juga dibintangi oleh,itu akan menayangkan episode terbaru pada Jumat (4/10) mendatang.
Cosine Similarity: 0.165582537651062

--------------------------------------------------
Title: Jusuf Kalla Beri Pernyataan Mengejutkan, Jokowi Langsung Bereaksi!
Summary: Ketidakhadiran Presiden,alias Jokowi dalam agenda Sidang Umum ke-74 Perserikatan Bangsa Bangsa (PBB) di New York menjadi sorotan. Selama ini, wakil Presiden,lah yang selalu mewakili Jokowi di acara tersebut.,,,JK mengatakan bahwa selama ketidakhadiran Jokowi, sejumlah pemimpin dunia kerap menanyakan hal tersebut. "Semua menanyakan, mana pak Joko? Jadi yang ditanya pak Jokowi," kata JK di New York, Amerika Serikat (AS) seperti dilansir dari,, Senin (30/9).,Semenjak dilantik sebagai Presiden pada 2014 lalu, Jokowi memang tidak pernah terlihat hadir dalam Sidang umum PBB. Selama pemerintahan Kabinet Kerja, JK tercatat sudah lima kali mewakili Jokowi untuk hadir di sidang tersebut.,JK menuturkan bahwa ketidakhadiran presiden adalah murni karena kesibukan dalam negeri. Selain itu, ia juga menekankan bahwa penting bagi kepala negara untuk hadir di acara itu.,"Memang tahun ini, kita harapkan beliau hadir. Tapi karena kesibukan di dalam negeri, jadi saya yang pergi untuk mewakili beliau," tutur JK. "Jadi sekali lagi, itu penting bagi suatu kepala negara hadir di sini.",Sementara itu, Tenaga Ahli Kedeputian IV Kantor Staf Kepresidenan Ali Mochtar Ngabalin juga ikut buka suara mengenai absennya Jokowi dalam sidang PBB. Dikatakannya, Jokowi selama lima tahun ini lebih fokus untuk menangani masalah dalam negeri. Meski demikian, bukan berarti Jokowi mengabaikan politik luar negerinya.,"Saya ingin sampaikan bahwa dalam lima tahun kepemimpinan Pak Jokowi, beliau kan lebih berkonsentrasi untuk fokus urusan dalam negeri," kata Ngabalin dilansir dari,, Senin (30/9). "Tapi kan tidak berarti presiden tidak memikirkan tentang kebijakan politik luar negeri.",Meski tidak hadir dalam sidang itu, Ngabalin memastikan bahwa Jokowi tetap memantau perkembangannya. "Dan setiap pelaksanaan PBB presiden juga selalu memantau perkembangannya ya, hari per hari, jam per jam. Baik itu berkomunikasi langsung dengan wakil presiden maupun presiden menerima laporan dari Menlu Ibu Retno," ujar JK.
Cosine Similarity: 0.15598252415657043

--------------------------------------------------
Title: Yasmine Wildblood Lakukan Pemotretan Dengan Heels Tinggi, Tapi Ada Keanehan yang Terungkap!
Summary: dan sang suami, Abi Yapto saat ini tengah menanti kehadiran buah cinta mereka yang kedua. Usia kandungan Yasmine diketahui saat ini sudah memasuki bulan kesembilan. Tak lama lagi, putri sulung Yasmin, Seraphine Rose akan menjadi seorang kakak.,,,Sembari menunggu kelahiran sang buah hati, Yasmine membagikan,dalam postingan Instagram pada Minggu (29/9). Dalam foto tersebut, Yasmine terlihat cantik mengenakan busana panjang dan tertutup berwarna putih.,Dengan riasan sederhana dan rambut dikuncir sebagian ke belakang, Yasmine berpose mengelus perut buncitnya. Bersama dengan postingan tersebut, mantan kekasih,ini mengungkap rasa tak sabar menggendong sang buah hati. ",," tulis Yasmine di bagian,.,,,Postingan Yasmine itu langsung ramai dikomentari warganet. Sejumlah netter langsung memuji kecantikan perempuan kelahiran 1993 itu yang makin terpancar saat hamil. Sementara itu, netter lain juga tak lupa mendoakan persalinan Yasmine berjalan lancar.,",," tulis,. ",," sambung akun,. ",," tambah akun,.,",," komentar akun,. ",," imbuh akun,. ",," seru akun,. ",," tulis akun,.,,,Sementara itu, Yasmine juga membagikan postingan tentang kehamilannya dalam Instagram Story di hari yang sama. Dalam foto tersebut, Yasmine nampak tengah berbaring memperlihatkan perut buncitnya.,Yasmine juga menuai pujian habis-habisan saat belum lama ini hadir di acara pesta. Dalam kesempatan tersebut, Yasmine tampil,memakai,bling-bling berwarna emas sepanjang lutut dipadukan dengan sepatu,cukup tinggi.
Cosine Similarity: 0.10477109253406525

--------------------------------------------------
Title: Ratu Elizabeth Dikabarkan Tak Suka Dengan Kate Middleton, Apakah Ada Konspirasi di Baliknya?
Summary: Menjadi bagian dari anggota keluarga Kerajaan Inggris tentunya bukanlah suatu hal yang mudah. Ada sederet peraturan dan protokol yang tentunya wajib untuk ditaati anggota keluarga tanpa terkecuali, termasuk berpakaian.,,,Bicara soal gaya busana anggota,, mayoritas publik tentunya sangat setuju kalau dua cucu menantu,, yakni,dan,, adalah sosok yang sangat mencuri perhatian. Bahkan tak jarang,kedua wanita cantik tersebut dijadikan sebagai acuan,bagi para wanita era sekarang. Namun faktanya, rupanya Kate dan Meghan sering kali mengabaikan aturan berpakaian yang ditetapkan oleh Ratu Elizabeth.,Setelah menikah dengan,pada 29 April 2011 silam, Kate memang bisa dibilang langsung mudah beradaptasi sebagai anggota keluarga kerajaan. Duchess of Cambridge telah membuktikan bahwa ia dapat diandalkan dalam menuruti sebagian besar aturan Kerajaan, termasuk mengenakan pakaian yang sopan dan tertutup.,Meski demikian, rupanya ada beberapa hal kecil yang tetap dilanggarnya, seperti memakai sepatu wedges yang tidak disukai oleh Ratu Elizabeth. Diketahui, Kate terlihat kerap memakai sepatu wedges di beberapa kesempatan, yang pastinya tidak saat bersama Ratu Elizabeth.,,,"Ratu Elizabeth II bukan penggemar sepatu wedges," kata seorang sumber kepada laman,. "Ia benar-benar tidak menyukai wedges dan itu sudah diketahui para wanita di keluarga Kerajaan Inggris.","Ratu membenci wedges karena sepatu itu mengingatkannya pada kondisi penghematan dan penjatahan selama masa perang. Di masa itu satu hal yang tidak dijatah, yaitu gabus. Jadi, orang menggunakannya untuk membuat sepatu mereka sendiri. Karena gabus itu terlalu lunak sehingga membuat sol dan tumit terpisah," imbuhnya.,,,Duchess of Cambridge bukan satu-satunya anggota keluarga kerajaan yang tetap memilih wedges di beberapa penampilan publik. Meghan Markle pun terlihat memakainya di beberapa kesempatan, contohnya di penampilan pertamanya di tur Afrika Selatan.,Di momen tersebut, Duchess of Sussex ini memakai wedges koleksi Castaner. Tak hanya itu, sebelumnya istri,itu juga sudah pernah mengenakan sepatu wedges tersebut saat kunjungan Kerajaan ke Fiji pada Oktober 2018.
Cosine Similarity: 0.1467113196849823

--------------------------------------------------
Title: BTS Tiba-tiba Ikut Challenge Viral, Ada Tujuan Terselubung?
Summary: TikTok membuat tantangan menyusul dirilisnya "Chicken Noodle Soup" kolaborasi,,(,) dan penyanyi Amerika,. Tantangan diberi nama,di mana pengguna di seluruh dunia ditantang menampilkan koreografi gerakan ayam khas lagu tersebut.,,,Dikatakan bahwa para member BTS akan mengikuti,. J-Hope memulai tantangan sebagai member pertama. Diikuti oleh,,,dan,yang melakukannya secara bersamaan.,Tiga member yang kerap disebut,BTS itu rupanya melakukan tantangan dengan berlebihan dan berisik. Bisa dilihat dari gerakan mereka selama menari. Tak hanya menari, mereka bahkan tertawa dan sesekali berteriak, terutama Jimin yang dari awal sampai akhir terlihat sangat bersemangat.,,,Yang paling disorot adalah bagian akhir di mana mereka menutup tantangan tersebut dengan gerakan ngawur. Jungkook sukses mengundang tawa netizen karena "goyang ngebor" yang dilakukannya sebelum kompak berpose sama dengan V dan Jimin.,"Mereka terlihat bahagia dan lucu. Aku sangat bahagia," komentar salah satu netizen. "Mereka lebay tapi lucu sekali, hahaha. Goyang ngebor Jungkook kocak sekali," tambah netizen lain. "Kenapa Jimin berisik sekali? Hahaha. Mereka imut sekali!" sahut yang lain. "Mereka bahagia dan berisik sekali. Ada apa dengan goyangan Jungkook di bagian akhir? Aku tidak bisa berhenti tertawa melihatnya," pungkas lainnya.,Sementara itu, masa cuti panjang BTS yang diumumkan Big Hit Entertainment pada Agustus lalu telah berakhir. Mereka kembali bekerja dengan menuju Selandia Baru pada 16 September untuk syuting reality show tahunan "Bon Voyage" dan baru pulang pada 24 September.,Selain itu telah dikonfirmasi bahwa BTS akan mengunjungi Arab Saudi untuk konser di King Fahd International Stadium, Riyadh pada 11 Oktober. Mereka juga akan menggelar konser final untuk tur "Love Yourself: Speak Yourself" di Seoul selama tiga hari yaitu 26, 27 dan 29 Oktober.
Cosine Similarity: 0.21831217408180237

--------------------------------------------------
Title: MUI Haramkan Makanan Berlabel Setan, Netizen Langsung Buru-buru Cek Dapur!
Summary: Majelis Ulama Indonesia (MUI) Sumatera Barat menegaskan bahwa penggunaan kata-kata seperti neraka, setan, iblis, untuk digunakan sebagai nama produk makanan, minuman dan lainnya adalah haram hukumnya. Karena pelabelan produk-produk tersebut dilarang dalam Islam.,,,Pelabelan produk dengan menggunakan nama setan, iblis, dan neraka ini disebut Manhiy 'Anhu. "Kalau menyangkut hal-hal yang prinsip di dalam Islam terkait soal akidah seperti kata neraka, setan, iblis maka hukumnya haram," kata Ketua Umum MUI Sumbar, Gusrizal Gazahar dilansir,.,Keputusan bidang fatwa itu diambil melalui Rapat Koordinasi Daerah MUI Sumbar dan MUI Kabupaten/Kota pada 20 Juli 2019. Tak hanya itu, selain soal neraka, ada beberapa nama produk makanan dan minuman yang mengandung unsur seksi.,Terutama yang terkait dengan akhlak dan etika seperti "ayam dada montok", "mie caruik", maka hukumnya adalah makruh. Oleh karena itu, MUI mengeluarkan sejumlah rekomendasi terkait hal itu yaitu kepada pemerintah agar melahirkan regulasi dalam rangka implementasi fatwa ini.,Mereka mendesak agar pemerintah segera menindaklanjuti fatwa tersebut sebagai bentuk imbauan dan sosialisasi kepada masyarakat. MUI Sumbar juga mengimbau semua lapisan masyarakat agar tidak mengkonsumsi produk yang menggunakan nama-nama yang dilarang dalam fatwa ini.,Imbauan ini juga diberikan kepada LPPOM MUI untuk tidak menerbitkan sertifikat halal terhadap produk yang menggunakan nama-nama yang tidak sesuai dengan syariat. Lalu dikeluarkannya fatwa haram terhadap penggunaan nama setan, iblis, dan neraka ini disebabkan karena banyaknya pemakaian kata-kata nyeleneh untuk nama produk kuliner.,Alasan kenapa fatwa ini ingin dipertegas oleh MUI adalah karena nama-nama yang nyeleneh telah menjadi tren sendiri di kalangan anak-anak muda di Sumbar dalam setahun terakhir. Seperti yang diketahui jika produk-produk yang menggunakan kata "neraka", "setan", dan iblis biasanya digunakan untuk menggambarkan tingkat kepedasan yang ekstrim.
Cosine Similarity: 0.198186993598938

--------------------------------------------------
Title: Petani Jambi Ikut Aksi, Tapi Menghilang Secara Misterius!
Summary: Salah seorang perempuan petani Jambi meninggal dunia saat mengikuti,Suku Anak Dalam (SAD) menuju Istana Negara untuk bertemu Presiden,. Aksi jalan kaki tersebut sebagai bentuk protes darI SAD dan petani Jambi kepada Presiden Jokowi terkait konflik lahan yang berkepanjangan dengan perusahaan sawit.,,,Aksi jalan kaki tersebut telah dilakukan sejak pada Rabu (28/8). Rencananya mereka akan beraksi di Istana Negara, Kementerian ATR/BPN, Kementerian Dalam Negeri, KPK, Kemenko Polhukam, Kementerian Pertanian, Kementerian LHK, Mabes Polri, dan Kejaksaan Agung.,Aksi protes ini telah membuat salah satu petani wanita bernama Tamini yang berusia 54 tahun asal Desa Mekar Sari Makmur, Muaro Jambi, Jambi meninggal dunia pada Sabtu (14/9) lalu. Koordinator Lapangan Aksi Jalan Kaki Amiruddin Todak menjelaskan jika Tamini meninggal dunia setelah merasakan sakit setelah melakukan aksi jalan kaki ini.,Amiruddin mengatakan jika wanita yang berusia 54 tahun tersebut menghembuskan nafas untuk terakhir kalinya setelah melakukan aksi jalan kaki selama 13 hari sejak akhir Agustus lalu. "13 hari setelah jalan kaki, Bu Tamini meminta izin karena sakit sehingga kemudian berobat di Rumah Sakit Kecamatan Bahar, Muaro Jambi," kata Amiruddin kepada,, Minggu (29/9).,Tamini yang mengeluhkan sakit ini kemudian langsung dibawa ke Rumah Sakit Kecamatan Bahar, Muaro Jambi untuk dilakukan pengobatan lebih lanjut. Namun karena diduga juga mengalami kelelahan yang parah, nyawa Tamini akhirnya tidak dapat tertolong.,Aksi jalan kaki SAD dan petani Jambi ini sendiri saat ini telah sampai ke Desa Mekar Jaya, Musi Banyuasin, Sumatera Selatan. Amiruddin menuturkan hingga saat ini pihak Istana belum merespons aksi jalan kaki tersebut. Dirinya meminta Presiden Jokowi dapat segera menyelesaikan kasus agraria yang dihadapi oleh SAD dan petani Jambi dengan perusahaan sawit.
Cosine Similarity: 0.14421117305755615

--------------------------------------------------
Title: Konser BLACKPINK Jadi yang Terlaris, Tapi Ada Isu Aneh di Baliknya!
Summary: Salah satu girl grup besutan YG Entertainment, BLACKPINK (,) tahun ini sedang menghadapi jadwal yang super padat. Grup ini baru saja comeback dengan lagu bertajuk "Kill This Love" dan sukses meraih banyak prestasi.,,,Selain itu, BLACKPINK saat ini juga tengah sibuk dengan tur konser mereka bertajuk "In Your Area". BLACKPINK harus rela bolak-balik beberapa negara untuk mengadakan konser di berbagai benua seperti Asia, Amerika dan bahkan Eropa.,Girl grup besutan YG Entertainment ini sudah mulai melakukan tur konsernya pada November 2018 lalu. Mereka akan terus berkeliling dunia hingga Febuari 2020 mendatang. Tak hanya itu, beberapa waktu lalu BLACKPINK berhasil memecahkan rekor yang membanggakan.,Tur konser dunia BLACKPINK baru-baru ini secara resmi melampaui konser,sebagai tur dunia girl grup K-Pop terlaris sepanjang masa. Secara total hingga kini, konser BLACKPINK telah meraup untuk sebanyak 32,2 juta Dollar atau sekitar Rp 456 miliar.,,,Hal ini mengalahkan tur konser milik Girls' Generation "Japan 3rd Tour 2014" yang sukses meraup untung sebanyak 32,6 juta Dollar atau yang setara dengan Rp 448 miliar. Selain itu, BLACKPINK mengungguli konser lain dari Girls' Generation "Phantasia" yang berhasil menghasilkan 22,3 juta Dollar atau setara dengan Rp 316 miliar.,Sebelumnya, BLACKPINK juga meraih prestasi lain mengenai subscibers mereka di YouTube. Channel YouTube resmi BLACKPINK tercatat telah memiliki total 29.897.163 subscribers. Hal ini otomatis menjadikannya channel grup musik dengan jumlah subscribers tertinggi di YouTube.,Rekor ini sebelumnya telah dipegang oleh grup musik terkenal Amerika,,. Grup musik pria ini kini memiliki jumlah pelanggan tertinggi kedua di YouTube yakni 29.886.939 subscribers.,Beberapa waktu lalu Chart Data juga mengumumkan bahwa BLACKPINK menjadi girl grup yang paling banyak ditonton dalam sejarah YouTube. Menurut Chart Data, grup yang digawangi,cs ini telah berhasil melampaui rekor yang sebelumnya dipegang oleh girl grup Amerika,,. Penting untuk dicatat bahwa perhitungan ini hanya untuk video resmi, yang berarti bahwa video buatan fans dan konten yang diunggah ulang tidak akan dihitung.
Cosine Similarity: 0.22079822421073914

--------------------------------------------------
Title: Lucinta Luna Ngaku Rambutnya Bermasalah, Tapi Netizen Punya Teori Lain!
Summary: selalu berusaha tampil semaksimal mungkin di setiap kesempatan. Namun belum lama ini pelantun lagu "Tanpa Status" tersebut menceritakan masalahnya, lantaran rambutnya masih basah.,,,Hal tersebut dikarenakan alat pengering rambut alias,milik Lucinta sedang rusak. Melalui video yang diunggah di Instagram pada Senin (30/9), Lucinta tampak berpose manja sembari menunggu rambutnya kering. "," tulis Lucinta di bagian keterangan Instagram.,,,Akan tetapi, postingan Lucinta tersebut justru membuat para netter mengingat kembali insiden rambut palsu alias wignya lepas beberapa waktu lalu. Kala itu, Lucinta yang kalah beradu panco menjatuhkan dirinya ke lantai hingga membuat,.,Bukan hanya itu, Lucinta juga ketahuan tak memiliki rambut alias botak saat seorang hater,di depan umum. Para netter pun menyarankan Lucinta untuk melepas wig hingga menjemur rambutnya sehingga segera kering.,,,",," sindir akun,. "," imbuh akun,. ",," sahut akun,.,",," komentar akun,. "," tambah akun,. ",," sambung akun,.,Sementara itu, Lucinta sudah memberikan,mengenai alasan kepalanya menjadi botak. Mantan personel,tersebut mengaku memangkas habis rambutnya untuk keperluan syuting sinetron baru.
Cosine Similarity: 0.14463669061660767

--------------------------------------------------
Title: Efek Samping Operasi Salmafina Bikin Makin Kurus, Dokter Langsung Angkat Bicara!
Summary: Sebagai seorang publik figur, menjaga penampilan menjadi suatu hal yang utama. Tak heran apabila sejumlah artis melakukan berbagai cara untuk dapat terus menjaga penampilan mereka.,,,Di sisi lain, operasi sedot lemak dapat menjadi referensi untuk menjaga keseimbangan berat badan. Belum lama ini,sempat menyampaikan bahwa ia akan melakukan,ketika menyadari badannya mulai terlihat gemuk.,Pernyataan Salmafina soal sedot lemak ini lantas ramai diperbincangkan oleh publik. Hingga akhirnya sosoknya kembali disorot ketika Salmafina mengunggah sebuah postingan foto di laman Instagram miliknya.,Jari jemari putri,ini menjadi sorotan ketika akan menyuapkan sesendok pasta ke mulutnya. Pasalnya dalam unggahannya tersebut jemari Salmafina tampak terlihat bengkak.,,,‚Äú,‚Äù tulis Salmafina dalam bahasa Inggris sebagai keterangan pada foto postingannya. Kemudian pada lima hari lalu Salmafina akhirnya menjelaskan bahwa perubahan mengagetkan tersebut karena efek samping dari operasi sedot lemak yang ia lakoni.,,,Dengan memperlihatkan lengan tangan di pantulan cermin, Salmafina mengucapkan syukur akhirnya efek samping yang ia rasakan sudah sedikit berkurang. ‚Äú," ungkap Salmafina.,Unggahan Salamafina ini lantas berhasil menyita perhatian jagat maya di Instagram. Hingga akhirnya banyak netter yang beramai-ramai memberikan tanggapan mereka di kolom komentar.,‚Äú," tulis akun,. ‚Äú,‚Äù komentar akun,dengan menambahkan emoji tertawa. ‚Äú,‚Äù ujar akun,.
Cosine Similarity: 0.19490540027618408

--------------------------------------------------
Title: Anya Geraldine Ngaku Punya Usaha Coffe Shop, Netizen Tak Percaya!

In [ ]:
# List to store the results
results = []

# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # Mendapatkan judul yang sesuai dengan summary berdasarkan index
    title = data.loc[data['content'] == index, 'title'].iloc[0]
    similarity_value = cosine_sim_df.loc[index, title]  # Mengakses nilai similarity

    # Menyimpan pasangan dan nilai similarity ke dalam list
    results.append([title, index, similarity_value])

# Membuat DataFrame untuk hasilnya
similarity_df = pd.DataFrame(results, columns=['Title', 'Summary', 'Cosine Similarity'])

In [ ]:
similarity_df.head()

,Title,Summary,Cosine Similarity
0,Salmafina Sunan Ungkap Sunan Kalijaga Sudah Bi...,"Meski sempat menghilang dan membuat,khawatir, ...",0.527851
1,Satria Mulia Oplas Mirip Jimin BTS?,"Nama,mendadak jadi perbincangan fans K-Pop, kh...",0.272868
2,Meghan Markle Santai di Acara Olahraga dengan ...,mengejutkan banyak mata dengan kemunculannya d...,0.173053
3,Mpok Alpa Berbagi Kisah Masa Kecil di Kampung ...,Nama Mpok Alpa mulai dikenal ketika videonya m...,0.161155
4,Admin Lambe Turah Kenang Perjalanan Karier di ...,"YouTuber,mendapat kesempatan mendatangi salah ...",0.124442

## Save Similarity

In [ ]:
# Menyimpan DataFrame ke file CSV di lokasi yang ditentukan
similarity_df.to_csv('/content/drive/MyDrive/File/CODES/Similarity/7_Similarity_Nonrelevan_Tambahan_Base1/similarity_nonrelevan_tambah_base1.csv', index=False)