# Install Library

In [ ]:
!pip install transformers
!pip install datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Collecting datasets
  Downloading datasets-3.3.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.12)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.3.1-py3-none-any.whl (484 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.9/484.9 kB 16.6 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.1 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 12.2 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 17.5 MB/s eta 0:00:00
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.3.1 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0

# Import Library

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer
from google.colab import drive

# Connect to Drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Path folder tempat file CSV berada
folder_path = "/content/drive/MyDrive/File/CODES/Summarize/3_Summary_Kompas_50_Base1/Sum_Kompas_50_Base1"

# Mengambil semua file dengan ekstensi .csv dalam folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith(".csv")]

# Membaca dan menggabungkan semua file
dataframes = []
for file_name in csv_files:
    file_path = os.path.join(folder_path, file_name)
    df = pd.read_csv(file_path)
    dataframes.append(df)

# Menggabungkan semua DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

In [ ]:
# Menyimpan hasil penggabungan ke file baru
output_path = os.path.join(folder_path, "/content/drive/MyDrive/File/CODES/Similarity/3_Similarity_Kompas_Base1/kompas_sum_50_base1_concat.csv")
combined_df.to_csv(output_path, index=False)

In [ ]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8741 entries, 0 to 8740
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         8741 non-null   object
 1   category      8741 non-null   object
 2   publish_date  8741 non-null   object
 3   author        8741 non-null   object
 4   article_url   8741 non-null   object
 5   content       8741 non-null   object
 6   summary       8741 non-null   object
dtypes: object(7)
memory usage: 478.2+ KB

In [ ]:
combined_df.head()

,title,category,publish_date,author,article_url,content,summary
0,Jokowi Pastikan Kerja Sama Indonesia dan Afrik...,Nasional,2024-09-01,"Haryanti Puspa Sari, Ihsanuddin",https://nasional.kompas.com/read/2024/09/01/21...,"Presiden Joko Widodo Jokowi mengatakan, Indone...","Presiden Joko Widodo Jokowi mengatakan, Indone..."
1,Jokowi Perkenalkan Prabowo di Forum Indonesia ...,Nasional,2024-09-01,"Singgih Wiryono, Ihsanuddin",https://nasional.kompas.com/read/2024/09/01/20...,Presiden Joko Widodo Jokowi memperkenalkan pre...,Presiden Joko Widodo Jokowi memperkenalkan pre...
2,Anies Dinilai Punya Modal Politik untuk Bikin ...,Nasional,2024-09-01,"Syakirun Ni'am, Icha Rastika",https://nasional.kompas.com/read/2024/09/01/13...,Pengamat politik Universitas Islam Negeri UIN ...,Pengamat politik Universitas Islam Negeri UIN ...
3,"Prabowo: Kalau Pun Koruptor Lari ke Antartika,...",Nasional,2024-09-01,"Singgih Wiryono, Icha Rastika",https://nasional.kompas.com/read/2024/09/01/13...,Ketua Umum Ketum Partai Gerindra sekaligus pre...,Ketua Umum Ketum Partai Gerindra sekaligus pre...
4,PDI-P Sebenarnya Sudah Dapat Titik Temu dengan...,Nasional,2024-09-01,"Nicholas Ryan Aditya, Icha Rastika",https://nasional.kompas.com/read/2024/09/01/11...,Ketua DPP PDIP Deddy Yevri Sitorus mengungkapk...,Ketua DPP PDIP Deddy Yevri Sitorus mengungkapk...

In [ ]:
nan_summary = combined_df[combined_df['summary'].isna()]


nan_summary

Empty DataFrame
Columns: [title, category, publish_date, author, article_url, content, summary]
Index: []

In [ ]:
combined_df=combined_df.dropna()

# Duplicate

In [ ]:
data = combined_df.copy()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8741 entries, 0 to 8740
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         8741 non-null   object
 1   category      8741 non-null   object
 2   publish_date  8741 non-null   object
 3   author        8741 non-null   object
 4   article_url   8741 non-null   object
 5   content       8741 non-null   object
 6   summary       8741 non-null   object
dtypes: object(7)
memory usage: 478.2+ KB

# Tokenize

Mencoba kode lain agar tokenize lebih mudah di pahami

# Word Embedding

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch

# Memuat IndoBERT dan tokenizer
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1", use_fast=True)
model = AutoModel.from_pretrained("indobenchmark/indobert-base-p1")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

In [ ]:
# Fungsi untuk mendapatkan embedding dari IndoBERT
def get_embeddings(input_ids):
    with torch.no_grad():
        outputs = model(input_ids=input_ids)
    # Mengambil hidden states dari layer terakhir dan rata-rata embeddingsnya
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings

# Fungsi untuk mengonversi tokenized data ke dalam bentuk input_ids dan mendapatkan embedding
def get_input_ids_and_embeddings(data_column):
    input_ids_list = []
    embeddings_list = []

    for text in data_column:
        # Tokenisasi
        tokens = tokenizer(text, padding='max_length', max_length=256, truncation=True, return_tensors="pt")
        input_ids = tokens['input_ids']  # Ambil input_ids
        input_ids_list.append(input_ids)

        # Mendapatkan embeddings
        embedding = get_embeddings(input_ids)
        embeddings_list.append(embedding)

    return input_ids_list, embeddings_list

# Dapatkan input_ids dan embeddings untuk title dan summary
title_input_ids, title_embeddings = get_input_ids_and_embeddings(data['title'])
summary_input_ids, summary_embeddings = get_input_ids_and_embeddings(data['summary'])

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

## Mengubah embeddings menjadi array numpy

In [ ]:
# Mengubah embeddings menjadi array numpy agar bisa disimpan dalam DataFrame
title_embeddings_array = np.vstack([embedding.numpy() for embedding in title_embeddings])
summary_embeddings_array = np.vstack([embedding.numpy() for embedding in summary_embeddings])

# Membuat DataFrame baru dengan embeddings numerik
data_embeddings = pd.DataFrame({
    'title_embeddings': list(title_embeddings_array),
    'summary_embeddings': list(summary_embeddings_array)
})

# Menyimpan DataFrame embeddings ke dalam file CSV (atau format lain)
# data_embeddings.to_csv('/content/drive/MyDrive/File/CODES/Similarity/Detik Berita/detik_berita_embeddings.csv', index=False)

# Cosine Similarity

In [ ]:
# hitung cosine similarity pada matrix berita
cosine_sim = cosine_similarity(title_embeddings_array, summary_embeddings_array)
print(cosine_sim)

[[0.9121338  0.79156876 0.44168645 ... 0.19062808 0.48020083 0.42453986]
 [0.9077672  0.78760684 0.44080755 ... 0.19101985 0.47997183 0.42366087]
 [0.9092082  0.78886145 0.44180822 ... 0.19118083 0.47919    0.42353004]
 ...
 [0.918085   0.7985732  0.4469295  ... 0.1909951  0.4853959  0.43074894]
 [0.9151063  0.7977096  0.4460653  ... 0.19155326 0.48515156 0.4297856 ]
 [0.92730635 0.8073182  0.45340103 ... 0.18900791 0.48694152 0.43406892]]

In [ ]:
# membuat dataframe dari varible cosine similarity dengan baris dan kolom title
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['summary'], columns=data['title'])

print(cosine_sim_df.shape)

(8741, 8741)

## Check Similarity Result

In [ ]:
# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # The index is a summary, and you need to find the corresponding title
    # to access the similarity value. However, since you have both summaries
    # and titles as indices, you can access the similarity directly using
    # the index and the corresponding title from the 'data' DataFrame.

    title = data.loc[data['summary'] == index, 'title'].iloc[0] # Get the title for the current summary
    similarity_value = cosine_sim_df.loc[index, title]  # Access the similarity using both summary and title

    print(f"Title: {title}")
    print(f"Summary: {index}")
    print(f"Cosine Similarity: {similarity_value}\n")
    print("-" * 50)  # Pemisah antar pasangan

Streaming output truncated to the last 5000 lines.
Title: Jokowi Sebut Kualitas Bibit dan Metode Panen Bakal Tingkatkan Produksi Kelapa RI
Summary: Presiden Joko Widodo menekankan, kualitas bibit dan metode cara panen sangat berpengaruh terhadap peningkatan produksi kelapa di Indonesia. Kepala Negara menuturkan, menyiapkan cara panen bisa dilakukan dengan menyiapkan pemetik buat kelapa. "Kalau kelapanya 20 meter, berapa juta pohon kelapa, berarti berapa orang yang harus disiapkan untuk memetik kelapa itu," ucap dia. Selain dua hal itu, pemeliharaan juga perlu dilakukan. Buahbuah kelapa yang ditanam harus dipelihara agar hasilnya pun bagus. " Biasanya kita menanam, dibiarkan, berbuah, baru diambil. Jadi kualitas bibit, pemeliharaan, dan metode cara panen itu penting," kata Jokowi. Adapun saat ini, Indonesia memiliki luas lahan kelapa sebesar 3,8 juta hektare dengan produksi 2,8 juta ton per tahun. Ini sebuah angka yang sangat besar dan bisa ditingkatkan lagi kalau kita serius.
Cosine Similarity: 0.676742672920227

--------------------------------------------------
Title: Amnesty Internasional Minta DPR Tunda Pengesahan Revisi UU Polri
Summary: Amnesty Internasional Indonesia meminta agar DPR RI menunda pengesahan Revisi UndangUndang RUU Polri. Kami mau bahwa DPR ini menunda pengesahan atau Presiden cabut deh surpresnya yang ada di DPR sebelum ada ruang partisipasi bermakna," ujarnya dalam diskusi bertajuk "Polisi Superbody Siapa yang Mengawasi" di Kantor Amnesty Internasional, Jakarta Pusat, Senin 22 Juli 2024. Selain itu, pemerintah dan DPR juga pasti akan menggunakan dalih judicial review jika koalisi masyarakat sipil tak menerima RUU Polri itu. " Revisi UU Polri Draf revisi UU yang akan mengatur tambahan kewenangan Polri menjadi sorotan sejumlah pihak. Disebutkan, Polri berwenang melakukan penindakan, pemblokiran atau pemutusan, dan upaya perlambatan akses ruang siber untuk tujuan keamanan dalam negeri. Polri juga memiliki wewenang untuk berkoordinasi dengan kementerian yang menyelenggarakan urusan pemerintahan di bidang komunikasi dan informatika penyelenggara jasa telekomunikasi. Selain itu, revisi UU juga mengatur usia pensiun maksimum anggota Polri, Pasal 30 ayat 4 mengatur batas usia pensiun Kapolri atau polisi berpangkat perwira tinggi bintang 4. Namun, tidak diatur secara rinci berapa lama batas usia maksimum pensiun Kapolri bisa diperpanjang.
Cosine Similarity: 0.22672072052955627

--------------------------------------------------
Title: Gerindra Usung Rudy Susmanto Jadi Bakal Calon Bupati Bogor
Summary: Partai Gerindra mengusung kadernya, Rudy Susmanto sebagai bakal calon bupati bacabup Bogor di Pilkada serentak 2024. Hari ini Rudy resmi sebagai calon bupati Bogor. Itu sebabnya saya minta dengan hormat kepada seluruh pengurus ranting, PAC, dan DPC untuk memenangkan Rudy di ganggang di kampungkampung di desadesa," kata Muzani dalam keterangannya, Senin. Ia mengatakan, membangun Kabupaten Bogor tidak mungkin sendirian. Apalagi Bogor menjadi daya tarik wisata warga Jakarta. Hampir setiap pekan, orang Jakarta liburannya ke Bogor. Jumlah penduduk yang besar dan wilayah yang luas jadi tantangan tersendiri. Ini adalah tugas Rudy jika terpilih bupati. Bagaimana orang Bogor menjadi cerdas otaknya, tinggi pendidikannya, sehat badannya, bagus parasnya," jelas Wakil Ketua MPR ini. Kita perlu gubernur, walikota, dan bupati. Kita perlu bekerja sama dengan partai politik lain. Sekarang setelah Pak Prabowo menjadi presiden terpilih, seluruh partai potensial menjadi kekuatan bersama untuk membangun bangsa Indonesia ke depan," tutur Muzani. "
Cosine Similarity: 0.3493284583091736

--------------------------------------------------
Title: Wacana Wajib Asuransi Kendaraan Bermotor, Pemerintah Diharap Tak "Latah"
Summary: Pemerintah diminta tidak menerapkan wacana kewajiban asuransi kendaraan bermotor bagi masyarakat hanya karena ikutikutan negara lain yang sudah memberlakukan kebijakan itu. Bukan dengan gampangnya membebani masyarakat lewat asuransi, terlebih alasannya karena praktik asuransi wajib ini sudah berlaku di berbagai negara lain, kata Suryadi dalam keterangan pers, seperti dikutip pada Senin 22 Juli 2024. Wacana pemberlakuan wajib asuransi third party liability TPL itu dilontarkan oleh Otoritas Jasa Keuangan OJK. Menurut OJK, wacana ketentuan itu berdasarkan UndangUndang Nomor 4 Tahun 2023 tentang Pengembangan dan Penguatan Sektor Keuangan UU P2SK Pasal 39A. Akan tetapi menurut Suryadi, Fraksi PKS di DPR memandang OJK hanya tidak utuh dalam mengutip UU P2SK, dengan alasan Program Asuransi Wajib untuk kendaraan bermotor belum menjadi solusi komprehensif untuk permasalahan yang sesungguhnya. Sebab, kendaraan masyarakat bukan hanya berfungsi untuk alat transportasi tapi juga alat produksi. Oleh karena itu, Suryadi mengingatkan, jika ternyata wacana kewajiban asuransi bagi kendaraan itu mendapatkan penolakan keras dari masyarakat sehingga Peraturan Pemerintah PP tidak disetujui oleh DPR, maka pemerintah tidak boleh asal memberlakukan asuransi itu.
Cosine Similarity: 0.2523317337036133

--------------------------------------------------
Title: Sebut Konflik di Pulau Haruku Selesai, Moeldoko Tegaskan Bukan Disebabkan Agama
Summary: Kepala Staf Kepresidenan, KSP Moeldoko mengatakan, saat ini konflik sosial antara masyarakat Desa Ori Pelauw dengan warga Desa Kariuw, Pulau Haruku, Kabupaten Maluku Tengah, Provinsi Maluku telah selesai. Menurutnya, pemerintah sudah membantu penanganan konflik dengan melibatkan berbagai pihak terkait. Konflik sosial di Pulau Haruku saat ini sudah dinyatakan selesai. Kami sampaikan bahwa konflik ini bukan konflik agama namun konflik tapal batas," ujar Moeldoko di Gedung Bina Graha, Jakarta, Senin 22 Agustus 2024. " Akibatnya, terdapat 1.234 jiwa atau 330 Kepala Keluarga terpaksa harus mengungsi. Selain melakukan serangkaian rapat koordinasi bersama pemerintah daerah dan kementerian/lembaga, KSP juga melakukan verifikasi lapangan, dengan mengunjungi lokasi konflik, dan lokasi pengungsian di negeri Aboru. Saat ini masih ada 801 jiwa yang tidur di tenda. Sehingga dalam waktu singkat pihak Kementerian Pekerjaan Umum dan Perumahan Rakyat PUPR akan menyelesaikan 207 unit rumah untuk warga. Situasi saat ini sudah jauh lebih baik dibanding beberapa tahun lalu sehingga diharapkan peran pemerintah daerah bisa lebih lead proses pemulihan, katanya. Diberitakan sebelumnya, bentrokan antara warga Desa OriPelauw dan Kariuw terjadi pada 26 Januari 2022 lalu. Dalam bentrokan itu, tiga warga meninggal dunia dan dua lainnya terluka. Bentrokan juga menyebabkan ratusan rumah warga hangus terbakar.
Cosine Similarity: 0.13513773679733276

--------------------------------------------------
Title: Ungkap Wejangan Surya Paloh, Kaesang: Jangan Pernah Berhenti 5-6 Pemilu Ke Depan
Summary: Ketua Umum Partai Solidaritas Indonesia PSI Kaesang Pangarep mengaku diberikan wejangan atau nasihat oleh Ketua Umum Partai Nasdem Surya Paloh saat keduanya bertemu di Nasdem Tower, Gondangdia, Jakarta Pusat, Senin 22 Juli 2024. Wejangan itu agar Kaesang tidak berhenti berpolitik hingga 56 pemilihan umum Pemilu mendatang. " Setelah itu silakan istirahat, sudah itu saja," kata Kaesang ditemui usai pertemuan. Kaesang melanjutkan, dirinya menyampaikan ucapan selamat ulang tahun kepada Surya Paloh dalam pertemuan tertutup itu. Pembicaraan itu tentang bagaimana kerja sama atau koalisi antara PSI dan Nasdem untuk Pilkada di Indonesia Timur.
Cosine Similarity: 0.9209238290786743

--------------------------------------------------
Title: Menimbang Gagasan Dewan Pertimbangan Agung
Summary: Oleh Prof. Dr. Rasji, S.H., M.H. AKHIRakhir ini muncul gagasan pembentukan kembali Dewan Pertimbangan Agung DPA. Gagasan Presidensial Club disambut baik oleh banyak pihak, termasuk presiden dan wakil presiden terpilih, wakil presiden definitif, hingga Ketua Majelis Permusyawaratan Rakyat MPR. Gagasan pembentukan DPA terus berkembang. Seorang ahli Hukum Tata Negara menyambut baik pembentukan DPA untuk menggantikan Dewan Pertimbangan Presiden Wantimpres. Gagasan perubahan lembaga Wantimpres menjadi DPA masih menimbulkan pemahaman yang berbeda. Pembentukan kembali DPA juga dipertanyakan urgensi dan efektivitasnya, mengingat sebelumnya lembaga DPA telah ada, namun dihapus ditiadakan dalam sistem ketatanegaraan sejak amandemen UUD 1945 tahun 2002. Tugasnya adalah wajib memberi jawaban atas pertanyaan presiden dan berhak mengajukan usul kepada Pemerintah. Kemudian UUD 1945 mendelegasikan pengaturan lebih lanjut susunan DPA kepada lagislator untuk ditetapkan dengan UU. Pada mulanya DPA dibentuk pada 25 September 1945, berdasarkan pengumuman pemerintah, yang beranggotakan sebelas orang. Kemudian lembaga DPA diatur lebih lanjut dengan UndangUndang Nomor 3 Tahun 1967 tentang Dewan Pertimbangan Agung, yang telah diubah dengan UndangUndang Nomor 4 Tahun 1978 tentang Perubahan dan Penyempurnaan UndangUndang Nomor 3 Tahun 1967 tentang Dewan Pertimbangan Agung. Karena itu, pertimbangan perubahan UU DPA bertujuan mencapai daya guna dan hasil guna DPA sebesarbesarnya. Salah satu lembaga negara yang dievaluasi adalah DPA. Hasil evaluasi dituangkan ke dalam UUD 1945 perubahan. Salah satu perubahannya adalah aturan DPA dihapus dari ketentuan UUD 1945, yang berarti DPA dihapus dari sistem ketatanegaraan Indonesia.
Cosine Similarity: 0.2079988420009613

--------------------------------------------------
Title: Lantik Perwira Karier, Panglima Agus Sebut Tantangan dan Tuntutan Tugas TNI Makin Kompleks
Summary: Panglima TNI Jenderal Agus Subiyanto mengatakan bahwa tantangan dan tuntutan tugas TNI semakin kompleks. Tantangan dan tuntutan tugas TNI ke depan akan semakin kompleks, dihadapkan dinamika perkembangan strategis, baik tingkat global, regional dan nasional, ujar Agus. Oleh karena itu, Agus meminta para perwira yang dilantik agar mengembangkan pengetahuan dan keterampilan yang didapat selama proses pendidikan di Komando Pembinaan Doktrin, Pendidikan, dan Latihan Kodiklat TNI. Sebagai perwira remaja, kalian dituntut menjawab berbagai tantangan, perkembangan dan perubahan situasi serta menjadi teladan bagi anggota. Sebanyak 350 prajurit karier itu terdiri dari 141 personel matra darat 127 lakilaki dan 14 perempuan, 108 personel matra laut 89 lakilaki dan 19 perempuan, dan 101 personel matra udara 94 lakilaki dan 7 perempuan.
Cosine Similarity: 0.8577091693878174

--------------------------------------------------
Title: Cak Imin: Pansus Haji Akan Fokus pada Persoalan Visa yang Tak Sesuai Aturan
Summary: Wakil Ketua DPR RI Muhaimin Iskandar mengungkapkan bahwa dirinya telah menandatangani izin rapat Panitia Khusus Pansus Hak Angket terkait penyelenggaraan Ibadah Haji 2024. Kemudian, pria yang karib disapa Cak Imin ini menyebut bahwa pansus kemungkinan bakal fokus pada visa haji yang penggunaannya tidak sesuai aturan. Padahal, menurut dia, rapat tersebut juga sudah mendapatkan izin dari Ketua DPR Puan Maharani. Luluk mengatakan, masalah teknis itu terkait pelaksanaan rapat yang digelar di tengah masa reses. Salah satunya, masalah visa dan kuota haji khusus. " Padahal, dia menegaskan bahwa seharusnya kuota haji khusus tersebut hanya delapan persen atau sekitar 1.600 orang. " Luluk juga mengatakan, hal tersebut mengabaikan dan melanggar Keputusan Presiden Kepres Nomor 6 Tahun 2024 tentang Pembiayaan Haji yang telah didasarkan pada asumsi jumlah jemaah haji yang sudah diputuskan pada saat rapat kerja bersama dengan Menteri Agama Yaqut Cholil Qoumas. " Kita ingin lah jangan ada rente, ada mafiamafiaan, apalagi masalah haji ya kan, katanya. " Kita akan selidiki apakah pengalihan ini ternyata diikuti dengan tindakan rente yang itu kemudian memberikan keuntungan, ujar Luluk melanjutkan.
Cosine Similarity: 0.18037134408950806

--------------------------------------------------
Title: Masih Banyak Kendala, Pembatasan BBM Subsidi Diimbau Tak Terburu-buru
Summary: Pemerintah diminta tidak terburuburu dalam memutuskan pembatasan distribusi bahan bakar minyak BBM bersubsidi karena sejumlah sarana penunjang dinilai belum siap. Baiknya kebijakan itu diberlakukan ketika sistem pemantauan distribusi dan kategori kendaraan yang dibolehkan menggunakan BBM bersubsidi serta sistem dan instrumen pembatasan BBM bersubsidi sudah siap, kata Anggota Komisi VII Dewan Perwakilan Rakyat DPR dari Fraksi Partai Keadilan Sejahtera PKS, Mulyanto, dalam keterangan pers seperti dikutip pada Senin 22 Juli 2024. Menurut Mulyanto, dari peninjauan Komisi VII DPR, ditemukan masih banyak kendala terkait program digitalisasi sebagai instrumen pembatasan dan pengawasan untuk implementasi BBM tepat sasaran pada tahun anggaran 2025 mendatang. Selain itu, kata Mulyanto, infrastruktur jaringan Internet di wilayah terpencil tidak stabil, terutama pada daerahdaerah pelosok seperti di Nusa Tenggara Timur NTT dan Madura, Jawa Timur. Itu yang disampaikan pihak Pertamina saat pembahasan kondisi lapangan, ujar Mulyanto. Serta merevisi regulasi terkait, yakni Perpres Nomor 191 tahun 2014 tentang Penyediaan, Pendistribusian dan Harga Jual Eceran Bahan Bakar Minyak. Pemerintah, kata Airlangga, akan mengelompokkan masyarakat yang berhak membeli BBM subsidi. Mantan Menteri Perindustrian ini menuturkan, pemerintah pun akan mensosialisasikan penerapan program BBM bersubsidi baru kepada masyarakat. Namun, program tersebut akan disosialisasikan pada 1 September 2024.
Cosine Similarity: 0.16067485511302948

--------------------------------------------------
Title: Kata Mahfud MD soal Usul Penghapusan Aturan Prajurit TNI Tak Boleh Berbisnis
Summary: Mantan Menteri Koordinator Bidang Politik, Hukum, dan Keamanan Menko Polhukam Mahfud MD menanggapi soal revisi UndangUndang UU Nomor 34 Tahun 2004 tentang TNI yang belakangan menuai pro dan kontra. Pasalnya, ada usulan dari Mabes TNI agar aturan mengenai prajurit dilarang terlibat kegiatan bisnis sebagaimana bunyi Pasal 39 Ayat 3 dihapuskan dalam revisi yang tengah dibahas di DPR RI. Yang saya yakini setiap perubahanperubahan itu akan menimbulkan akibatakibat baru. Lalu, dia mau tidak mau ikut membantu sang istri. " Prajurit dilarang terlibat di dalam kegiatan bisnis. Oleh karena itu, kami sarankan ini dibuang, kata Kresno dalam acara di Hotel Borobudur, Jakarta Pusat pada 11 Juli 2024, dipantau dari kanal YouTube Kemenko Polhukam. Iya tidak ada di draf," ujar Meutya saat dikonfirmasi pada 15 Juli 2024. " Jika bentuk koperasi resmi masih dimungkinkan untuk kesejahteraan prajurit saja. Tapi bisnis tidak boleh, katanya melanjutkan. Untuk diketahui, DPR menyetujui revisi UU TNI dalam sidang paripurna ke18 yang dipimpin oleh Wakil Ketua DPR RI dari Fraksi Partai Gerindra, Sufmi Dasco Ahmad di Ruang Rapat Paripurna DPRRI, Kompleks Parlemen, Jakarta Pusat pada 28 Mei 2024.
Cosine Similarity: 0.20509371161460876

--------------------------------------------------
Title: Kemenlu RI Sebut Putusan ICJ Tegaskan Israel Tak Punya Hak Apa Pun di Palestina
Summary: Kementerian Luar Negeri Kemenlu mendukung keputusan Mahkamah International atau ICJ yang menyatakan tindakan Israel menduduki wilayah Palestina adalah ilegal. Arti penting keputusan ICJ yang baru lalu, pertama adalah bangsa Palestina memiliki hak untuk menentukan nasibnya sendiri dan ini dengan teritori tepi barat, Sungai Jordan dan Gaza, ujar Abdul di Gedung Kemenlu, Senin 22 Juli 2024. Selain itu, tindakan Israel yang menduduki paksa wilayah tersebut dengan cara kekerasan adalah tindakan melawan hukum. Abdul menerangkan bahwa selama ini Israel berdalih memiliki hak atas wilayah Palestina berdasarkan catatan sejarah yang mereka miliki. Sebab, argumentasi yang selama ini dinyatakan Israel dan beberapa negara afiliasinya dianggap tak cukup atau kurang memadai. " Karenanya konsekuensinya adalah keberadaan Israel di Tepi Barat, Sungai dan Gaza harus segera diakhiri, pungkasnya. Pengadilan telah memutuskan kehadiran Israel yang terus berlanjut di Wilayah Palestina adalah ilegal," kata Hakim Ketua Mahkamah Internasional ICJ Nawaf Salam, dikutip dari AFP. ICJ menambahkan, Israel berkewajiban untuk segera menghentikan semua kegiatan permukiman baru dan mengevakuasi semua pemukim dari tanah Palestina yang diduduki. Namun, dalam kasus ini, pendapatnya tidak mengikat, meskipun sebagian besar pendapat penasihat sebenarnya ditindaklanjuti.
Cosine Similarity: 0.14498308300971985

--------------------------------------------------
Title: Jelang Pilkada, Jaksa Agung: Netralitas Adhyaksa Harga Mati!
Summary: Jaksa Agung RI Sanitiar Burhanudddin menegaskan bahwa jajaran kejaksaan harus bersikap netral pada pelaksanaan Pemilihan Kepala Daerah Pilkada serentak 2024 mendatang. Saya tegaskan, tidak ada ruang politik praktis bagi kita. Burhanuddin pun berharap kinerja jajarannya semakin baik dan instansi kejaksaan semakin jaya. Burhanuddin mengeklaim, kinerja Kejaksaan menunjukkan tren positif dalam lima tahun terakhir. Kejaksaan mampu hadir untuk menjawab harapan masyarakat dan bangsa dalam mewujudkan keadilan, kemanfaatan dan kepastian hukum serta mampu melaksanakan penegakan hukum dan pemberantasan kejahatan tanpa pandang bulu namun dengan tetap menjaga sisi humanis, kata dia. Menurut Jaksa Agung, keberhasilan ini merupakan hasil kerja keras seluruh insan Adhyaksa dalam setiap pelaksanaan tugas dan wewenangnya. Dia pun meminta keberhasilan kinerja tersebut bisa dijaga, dirawat, dan terus ditingkatkan.
Cosine Similarity: 0.7909929156303406

--------------------------------------------------
Title: Berjas, Kaesang Pimpin Jajaran PSI Temui DPP Nasdem di Gondangdia
Summary: Dewan Pimpinan Pusat DPP Partai Solidaritas Indonesia PSI mendatangi kantor DPP Partai Nasdem atau biasa dikenal Nasdem Tower, di Gondangdia, Jakarta Pusat, Senin 22 Juli 2024. Kaesang berstelan jas cokelat krem dengan dalaman putih. Robert Rouw dan Kaesang beserta jajaran PSI lalu masuk ke gedung Nasdem Tower. Ditanya terkait kunjungannya ke Nasdem, Kaesang tak ingin membeberkannya saat ini. "Nanti saja, ya," kata Kaesang saat ditemui sembari berjalan kecil. Namun sebelumnya, Kaesang diketahui sudah mengunjungi sejumlah partai politik, antara lain Partai Keadilan Sejahtera PKS dan Partai Golkar.
Cosine Similarity: 0.9206559658050537

--------------------------------------------------
Title: Kejagung Pulihkan Rp 1,3 Triliun Kerugian Keuangan Negara dalam 6 Bulan Terakhir
Summary: Jaksa Agung Sanitiar Burhanuddin membeberkan sederet pencapaian Korps Adhyaksa dalam periode enam bulan terakhir atau semester 1 tahun 2024. Berdasarkan data Kejagung, Direktorat Jaksa Agung Muda bidang Tindak Pidana Khusus telah melakukan penyelamatan dan pemulihan kerugian keuangan negara kurang lebih sebesar Rp 1,3 triliun. Hal ini juga diungkap Jaksa Agung dalam pidatonya di Upacara Peringatan Hari Bhakti Adhyaksa ke64 Tahun 2024 pada Senin 22 Juli 2024. Capaian di atas merupakan hasil kerja keras kita bersama dalam memberikan yang terbaik untuk institusi dan negeri," kata Jaksa Agung Sanitiar Burhanuddin. Menurut Jaksa Agung, per 12 Juni 2024 lalu penyerapan anggaran Kejaksaan RI mencapai persentase 49,50 persen atau senilai Rp 9.218.897.941.018. Lalu, telah dilaksanakan penangkapan 73 orang buronan dalam enam bulan terakhir ini. Di bidang Tindak Pidana Umum juga telah diselesaikan 46.300 perkara dan sebanyak 55.202 pelimpahan perkara tahap II.
Cosine Similarity: 0.4531306028366089

--------------------------------------------------
Title: Cari Kesamaan dengan PDI-P, PKB Bicara Kans Dukung Risma atau Marzuki Mustamar pada Pilkada Jatim

In [ ]:
# List to store the results
results = []

# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # Mendapatkan judul yang sesuai dengan summary berdasarkan index
    title = data.loc[data['summary'] == index, 'title'].iloc[0]
    similarity_value = cosine_sim_df.loc[index, title]  # Mengakses nilai similarity

    # Menyimpan pasangan dan nilai similarity ke dalam list
    results.append([title, index, similarity_value])

# Membuat DataFrame untuk hasilnya
similarity_df = pd.DataFrame(results, columns=['Title', 'Summary', 'Cosine Similarity'])

In [ ]:
similarity_df.head()

,Title,Summary,Cosine Similarity
0,Jokowi Pastikan Kerja Sama Indonesia dan Afrik...,"Presiden Joko Widodo Jokowi mengatakan, Indone...",0.912134
1,Jokowi Perkenalkan Prabowo di Forum Indonesia ...,Presiden Joko Widodo Jokowi memperkenalkan pre...,0.787607
2,Anies Dinilai Punya Modal Politik untuk Bikin ...,Pengamat politik Universitas Islam Negeri UIN ...,0.441808
3,"Prabowo: Kalau Pun Koruptor Lari ke Antartika,...",Ketua Umum Ketum Partai Gerindra sekaligus pre...,0.915256
4,PDI-P Sebenarnya Sudah Dapat Titik Temu dengan...,Ketua DPP PDIP Deddy Yevri Sitorus mengungkapk...,0.159616

## Save Similarity

In [ ]:
# Menyimpan DataFrame ke file CSV di lokasi yang ditentukan
similarity_df.to_csv('/content/drive/MyDrive/File/CODES/Similarity/3_Similarity_Kompas_Base1/similarity_kompas_base1.csv', index=False)