# Install Library

In [ ]:
!pip install transformers
!pip install datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.12)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 8.9 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 5.1 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 10.5 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 13.2 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 12.9 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.5.1+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.5.1+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.2.0 dill-0.3.8 fsspec-2024.9.0 multiprocess-0.70.16 xxhash-3.5.0

# Import Library

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer
from google.colab import drive

# Connect to Drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Path folder tempat file CSV berada
folder_path = "/content/drive/MyDrive/File/CODES/Summarize/2_Summary_Detik_Hot_50_Base1/Sum_Detik_Hot_50_Base1"

# Mengambil semua file dengan ekstensi .csv dalam folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith(".csv")]

# Membaca dan menggabungkan semua file
dataframes = []
for file_name in csv_files:
    file_path = os.path.join(folder_path, file_name)
    df = pd.read_csv(file_path)
    dataframes.append(df)

# Menggabungkan semua DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

In [ ]:
# Menyimpan hasil penggabungan ke file baru
output_path = os.path.join(folder_path, "/content/drive/MyDrive/File/CODES/Similarity/2_Similarity_Detik_Hot_Base1/detikhot_sum_50_base1_concat.csv")
combined_df.to_csv(output_path, index=False)

In [ ]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2063 entries, 0 to 2062
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         2063 non-null   object
 1   category      2063 non-null   object
 2   publish_date  2063 non-null   object
 3   author        2063 non-null   object
 4   article_url   2063 non-null   object
 5   content       2063 non-null   object
 6   summary       2063 non-null   object
dtypes: object(7)
memory usage: 112.9+ KB

In [ ]:
combined_df.head()

,title,category,publish_date,author,article_url,content,summary
0,Pentingnya Hak Cipta dan Perlakuan Maksimal un...,detikHot,2024-07-01,Mauludi Rismoyo,https://hot.detik.com/music/d-7417986/pentingn...,Perseteruan Ahmad Dhani dan Once beberapa wakt...,Perseteruan Ahmad Dhani dan Once beberapa wakt...
1,Okan Kornelius Pakai Kemeja Pink dan Dapat Kej...,detikHot,2024-07-01,prih febriani,https://hot.detik.com/celeb/d-7417696/okan-kor...,Artis Okan Kornelius saat ini diketahui tengah...,Artis Okan Kornelius saat ini diketahui tengah...
2,Ayu Ting Ting Putus dengan Muhammad Fardhana,detikHot,2024-07-01,Muhammad Ahsan Nurrijal,https://hot.detik.com/celeb/d-7418047/ayu-ting...,Pedangdut Ayu Ting Ting rupanya sudah tak menj...,Pedangdut Ayu Ting Ting rupanya sudah tak menj...
3,Dion Wiyoko Ajak Anak Muda Tak Takut Berkeringat,detikHot,2024-07-01,Dicky Ardian,https://hot.detik.com/hottainment/d-7417905/di...,Siapa sangka aktor Dion Wiyoko dulunya jago ol...,Siapa sangka aktor Dion Wiyoko dulunya jago ol...
4,Denny Sumargo Ungkap Kondisi Janin di Kandunga...,detikHot,2024-07-01,Febryantino Nur Pratama,https://hot.detik.com/celeb/d-7416625/denny-su...,"Aktor dan mantan atlet basket, Denny Sumargo b...","Aktor dan mantan atlet basket, Denny Sumargo b..."

In [ ]:
nan_summary = combined_df[combined_df['summary'].isna()]


nan_summary

Empty DataFrame
Columns: [title, category, publish_date, author, article_url, content, summary]
Index: []

In [ ]:
combined_df=combined_df.dropna()

# Duplicate

In [ ]:
data = combined_df.copy()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2063 entries, 0 to 2062
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         2063 non-null   object
 1   category      2063 non-null   object
 2   publish_date  2063 non-null   object
 3   author        2063 non-null   object
 4   article_url   2063 non-null   object
 5   content       2063 non-null   object
 6   summary       2063 non-null   object
dtypes: object(7)
memory usage: 112.9+ KB

# Tokenize

In [ ]:
# tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p2", use_fast=True)
# tokenizer.add_tokens([ 'NaN' ])

In [ ]:
# def tokenize_function(text):
#     return tokenizer(text, padding='max_length', max_length=256, truncation=True)

# # Tokenisasi kolom 'title' dan 'summary'
# data['tokenized_title'] = data['title'].apply(lambda x: tokenize_function(x))
# data['tokenized_summary'] = data['summary'].apply(lambda x: tokenize_function(x))

In [ ]:
# data.head()

In [ ]:
# # Menampilkan hasil tokenisasi untuk 'tokenized_title' dan 'tokenized_content'
# print("Tokenized Title:")
# print(data[['title', 'tokenized_title']])

# print("\nTokenized summary:")
# print(data[['summary', 'tokenized_summary']])

# # Menampilkan hanya input_ids yang lebih mudah dibaca
# print("\nInput IDs for Tokenized Title:")
# print(data['tokenized_title'].apply(lambda x: x['input_ids']))

# print("\nInput IDs for Tokenized summary:")
# print(data['tokenized_summary'].apply(lambda x: x['input_ids']))

Mencoba kode lain agar tokenize lebih mudah di pahami

# Word Embedding

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch

# Memuat IndoBERT dan tokenizer
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1", use_fast=True)
model = AutoModel.from_pretrained("indobenchmark/indobert-base-p1")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

In [ ]:
# Fungsi untuk mendapatkan embedding dari IndoBERT
def get_embeddings(input_ids):
    with torch.no_grad():
        outputs = model(input_ids=input_ids)
    # Mengambil hidden states dari layer terakhir dan rata-rata embeddingsnya
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings

# Fungsi untuk mengonversi tokenized data ke dalam bentuk input_ids dan mendapatkan embedding
def get_input_ids_and_embeddings(data_column):
    input_ids_list = []
    embeddings_list = []

    for text in data_column:
        # Tokenisasi
        tokens = tokenizer(text, padding='max_length', max_length=256, truncation=True, return_tensors="pt")
        input_ids = tokens['input_ids']  # Ambil input_ids
        input_ids_list.append(input_ids)

        # Mendapatkan embeddings
        embedding = get_embeddings(input_ids)
        embeddings_list.append(embedding)

    return input_ids_list, embeddings_list

# Dapatkan input_ids dan embeddings untuk title dan summary
title_input_ids, title_embeddings = get_input_ids_and_embeddings(data['title'])
summary_input_ids, summary_embeddings = get_input_ids_and_embeddings(data['summary'])

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

## Mengubah embeddings menjadi array numpy

In [ ]:
# Mengubah embeddings menjadi array numpy agar bisa disimpan dalam DataFrame
title_embeddings_array = np.vstack([embedding.numpy() for embedding in title_embeddings])
summary_embeddings_array = np.vstack([embedding.numpy() for embedding in summary_embeddings])

# Membuat DataFrame baru dengan embeddings numerik
data_embeddings = pd.DataFrame({
    'title_embeddings': list(title_embeddings_array),
    'summary_embeddings': list(summary_embeddings_array)
})

# Menyimpan DataFrame embeddings ke dalam file CSV (atau format lain)
# data_embeddings.to_csv('/content/drive/MyDrive/File/CODES/Similarity/Detik Berita/detik_berita_embeddings.csv', index=False)

# Cosine Similarity

In [ ]:
# hitung cosine similarity pada matrix berita
cosine_sim = cosine_similarity(title_embeddings_array, summary_embeddings_array)
print(cosine_sim)

[[0.4200536  0.5428125  0.364487   ... 0.8739842  0.53526455 0.76630294]
 [0.42167103 0.54701763 0.3654223  ... 0.8803202  0.53826904 0.7710594 ]
 [0.4178853  0.5411078  0.3642066  ... 0.87328076 0.5335995  0.76440597]
 ...
 [0.41769448 0.5417557  0.36280203 ... 0.87655383 0.5346513  0.76789296]
 [0.4185007  0.5411456  0.36328658 ... 0.8742609  0.5352633  0.76581323]
 [0.41965622 0.54442537 0.36279303 ... 0.8804164  0.536415   0.7713593 ]]

In [ ]:
# membuat dataframe dari varible cosine similarity dengan baris dan kolom title
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['summary'], columns=data['title'])

print(cosine_sim_df.shape)

(2063, 2063)

## Check Similarity Result

In [ ]:
# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # The index is a summary, and you need to find the corresponding title
    # to access the similarity value. However, since you have both summaries
    # and titles as indices, you can access the similarity directly using
    # the index and the corresponding title from the 'data' DataFrame.

    title = data.loc[data['summary'] == index, 'title'].iloc[0] # Get the title for the current summary
    similarity_value = cosine_sim_df.loc[index, title]  # Access the similarity using both summary and title

    print(f"Title: {title}")
    print(f"Summary: {index}")
    print(f"Cosine Similarity: {similarity_value}\n")
    print("-" * 50)  # Pemisah antar pasangan

Streaming output truncated to the last 5000 lines.
Title: Thalita Latief Nyaman dengan Cara Kekasih Dekati Anak
Summary: Artis Thalita Latief menceritakan kekasihnya, Ichsan Reinaldy sudah sangat dekat dengan putra semata wayangnya. Surprisingly atau mungkin karena dia juga punya banyak ponakan kali. Saya nggak pernah kayak gitu," kata Thalita Latief ditemui di Studio Trans TV, Jakarta Selatan, kemarin. Di sisi lain, Thalita menilai sosok Ichsan pantang menyerah membangun kedekatan dengan putranya. Bahkan mantan istri Dennis Lyla itu menyebut putranya sangat menerima sosok Ichsan. "Dia juga effortless, benar-benar apa adanya aja. Pasangan aku bisa support hobi dia (anak). Pasangan bisa dekat dengan anak menjadi hal penting untuk Thalita. " Sekarang dapat deh tuh ibaratnya gengnya. Jadi ya sudah selama pasangan ini suka dan enjoy tidak terganggu ya silakan aja yang penting ya aku penginnya Rafello merasa nyaman," tukas Thalita Latief.
Cosine Similarity: 0.4998360872268677

--------------------------------------------------
Title: Al Ghazali Tak Masalah El atau Dul Nikah Duluan, tapi Ada Satu Syarat
Summary: Kakak beradik Al Ghazali, El Rumi, dan Dul Jaelani saat ini sama-sama sudah memiliki sosok tambatan hati. Sebagai kakak, Al Ghazali tidak masalah nantinya akan dilangkahi oleh adik-adiknya yang mau menikah lebih dulu. "Aku sih nggak apa-apa (dilangkahi menikah oleh El Rumi dan Dul Jaelani)," kata Al Ghazali saat ditemui di kawasan Kuningan, Jakarta Selatan, kemarin. Namun, putra sulung Ahmad Dhani dan Maia Estianty itu mempertanyakan kesiapan adik-adiknya soal pernikahan. " Hubungan asmara kakak beradik itu sudah mendapatkan restu dari orang tua. Bahkan Ahmad Dhani memiliki rencana untuk menikahkan anak-anaknya di waktu yang sama. Aku nggak tahu itu mitos Indonesia atau apa, tapi kalau kata ayah sih nggak apa-apa. Aku sih selama ada larangan itu aku percaya, tapi kalau nggak ya jalani aja," pungkasnya.
Cosine Similarity: 0.48306041955947876

--------------------------------------------------
Title: Cut Intan Nabila Minta Maaf 5 Tahun Tutupi KDRT yang Dilakukan Armor
Summary: Selebgram Cut Intan Nabila akhirnya bersuara lewat Instagram miliknya. Cut Intan Nabila mengucapkan terima kasih kepada semua pihak yang sudah membantu kasusnya. Ia meminta maaf karena selama lima tahun menutup diri mengenai hal ini. Maafkan jika selama 5 tahun ini saya selalu menutup diri atas KDRT yang saya alami dari keluarga dan sahabat-sahabat terdekat saya karena saya selalu bergelut dengan pikiran dan hati saya, bahwa dia bisa berubah," tulis Cut Intan Nabila dalam Instagram miliknya dilihat detikcom, Sabtu 17 Agustus 2024. "Kemudian saya juga mau berterima kasih kepada pihak Polres Bogor, yang telah mengawal kasus ini. Saya ingin meluruskan berita simpang siur di luar sana, terkait kasus saya. Cut Intan Nabila menaruh harapan dengan keputusannya tetap melanjutkan proses hukum atas KDRT yang dilakukan suami. "
Cosine Similarity: 0.7202541828155518

--------------------------------------------------
Title: Kondisi Angela Lee Sebulan Ditahan karena Kasus Tas Mewah
Summary: Selebgram Angela Lee ternyata sudah lebih dari sebulan ditahan polisi. Ibu satu anak itu disebut ditahan sejak 16 Juli lalu. Sudah lebih dari sebulan dia ditahan, sudah ada perpanjangan penahanan satu kali," ujar Anggiat kepada detikcom saat dihubungi, Senin 19 Agustus 2024. Anggiat Tobing lalu mengungkapkan kondisi Angela Lee setelah sebulan ditahan. Tapi ketika dia di tahanan dia down, shock juga, karena dia merasa tetap bertanggung jawab, hanya memang dia tidak punya kemampuan menyelesaikan utang-utangnya," tuturnya. Angela Lee dikatakan selalu memohon didoakan. Saya kristen, dia kristen, kita doa bersama. Saya minta ke dia berkomitmen agar dia selektif, menjadi orang yang baik," katanya. Ia berharap Francisca Indiarti bisa terketuk hatinya. Sekadar diketahui Angela Lee ditahan karena kasus dugaan penggelapan 15 tas mewah.
Cosine Similarity: 0.6157281994819641

--------------------------------------------------
Title: Rizwan Fadilah Jadi Gamers, Senang Ada Wadah Game Online Baru
Summary: Rizwan Fadilah yang dikenal sebagai artis sekaligus anak dari komedian Sule, menjelaskan kegemarannya dalam bermain game. Ia sangat menyukai game bahkan sering bermain dengan teman-temannya di sekolah. Termasuk kostum atau skin yang dibeli untuk membuat karakter gamenya semakin mengesankan. Rizwan mengaku senang karena ia memiliki wadah game baru. Ia merasa tidak layak bersanding dengan gamer lain yang dianggap lebih handal. " Saya udah minder duluan, kalau ada ajakan. Kami ingin komunitas game memiliki tempat berkumpul, bermain, bersaing, bertemu teman baru dan berbagi konten," kata Komisaris Playhera Indonesia sekaligus CEO E-motion Entertainment, Arnold Limasnax. Sheikh Sultan bin Khalifa bin Sultan bin Shakhbout Al Nahyan dari Abu Dhabi juga menyambut antusias peluncuran Playhera. Ia melihat adanya potensi besar di Indonesia. " Kita punya fokus untuk para gamer, yang mana movement-nya sudah mendunia.
Cosine Similarity: 0.5267322659492493

--------------------------------------------------
Title: Jawaban Altaf Vicko Dituduh KDRT dan Diceraikan Selebgram Shahnaz Anindya
Summary: Selebgram Shahnaz Anindya tengah menghadapi gejolak rumah tangga dengan presenter Altaf Vicko. Dia mengajukan gugatan cerai ke Pengadilan Agama Jakarta Pusat, Senin 19 Agustus 2024. Dugaan Kekerasan Dalam Rumah Tangga (KDRT) disebut sebagai alasan. "Faktanya, menikah Juni 2022, belum sebulan sudah pisah rumah," buka Vicko dalam pesan singkat yang dikirim pengacaranya, Jamaludin Fakaubun S.H., M.H. "4 Februari 2023 saya gugat di Pengadilan Agama Jakarta Selatan, namun tidak dapat diterima," tulisnya dalam fakta kedua. Sampai tahap banding, kasasi, hingga tahap Mahkamah Agung," ungkapnya di fakta ketiga. Dalam pesan singkat itu, Vicko juga menguraikan soal tuduhan KDRT yang dialamatkan kepadanya. Vicko mengaku mendapati beberapa barang yang mencurigakan milik sang istri. Salah satunya diketahui sebagai media pelet. " Saya baru tahu tabiat ini setelah menikah," ungkapnya. Humas Polres Metro Jakarta Selatan, AKP Nurma Dewi, membenarkan Vicko dilaporkan oleh Shahnaz atas dugaan KDRT. " Sudah kemarin diperiksa," kata AKP Nurma Dewi melalui pesan singkat kepada detikcom, Senin 19 Agustus. Gugatan cerai tersebut terdaftar dengan nomor register PA.JP-19082024ZHS. " Soal gugatan cerai ke PA Jakpus, saya belum terima surat apa-apa.
Cosine Similarity: 0.18542960286140442

--------------------------------------------------
Title: Reaksi Angger Dimas Lihat Ulang CCTV Meninggalnya Dante
Summary: Pengadilan Negeri Jakarta Timur kembali menggelar sidang lanjutan atas meninggalnya anak Angger Dimas dan Tamara Tyasmara, Raden Andante Khalif Pramudityo, dengan agenda mendengarkan keterangan saksi-saksi ahli. Dalam sidang ini, Jaksa Penuntut Umum (JPU) menghadirkan saksi ahli CCTV untuk melihat ulang tayangan di TKP kolam renang. Setelah selesai meihat tayangan ulang CCTV tersebut, Angger Dimas terlihat geram melihat perbuatan terdakwa Yudha Arfandi pada putranya "Mual sih itu bukan perbuatan manusia," kata Angger Dimas saat ditemui setelah sidang di Pengadilan Negeri Jakarta Timur, Jakarta Selatan, Senin 19 Agustus 2024. Iya ayah nangis, karena di kesaksian dijelaskan banyak ganggang di tubuh Dante karena banyak frekuensi penekanan dalam air, yang dipicu juga sama zat zat dalam air itu," tutur Angger Dimas. Setelah melihat tayangan ulang CCTV, disjoki berusia 36 tahun itu semakin yakin jika Yudha Arfandi akan dijatuhi hukuman dengan pasal pembunuhan berencana. "
Cosine Similarity: 0.4401281476020813

--------------------------------------------------
Title: Ke Mana Cut Intan Nabila Akan Membawa Rumah Tangganya Usai Alami KDRT?
Summary: Suami selebgram Cut Intan Nabila, Armor Toreador kini sudah ditahan dan ditetapkan sebagai tersangka atas kekerasan dalam rumah tangga (KDRT) oleh Polres Bogor. Jauh sebelum laporan ini, ibu tiga anak itu juga sempat ada niatan untuk melaporkan tindak KDRT suaminya ke polisi dan juga mengajukan gugatan cerai. Sebenarnya ada upaya untuk melapor, cuma memang gagal. Pernah juga udah dua kali ke pengadilan agama, cuma ya gagal juga," aku Cut Intan Nabila. Alasan sebelumnya tak jadi mempolisikan dan menggugat cerai, Intan Nabila berharap suami bisa berubah. " Ya memang mungkin, saya ingin berpikir, pelaku KDRT ini kan, dulu saya nggak sadar nih, apakah dia bisa berubah atau nggak. Cuma terakhir itu karena saya merasa kalau melakukan itu bukan cuma mengancam nyawa saya, tapi juga nyawa anak-anaknya, dan teman-temannya, jadi akhirnya saya memutuskan untuk melapor demi anak-anak saya juga," ujar Cut Intan Nabila. "
Cosine Similarity: 0.3530411720275879

--------------------------------------------------
Title: Pesan Menohok Ayu Ting Ting Untuk Netizen yang Cibir Bilqis Nyanyi SHEES
Summary: Ayu Ting Ting turun tangan membalas komentar julid netizen yang mencibir penampilan Bilqis Khumairah bernyanyi di televisi. Ayu merasa orang-orang seperti itu tak punya hati. Pedangdut berusia 32 tahun itu mewanti-wanti para pemilik akun bodong yang memberikan komentar julid. " Lo kalau mau julidin bisa sama orang dewasa aja. Tapi kalau anak kecil kayaknya dimana gitu hati nurani lo sebagai manusia," pesan Ayu Ting Ting. " Lah lo waktu seumuran anak gue paling nangis di pojokan, sambil ngedot. Gitu saja sih, ngeledek-ngeledekin aja," sambungnya. Bilqis mengetahui jadi sasaran hujatan di media sosial. Ayu Ting Ting mengingatkan seorang ibu rela melakukan apa saja demi melindungi dan membela anaknya. Wajar seorang ibu ngoceh bila ada yang merendahkan anak-anaknya. " Pokoknya ibu-ibu kasta tertinggi di dunia jangan pernah dilawan. Saya nggak pernah balas-balasin juga, tapi kan ini anak kecil.
Cosine Similarity: 0.3420409560203552

--------------------------------------------------
Title: Juliana Moechtar Terharu Suami Berjuang Jadi Komandan Upacara Pertama di IKN
Summary: Artis dan model Juliana Moechtar menjadi salah satu tamu undangan yang menghadiri perayaan HUT ke-79 RI pertama kalinya di Ibu Kota Nusantara. Kehadirannya juga mendampingi suami bertugas sebagai Komandan Upacara Detik-detik Proklamasi. Juliana Moechtar dalam unggahan Instagram pribadinya, mengucap syukur suami lancar menjalankan tugasnya. Finalis Puteri Indonesia 2010 dari Aceh itu hanya bisa membantu doa dan semangat kepada suami menjalani segala seleksinya. Atas kepercayaan Pimpinan masyallah allahuakbar darı mulai upacara sampai selesai hanya ada tangisan rasa haru yang luar biasa bangganya. Kolonel Infanteri Nur Wahyudi menjabat sebagai Komandan Satuan atau Dansat-81 Kopassus. Sebelumnya dia pernah menjabat sebagai Komandan Kodim (Dandim) 09603/Lebak Banten pada 2020. Dia menikah dengan Kolonel Inf Nur Wahyudi setelah menjanda empat tahun seusai Herman Seventeen meninggal dunia dalam bencana tsunami Banten pada 22 Desember 2018. Kolonel Inf Nur Wahyudi dan Juliana Moechtar menggelar ijab kabul pada Jumat 27 Mei 2022.
Cosine Similarity: 0.42258042097091675

--------------------------------------------------
Title: Azriel Hermansyah dan Sarah Menzel Mulai Mempersiapkan Pernikahan
Summary: Anak kedua musisi Anang Hermansyah, Azriel Hermansyah, sudah melamar kekasihnya, Sarah Menzel. Persiapan pernikahan mereka mulai dipersiapkan. Anang Hermansyah juga membenarkan persiapkan pernikahan putranya sedang dipersiapkan. " Lagi direncanakan," kata Anang Hermansyah saat ditemui di kawasan Radio Dalam, Jakarta Selatan, Jumat 16 Agustus 2024. Menyoal waktu pernikahan, Anang Hermansyah juga menjawab singkat. " Sebelumnya, Azriel Hermansyah sempat mengungkapkan alasan mengapa ia melamar Sarah Menzel. " Kan mau LDR, pas pacaran pun LDR, cuma ini LDR yang paling lama dan paling jauh.
Cosine Similarity: 0.9311206936836243

--------------------------------------------------
Title: Persaingan Atta Halilintar-Keanu Agl Lomba Kelereng Rebutkan Rp 10 Juta
Summary: Atta Halilintar dan Keanu Agl turut memeriahkan perayaan Hari Kemerdekaan dengan mengikuti perlombaan kelereng yang diadakan oleh Putra Siregar. Beruntung, pada putaran pertama, selebgram ini berhasil mengalahkan Atta Halilintar. "Menanglah, urusan kelereng mah gue," kata Keanu Agl di kawasan Lenteng Agung, Jakarta Selatan, Sabtu 17 Agustus 2024. Alhasil hadiah Rp 10 juta jatuh ke tangan pengusaha tersebut. Meskipun kalah, keduanya tetap merasa senang bisa merayakan Hari Kemerdekaan Indonesia dengan mengikuti lomba kelereng. Momen ini membawa kembali kenangan mereka ke masa kecil. Selamat hari 17 Agustus, untuk negara kita tercinta. Semoga kita semua selalu merdeka," tutup Atta Halilintar.
Cosine Similarity: 0.8689651489257812

--------------------------------------------------
Title: Cut Intan Nabila Ungkap Alasan 5 Tahun Tutupi Tindak KDRT Armor
Summary: Cut Intan Nabila untuk pertama kalinya muncul dan bicara prihal KDRT yang dialaminya. Mantan atlet anggar itu muncul di laman Instagram pribadinya yang terverifikasi. Maafkan jika selama 5 tahun ini saya selalu menutup diri atas KDRT yang saya alami dari keluarga dan sahabat-sahabat terdekat saya karena saya selalu bergelut dengan pikiran dan hati saya, bahwa dia bisa berubah," ungkap Cut Intan Nabila dilihat, Minggu 18 Agustus 2024. Di mana kasus ini masih terus berjalan sesuai prosedur hukum yang ada. Terkait isu diluar soal rumor adanya pencabutan LP dan penyelesaian secara musyawarah itu belum ada sampai sekarang. Jadi proses hukum tingkat penyidikan masih berjalan. Sampai sekarang juga masih belum ada (pengajuan restorative justice)" kata Iptu Desi Triana saat ditemui di Polres Bogor, Jumat 16 Juli 2024. Kabar Cut Intan Nabila bakal cabut laporan muncul setelah Kuasa hukum Armor, Irwansyah, menyampaikan permohonan maaf kepada netizen atas kegaduhan yang terjadi. Pada intinya keluarga tadi menyampaikan ke saya pemohonan maaf kepada netizen yang telah memberikan se-booming ini dan ucapan terima kasih atas perhatian dan atensinya. Alasan yang dipakai oleh pihak Armor adalah demi anak-anaknya. " Kebayang nggak sih anak Armor paling besar 4 tahun, ada tiga.
Cosine Similarity: 0.15937992930412292

--------------------------------------------------
Title: Tasya Kamila Tak Arahkan Arrasya Jadi Penyanyi, tapi Sadari Bakat Anak
Summary: Artis Tasya Kamila mengungkapkan putra pertamanya, Arrasya Wardhana Bachtiar, akan menjajal dunia tarik suara. Dia kan masih lima tahun, dulu aku start nyanyi umur enam hingga tujuh tahun. Dia cuma nyanyi beberapa line aja, dia senang banget pas sudah jadi part," tutur Tasya Kamila. Ibu dua anak itu memilih untuk memberikan kebebasan kepada anaknya dalam mengeksplor minat dan bakatnya sendiri. Ternyata Arrasya mempunyai bakat alami untuk menyanyi. Arrasya juga disebut Tasya Kamila, tahun ini berencana akan merilis lagu yang pernah dibawakan olehnya saat menjadi penyanyi cilik. " Ini salah satu cara aku agar dia bisa ada kesempatannya.
Cosine Similarity: 0.8913924694061279

--------------------------------------------------
Title: Ayu Ting Ting Ngegas Balas Komen Netizen: Nggak Bisa Diam Anak Kena Julid
Summary: Penyanyi Ayu Ting Ting membalas komentar netizen yang julid dengan penampilan Bilqis saat membawakan lagu Sheesh milik BabyMonster dalam sebuah acara penghargaan di televisi. Hal seperti ini memang jarang dilakukan oleh Ayu Ting Ting. Kalau saya sih mau dikatain apa juga, saya nggak pernah ini. Cuma pas saya lagi syuting, saya nggak lagi ngapa-ngapain. Akun bodong kali ya tepatnya, ya bocah-bocah, bocil-bocil yang mungkin kalau saya tangkep nangis, jerit kayaknya," ucap Ayu Ting Ting ditemui di Depok, Jawa Barat, kemarin. Ayu Ting Ting menyebut orang-orang seperti itu tak punya hati nurani. " Kita ada panasnya kan orang tua, manusiawi baca komen gitu. Maksudnya gini, anak kecil lu julidin, di mana sih hati lo? Lo kalau mau julidin bisa sama orang dewasa aja. Masih mending anak gue umur segitu udah bisa tampil. Gitu saja sih, ngeledek-ngeledekin aja," sambung Ayu Ting Ting sambil tertawa. Ayu Ting Ting yakin pasti semua ibu-ibu sepaham dengan dirinya. Ibu akan jadi garda terdepan menjaga dan membela anaknya. " Pokoknya ibu-ibu kasta tertinggi di dunia jangan pernah dilawan. salah satu balasan Ayu Ting Ting ke netizen julid yang viral.
Cosine Similarity: 0.16722047328948975

--------------------------------------------------
Title: Anji Tegaskan Tak Ada Perselingkuhan, Miris Juliette Angela Jadi Konten Tuduhan
Summary: Percerain Anji dan Wina Natalia dikaitkan dengan masalah rumah tangga rapper Sexy Goath dan Juliette Angela. Anji secara langsung membantah tuduhan perselingkuhan itu. " Ah itu ku sudah bilang udah setop karena simple saja, kalau kamu punya maksudnya apalagi kalau dikaitkan sama penyebabnya perceraian kami, sudah jelas bullshit," tegas Anji Manji ditemui di Studio Pagi-pagi Ambyar Trans TV, Jalan Kapten P Tendean, Jakarta Selatan, Senin 19 Agustus 2024. Penyanyi bernama lengkap Erdian Aji Prihartanto itu merasa sudah memenuhi permintaan Sexy Goath untuk memberikan klarifikasi. Anji menyayangkan kecurigaan Sexy Goath sampai membuka hal pribadi Juliette Angela seperti soal kepemilikan lingerie. Demi Allah aku nggak tahu lingerie biru itu apa, dipakai apa nggak, dibawa apa nggak, nggak tahu. Adanya tuduhan-tuduhan seperti itu membuat Anji merasa sangat mengganggu pekerjaannya. Karena proyek ini harusnya dirahasiakan gitu. Ini pekerjaan ada kontraknya, ketika ini dibicarakan terus, akhirnya nggak surprise lagi. Nanti tunggu sajalah proyeknya seperti apa," tutup Anji tersenyum.
Cosine Similarity: 0.16861896216869354

--------------------------------------------------
Title: Tamara Tyasmara Keluar Sidang, Tak Kuat Lihat Video CCTV Kematian Dante Diputar
Summary: Sidang kasus meninggalnya anak Angger Dimas dan Tamara Tyasmara, Dante kembali digelar di Pengadilan Negeri Jakarta Timur dengan agenda keterangan dari saksi ahli. CCTV juga diputar dalam sidang yang digelar tertutup kali ini. Sidang digelar tertutup sesuai perintah Hakim Ketua, Immanuel. "Memanggil Hery Priyanto untuk melakukan pemeriksaan ahli. Di luar sidang akan kita jaga (orangtua tidak ngomong)," lanjutnya. Sebelumnya Tamara Tyasmara, ibunda Dante, merasa tidak siap harus melihat video CCTV yang memperlihatkan detik demi detik, Yudha Arfandi membenamkan Dante. " Saya akan keluar ruang sidang kalau rekaman CCTV itu diputar lagi. Cukup sekali saja melihat rekaman CCTV, yang pertama aja nggak kuat, apalagi ini," kata Tamara Tyasmara.
Cosine Similarity: 0.7674134969711304

--------------------------------------------------
Title: Istri Selalu Blak-blakan Cemburu, Boy Hamzah Lebih Posesif
Summary: Istri Boy Hamzah, Rina Amalia, selalu terbuka dengan suami apabila merasa cemburu. Kalau perempuannya terlihat normal-normal dia slow aja. Rina menjelaskan dirinya selalu mewanti-wanti Boy Hamzah untuk tidak melakukan hal berlebihan dengan lawan main apalagi di luar naskah. Ini merupakan cara Rina mengingatkan suaminya untuk bisa jaga diri. Sebagai istri, Rina tak masalah apabila lawan main Boy Hamzah punya sikap yang baik. Kalau mungkin kadang semi-semi cinlok gitu adalah, kan sering terjadi seperti itu. Makannya aku negur suami aku buat nggak dekat-dekat, tapi dia bilang tenang aja. Tapi aku tetap saja nyinyir, 'Hati-hati ya,'" kata Rina. " Boy mengaku memperlakukan istri seperti layaknya permata yang sangat dijaga. " Rina cemburu, tapi saya yang posesif karena bagi kita perempuan yang sudah kita nikahi itu sebuah permata. Permata yang sebaik-baiknya kan bukan yang dipajang, tapi yang disimpan di boksnya dan dibungkus yang terbaik.
Cosine Similarity: 0.32050973176956177

--------------------------------------------------
Title: Band Om Om Kupas Keresahan Bapak-bapak Lewat Single Hadeuh

In [ ]:
# List to store the results
results = []

# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # Mendapatkan judul yang sesuai dengan summary berdasarkan index
    title = data.loc[data['summary'] == index, 'title'].iloc[0]
    similarity_value = cosine_sim_df.loc[index, title]  # Mengakses nilai similarity

    # Menyimpan pasangan dan nilai similarity ke dalam list
    results.append([title, index, similarity_value])

# Membuat DataFrame untuk hasilnya
similarity_df = pd.DataFrame(results, columns=['Title', 'Summary', 'Cosine Similarity'])

In [ ]:
similarity_df.head()

,Title,Summary,Cosine Similarity
0,Pentingnya Hak Cipta dan Perlakuan Maksimal un...,Perseteruan Ahmad Dhani dan Once beberapa wakt...,0.420054
1,Okan Kornelius Pakai Kemeja Pink dan Dapat Kej...,Artis Okan Kornelius saat ini diketahui tengah...,0.547018
2,Ayu Ting Ting Putus dengan Muhammad Fardhana,Pedangdut Ayu Ting Ting rupanya sudah tak menj...,0.364207
3,Dion Wiyoko Ajak Anak Muda Tak Takut Berkeringat,Siapa sangka aktor Dion Wiyoko dulunya jago ol...,0.911709
4,Denny Sumargo Ungkap Kondisi Janin di Kandunga...,"Aktor dan mantan atlet basket, Denny Sumargo b...",0.505139

## Save Similarity

In [ ]:
# Menyimpan DataFrame ke file CSV di lokasi yang ditentukan
similarity_df.to_csv('/content/drive/MyDrive/File/CODES/Similarity/2_Similarity_Detik_Hot_Base1/similarity_detik_hot_base1.csv', index=False)