# Install Library

In [1]:
!pip install transformers
!pip install datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Collecting datasets
  Downloading datasets-3.3.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.12)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.3.1-py3-none-any.whl (484 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.9/484.9 kB 8.3 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 5.9 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 5.9 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 12.0 MB/s eta 0:00:00
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.3.1 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Import Library

In [3]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer
from google.colab import drive

# Connect to Drive

In [4]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
# Path folder tempat file CSV berada
folder_path = "/content/drive/MyDrive/File/CODES/Summarize/5_Summary_Suara_Nasional_50_Base1/Sum_Suara_Nasional_50_Base1"

# Mengambil semua file dengan ekstensi .csv dalam folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith(".csv")]

# Membaca dan menggabungkan semua file
dataframes = []
for file_name in csv_files:
    file_path = os.path.join(folder_path, file_name)
    df = pd.read_csv(file_path)
    dataframes.append(df)

# Menggabungkan semua DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

In [6]:
# Menyimpan hasil penggabungan ke file baru
output_path = os.path.join(folder_path, "/content/drive/MyDrive/File/CODES/Similarity/5_Similarity_Suara_Nasional_Base1/suara_nas_sum_50_base1_concat.csv")
combined_df.to_csv(output_path, index=False)

In [7]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6102 entries, 0 to 6101
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         6102 non-null   object
 1   category      6102 non-null   object
 2   publish_date  6102 non-null   object
 3   author        6102 non-null   object
 4   article_url   6102 non-null   object
 5   content       6102 non-null   object
 6   summary       6102 non-null   object
dtypes: object(7)
memory usage: 333.8+ KB

In [8]:
combined_df.head()

,title,category,publish_date,author,article_url,content,summary
0,Jokowi Beberkan 'Love-Hate' dengan Surya Paloh...,Nasional,2024-08-26,Chandra Iswinarno,https://www.suara.com/news/2024/08/26/070000/j...,Presiden Joko Widodo atau Jokowi membeberkan b...,Presiden Joko Widodo atau Jokowi membeberkan b...
1,"Ucap Terima Kasih, Surya Paloh Akui Belajar da...",Nasional,2024-08-25,Agung Sandy Lesmana,https://www.suara.com/news/2024/08/25/224500/u...,Ketua Umum Partai NasDem Surya Paloh mengaku b...,Ketua Umum Partai NasDem Surya Paloh mengaku b...
2,"Di Depan Jokowi, Surya Paloh: Bukan Cuma Masal...",Nasional,2024-08-25,Agung Sandy Lesmana,https://www.suara.com/news/2024/08/25/214434/d...,Ketua Umum Partai NasDem Surya Paloh menegaska...,Ketua Umum Partai NasDem Surya Paloh menegaska...
3,"Jokowi Muncul di Kongres III NasDem Malam Ini,...",Nasional,2024-08-25,Agung Sandy Lesmana,https://www.suara.com/news/2024/08/25/194135/j...,Presiden Joko Widodo alias Jokowi menghadiri K...,Presiden Joko Widodo alias Jokowi menghadiri K...
4,"Sebut Pemilu 2024 Paling Brutal, Cak Imin Usul...",Nasional,2024-08-25,Bangun Santoso,https://www.suara.com/news/2024/08/25/184735/s...,Ketua Umum Dewan Pimpinan Pusat Partai Kebangk...,Ketua Umum Dewan Pimpinan Pusat Partai Kebangk...

In [9]:
nan_summary = combined_df[combined_df['summary'].isna()]


nan_summary

Empty DataFrame
Columns: [title, category, publish_date, author, article_url, content, summary]
Index: []

In [10]:
combined_df=combined_df.dropna()

# Duplicate

In [11]:
data = combined_df.copy()

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6102 entries, 0 to 6101
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         6102 non-null   object
 1   category      6102 non-null   object
 2   publish_date  6102 non-null   object
 3   author        6102 non-null   object
 4   article_url   6102 non-null   object
 5   content       6102 non-null   object
 6   summary       6102 non-null   object
dtypes: object(7)
memory usage: 333.8+ KB

# Tokenize

Mencoba kode lain agar tokenize lebih mudah di pahami

# Word Embedding

In [13]:
from transformers import AutoTokenizer, AutoModel
import torch

# Memuat IndoBERT dan tokenizer
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1", use_fast=True)
model = AutoModel.from_pretrained("indobenchmark/indobert-base-p1")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

In [14]:
# Fungsi untuk mendapatkan embedding dari IndoBERT
def get_embeddings(input_ids):
    with torch.no_grad():
        outputs = model(input_ids=input_ids)
    # Mengambil hidden states dari layer terakhir dan rata-rata embeddingsnya
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings

# Fungsi untuk mengonversi tokenized data ke dalam bentuk input_ids dan mendapatkan embedding
def get_input_ids_and_embeddings(data_column):
    input_ids_list = []
    embeddings_list = []

    for text in data_column:
        # Tokenisasi
        tokens = tokenizer(text, padding='max_length', max_length=256, truncation=True, return_tensors="pt")
        input_ids = tokens['input_ids']  # Ambil input_ids
        input_ids_list.append(input_ids)

        # Mendapatkan embeddings
        embedding = get_embeddings(input_ids)
        embeddings_list.append(embedding)

    return input_ids_list, embeddings_list

# Dapatkan input_ids dan embeddings untuk title dan summary
title_input_ids, title_embeddings = get_input_ids_and_embeddings(data['title'])
summary_input_ids, summary_embeddings = get_input_ids_and_embeddings(data['summary'])

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

## Mengubah embeddings menjadi array numpy

In [15]:
# Mengubah embeddings menjadi array numpy agar bisa disimpan dalam DataFrame
title_embeddings_array = np.vstack([embedding.numpy() for embedding in title_embeddings])
summary_embeddings_array = np.vstack([embedding.numpy() for embedding in summary_embeddings])

# Membuat DataFrame baru dengan embeddings numerik
data_embeddings = pd.DataFrame({
    'title_embeddings': list(title_embeddings_array),
    'summary_embeddings': list(summary_embeddings_array)
})

# Cosine Similarity

In [16]:
# hitung cosine similarity pada matrix berita
cosine_sim = cosine_similarity(title_embeddings_array, summary_embeddings_array)
print(cosine_sim)

[[0.87954295 0.95228547 0.40579575 ... 0.903032   0.2260749  0.13818681]
 [0.8706143  0.94533837 0.4029524  ... 0.89482474 0.22230548 0.13384908]
 [0.87885    0.9517845  0.40821669 ... 0.9032042  0.22613734 0.13858905]
 ...
 [0.87099546 0.94564795 0.40239638 ... 0.89665294 0.22158778 0.13032664]
 [0.87574697 0.9515747  0.40250623 ... 0.9023708  0.2237569  0.13417077]
 [0.8734868  0.94632447 0.4063745  ... 0.89720714 0.2249633  0.13594346]]

In [17]:
# membuat dataframe dari varible cosine similarity dengan baris dan kolom title
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['summary'], columns=data['title'])

print(cosine_sim_df.shape)

(6102, 6102)

## Check Similarity Result

In [18]:
# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # The index is a summary, and you need to find the corresponding title
    # to access the similarity value. However, since you have both summaries
    # and titles as indices, you can access the similarity directly using
    # the index and the corresponding title from the 'data' DataFrame.

    title = data.loc[data['summary'] == index, 'title'].iloc[0] # Get the title for the current summary
    similarity_value = cosine_sim_df.loc[index, title]  # Access the similarity using both summary and title

    print(f"Title: {title}")
    print(f"Summary: {index}")
    print(f"Cosine Similarity: {similarity_value}\n")
    print("-" * 50)  # Pemisah antar pasangan

Streaming output truncated to the last 5000 lines.
Cosine Similarity: 0.9643455743789673

--------------------------------------------------
Title: Ngaku Cewek Tulen, Noe Row Mengungkap Alasannya Bergaya Seperti Cowok Ganteng
Summary: Youtuber Indonesia, Noe Row adalah seorang gadis yang tomboy. Tak heran ia selalu dikira cowok ganteng. Padahal ia mengaku perempuan tulen walaupun bergaya rambut pendek dan kacamata bulat. Suaranya yang agak berat, membuatnya juga disangka laki-laki. Padahal Youtuber yang memiliki 1,53 juta subscriber ini memiliki nama asli Nur Firza Hairani. Gadis kelahiran 25 November 1996 asal Medan ini sebelumnya kuliah di Aceh lalu pindah ke salah satu Universitas di Jakarta. Tak hanya itu Noe juga kerap membagikan momen saat bersama pacarnya, bernama Ido. Karena saya suka dengan hal yang berbau simpel," tegasnya. Di luar itu, dalam satu tahun terakhir ini, Noe Row juga disibukkan dengan usaha clothing atau apparel yang digelutinya.
Cosine Similarity: 0.7430610060691833

--------------------------------------------------
Title: KPK Panggil Anak AGK Lagi sebagai Saksi Kasus TPPU
Summary: Komisi Pemberantasan Korupsi (KPK) menjadwalkan pemeriksaan terhadap anak mantan Gubernur Maluku Utara Abdul Gani Kasuba (AGK), Muhammad Thariq Kasuba, pada hari ini, Kamis 5 September 2024. Hari ini Kamis (5/9), KPK menjadwalkan pemeriksaan saksi dugaan TPK/TPPU dengan Tersangka AGK," kata Juru Bicara KPK Tessa Mahardhika, Kamis 5 September 2024. Namun, belum diketahui materi apa yang akan didalami penyidik dari keterangan yang bersangkutan. Selain itu, Abdul Gani Kasuba juga diduga menyamarkan hasil penerimaan suap dan gratifikasi ke sejumlah aset bernilai ekonomis yang kasusnya sudah berproses di Pengadilan Tipikor Ternate. Dalam pengembangan perkara yang menjerat AGK, KPK kembali menetapkan dua orang tersangka baru yaitu mantan Ketua DPD Partai Gerindra Malut Muhaimin Syarif dan Kepala Dinas Pendidikan dan Kebudayaan Pemprov Malut Imran Jakub.
Cosine Similarity: 0.5614807605743408

--------------------------------------------------
Title: Presiden Jokowi Dijadwalkan Buka MTQ Nasional XXX di Kaltim, Ditutup Wapres Maruf Amin
Summary: Perhelatan Musabaqah Tilawatil Quran atau MTQ Nasional XXX 2024 akan dibuka langsung oleh Presiden Joko Widodo (Jokowi). Acara akbar ini bakal diselenggarakan di Kompleks Global Kadri Oneing, Sempaja, Samarinda, Kalimantan Timur, pada 8 September 2024, pukul 19.00 WIB. Rencananya, Presiden Jokowi akan didampingi sejumlah menteri dan duta besar negara-negara sahabat. Presiden Jokowi sangat mengapresiasi dan memberikan dukungan penuh kepada panitia penyelenggara, pemerintah provinsi, bersama Lembaga Pengembangan Tilawatil Quran (LPTQ) terkait dan juga Kementerian Agama untuk melakukan langkah pelayanan yang baik," kata Penjabat (Pj) Gubernur Kalimantan Timur Akmal Malik ditulis Kamis 5 September 2024. Konsep penyelenggaraan full digital ini dijelaskan oleh Direktur Penerangan Agama Islam Kemenag Ahmad Zayadi, ada hal terasa istimewa yakni peningkatan kualitas dari sisi penyelenggaraan MTQ Nasional 2024. Caranya dengan pendekatan digital, salah satunya melalui aplikasi pendaftaran e-MTQ berbasis digital. " Aplikasi e-MTQ ini digunakan untuk proses pendaftaran dan verifikasi peserta. Dengan sistem tersebut, Kemenag ingin memastikan data peserta terverifikasi secara akurat dan valid," ujarnya. Dewan Hakim tidak boleh dipengaruhi, dia harus benar-benar merdeka untuk bisa menetapkan mana yang terbaik. PJ Gubernul katim, Akmal menjelaskan bahwa dengan konfigurasi tulisan Allah dan Muhammad itu yang belum ada, insya Allah itu akan menjadikan perhelatan MTQ 2024 terasa lebih berkah karena dengan jumlah dronenya mencapai 500 500 unit akan ada konfigurasi lafadz Allah SWT dan Muhammad SAW di udara Propinsi Kalimantan Timur. Dengan aplikasi ini peserta dan masyarakat umum bisa langsung melihat skor yang diperoleh secara real time. Begitu peserta selesai mengikuti lomba, skor yang diperoleh otomatis terinput. Aplikasi ini dikembangkan sebagai alat pengacak soal dan bahan bacaan (maqro) agar bisa dilakukan secara lebih transparan, akurat dan meminimalkan potensi kesalahan atau manipulasi soal. " Adanya aplikasi akan menghindari spekulasi. Ini akan menuntut peserta untuk memiliki kapasitas yang maksimal. Mereka akan tahu soal saat mereka akan mengambil undian, sangat rahasia," tuturnya. Tema ini diusung untuk mencerminkan semangat dalam menjadikan Alquran sebagai landasan moral dan spiritual bangsa, terutama di era globalisasi. Mereka berasal dari 35 provinsi di Indonesia.
Cosine Similarity: 0.17742592096328735

--------------------------------------------------
Title: Sedang Naik Daun, Noe Row Yang Kerap Disangka Cowok Ternyata Dua Kali Pindah Kuliah
Summary: Youtuber Indonesia, Noe Row kini sedang banyak dibicarakan. Beberapa tahun belakangan ini pamor youtuber satu ini memang sedang naik daun. Bahkan orang yang melihatnya mungkin tak menyadari Noe adalah seorang perempuan. Youtuber yang memiliki 1,53 juta subscriber ini memiliki nama asli Nur Firza Hairani. Akhirnya ia terpikir untuk mengembangkan hobinya dan memulai mencari pengetahuan tentang mengedit konten video di YouTube. Awalnya ia kerap membuatkan video untuk teman-temannya. Dari video yang dibuatnya awalanya tak banyak yang menonton videonya tersebut. Namun ia tak putus asa dan terus bersemangat. Mulai dari QnA, prank, giveaway, membandingkan karekter dan video aktivitasnya sehari-hari. Tak hanya itu Noe juga kerap membagikan momen saat bersama pacarnya, bernama Ido.
Cosine Similarity: 0.7358183264732361

--------------------------------------------------
Title: Pembalap Zahir Ali Kembali Dipanggil KPK Terkait Kasus Dugaan Korupsi Lahan Rorotan
Summary: Komisi Pemberantasan Korupsi (KPK) kembali memeriksa pengusaha properti Zahir Ali (ZA) pada Kamis 5 September 2024 terkait kasus dugaan korupsi pengadaan lahan di kawasan Rorotan, Jakarta Utara oleh BUMD Sarana Jaya (SJ). Pemeriksaan dilakukan di Gedung KPK Merah Putih atas nama ZA, Direktur Utama PT Citratama Inti Persada," kata Tessa kepada wartawan, Kamis 5 September 2024.Sebelumnya, Zahir sudah pernah diperiksa KPK terkait kasus ini. Jadi, kami ingin mendapatkan informasi seperti apa,” kata Asep kepada wartawan, Rabu 26 Juni 2024. Jadi, dipanggil dia tersebut ya karena alasan-alasan yang dimaksud,” kata Asep. Sekadar informasi, KPK sudah mengumumkan pencegahan ke luar negeri terhadap 10 orang. Pencegahan ini guna mendukung proses penyidikan kasus tersebut. Pencegahan diajukan ke Ditjen Imigrasi Kemenkumham pada Rabu, 12 Juni 2024 dan berlaku untuk enam bulan ke depan.
Cosine Similarity: 0.5670951008796692

--------------------------------------------------
Title: Cak Lontong Jadi Ketua Timses Pramono-Rano Karno di Pilkada Jakarta 2024, Ini Daftar Lengkapnya
Summary: Pasangan Calon Gubernur dan Calon Wakil Gubernur Jakarta, Pramono Anung dan Rano Karno, akhirnya merilis tim pemenangan di Pilkada Jakarta 2024. Ketua tim pemenangan paslon yang diusung oleh PDI Perjuangan ini dipimpin langsung oleh Lies Hartono alias Cak Lontong. Taufik Damas, Witaryono, Soni Harsono Ketua: Cak Lontong "Lies Hartono" Ketua Harian: Prasetio Edi Marsudi Wakil Ketua: Elfonda "Once" Mekel (DPR RI Dapil DKI), Putra Nababan (DPR RI Dapil DKI), Maudy Koesnaedy Darmadi Durianto (DPR RI Dapil DKI), Peneran Sarah di sinetron Doel Cornelia Agatha Sekretaris: Ario BimoWakil Sekretaris: Ima Mahdiah (DPRD DKJ), Ilham Wiratmadja, Ichsan Sofyan, Mangatta Toding Allo, Beno Muhamad Ibnu.
Cosine Similarity: 0.5784833431243896

--------------------------------------------------
Title: Puluhan Transpuan Bakal Menyambut Paus Fransiskus di GBK
Summary: Komunitas transpuan bakal menyambut kunjungan Pimpinan Gereja Katolik Dunia Paus Fransiskus di Gelora Bung Karno (GBK) Senayan, Jakarta, Kamis 5 September 2024 siang. Ada sekitar 50-an transpuan yang akan ikut menyambut kedatangan Paus di GBK. " Sementara Indonesia akan menjadi negara paling lama yang dikunjungi Paus dalam perjalanan ini. Kemudian, pada 5 September 2024, Paus Fransiskus dijadwalkan menghadiri pertemuan antaragama di Masjid Istiqlal, Jakarta, dilanjutkan pertemuan dengan penerima manfaat organisasi amal di Kantor Konferensi Waligereja Indonesia (KWI).Terakhir, ia akan memimpin misa akbar di Stadion Gelora Bung Karno (GBK). Rencananya kegiatan ini akan dihadiri sekitar 84 ribu jemaat katolik dari seluruh wilayah di Indonesia. Setelah agenda di Indonesia kelar, Paus Fransiskus akan melanjutkan perjalanan dari Jakarta menuju Papua Nugini pada tanggal 6 September. Ia akan berangkat dari Ibu Kota menuju Port Moresby sekitar pukul 09.45 WIB melalui Bandara Internasional Soekarno-Hatta.
Cosine Similarity: 0.39558112621307373

--------------------------------------------------
Title: SBY Sarankan Prabowo Pecah KLHK: Agar Efektif Atasi Perubahan Iklim
Summary: Mantan Presiden RI Susilo Bambang Yudhoyono (SBY) menyarankan kepada presiden terpilih Prabowo Subianto agar memisah Kementerian Lingkungan Hidup dan Kementerian Kehutanan (KLHK) menjadi dua kementerian yang berdiri sendiri, agar efektif dalam mengatasi perubahan iklim.. Di sela-sela acara Bloomberg CEO Forum Gala Dinner di Jakarta, Rabu 4 September 2024, SBY menilai pemisahan ini penting agar kementerian tersebut dapat lebih fokus pada tugasnya dalam menghadapi isu-isu perubahan iklim di tingkat global. " Saya telah berbicara dengan Presiden Prabowo dan saya mengusulkan kepadanya agar Kementerian Lingkungan Hidup didirikan kembali menjadi kementerian yang berdiri sendiri. Sekarang Kementerian Lingkungan Hidup menjadi bagian dari Kementerian Kehutanan (KLHK). Dalam sesi gelar wicara itu, SBY menekankan pentingnya kolaborasi semua pihak dalam mengatasi perubahan iklim. Ke depan, Pemerintah perlu melibatkan sektor swasta, ilmuwan, pakar lingkungan, hingga masyarakat luas. Selain isu lingkungan, SBY juga memberikan saran kepada Pemerintahan selanjutnya untuk lebih fokus pada pengembangan infrastruktur di bidang ekonomi lainnya, seperti pembangkit tenaga listrik, bandara, hingga jaringan kereta api. Jadi, infrastruktur itu sangat penting, tetapi membangun sumber daya manusia juga penting. Kita harus menggabungkan kedua hal tersebut secara berurutan, dan ekonomi akan terus tumbuh lebih tinggi dan lebih kuat," jelas SBY. (
Cosine Similarity: 0.12568239867687225

--------------------------------------------------
Title: Jaksa KPK Bacakan Tuntutan Terdakwa Hakim Agung Nonaktif Gazalba Saleh Hari Ini
Summary: Jaksa dari Komisi Pemerantasan Korupsi (KPK) akan membacakan tuntutan terhadap terdakwa Hakim Agung Nonaktif Gazalba Saleh, Kamis 5 September 2024 hari ini. Iya benar, sesuai agenda persidangan hari ini dijadwalkan pembacaan tuntutan pidana atas terdakwa Gazalba Saleh, dan persidangan diagendakan jam 10 pagi," kata Jaksa KPK Wawan Yunarwanto kepada wartawan, Kamis 5 September 2024. Dia diduga menerima uang itu terkait perkara kasasi Nomor 3679 K/PID.SUS-LH/2022 di Mahkamah Agung. Dalam dakwaan jaksa, Gazalba juga disebut menerima Rp 37 miliar saat menangani peninjauan kembali yang diajukan oleh Jaffar Abdul Gaffar pada 2020. Selain itu, dia juga disebut mendapatkan penerimaan lain, yakni SGD 1.128.000, USD 181.100 dan Rp 9,4 miliar pada 2020 hingga 2022.
Cosine Similarity: 0.6340250968933105

--------------------------------------------------
Title: KPAI Beberkan Modus Penculikan Anak Melalui Facebook: Apa yang Harus Waspadai?
Summary: Selama Tahun 2023, Komisi Perlindungan Anak Indonesia (KPAI) melaporkan adanya 59 kasus penculikan dan perdagangan anak. Modus operandi para pelaku sering kali mencakup pembentukan yayasan palsu yang berfungsi sebagai kedok untuk aktivitas ilegal mereka. Mereka memanfaatkan kelemahan dan kerentanan kelompok tertentu, seperti ibu hamil yang ditinggal oleh pasangan, perempuan yang hamil di luar nikah, dan pekerja migran yang pulang dalam kondisi hamil serta menghadapi kekerasan seksual dari majikan. " Pelaku memanfaatkan kondisi mereka dengan menawarkan solusi palsu melalui iklan di media sosial," ungkap Ketua KPAI Ai Maryati Solihah seperti dilansir Antara, Rabu 4 September 2024.Lantaran itu, Ai Maryati Solihah menggandeng kepolisian dan Kementerian Komunikasi dan Informatika (Kemenkominfo) untuk mengatasi sindikat perdagangan manusia yang semakin canggih. KPAI terus bekerja sama dengan Siber Polri dan Kemenkominfo untuk melacak dan menutup jaringan-jaringan ilegal ini. Berdasarkan laporan masyarakat tentang aktivitas mencurigakan di Beji, Kota Depok, Unit PPA Satreskrim Polres Metro Depok berhasil mengungkap dan menangkap delapan tersangka. Sindikat ini menggunakan Facebook untuk mencari ibu yang ingin menjual bayinya dengan iming-iming uang hingga Rp15 juta per bayi. Kami menemukan dua bayi yang akan dijual, satu bayi laki-laki dan satu bayi perempuan. Rencananya, bayi-bayi ini akan dibawa ke Bali untuk dijual lebih lanjut," katanya. Kasus ini merupakan pengingat pentingnya kewaspadaan dan upaya kolektif dalam melawan praktik penculikan dan perdagangan anak.
Cosine Similarity: 0.13913887739181519

--------------------------------------------------
Title: Sudah Diteken Menkumham, Cak Imin Punya 6 Wakil, Maruf Amin Jadi Ketua Dewan Syura PKB
Summary: Partai Kebangkitan Bangsa (PKB) membeberkan nama pengurus partai yang baru untuk periode 2024-2029. Hal itu disebut sudah ditandatangani oleh Kemenkumham dan tinggal dilengkapi sedikit. Namanya nanti diumumkan dalam waktu yang tepat, juga untuk posisi deputi dan sekretaris eksekutif," kata Bambang kepada wartawan, Rabu 4 September 2024.Adapun ada sejumlah perubahan kepengurusan dari periode sebelumnya. Wakil ketua Umum: - Ketua bidang & sekretaris bidang: masing-masing 21 orang- Ketua Bidang Pendidikan dan Pesantren: Syaiful Huda- Sekretaris Jendral: Hasanudin Wahid- Wakil Sekjen: 4 orang- Bendahara Umum: Bambang Susanto- Wakil Bendahara Umum: 5 orang Sudah Diteken Sebelumnya, Menteri Hukum dan HAM (Mekumham) Supratman Andi Agtas mengaku sudah menandatangani Surat Keputusan (SK) hasil Muktamar PKB di Bali dengan Muhaimin Iskandar alias Cak Imin sebagai ketua umum partai. Kalau tidak salah saya sudah tanda tangani. Ya karena yang mengajukan kan seperti itu," ujarnya. Saat ditanya soal adanya wacana fungsionaris PKB yang akan menggelar Muktamar tandingan, Supratman enggan berandai-andai. " Saya tidak mau berandai-andai, saya melayani sesuai dengan yang memang sedang mengajukan permohonan yang dilakukan penelitian," katanya. Ia menegaskan, tidak mau mengomentari hal yang belum ada dan diterima pihaknya. " Yang belum ada ngapain saya komentarin," pungkasnya.
Cosine Similarity: 0.1550179123878479

--------------------------------------------------
Title: Turun jadi 21,5 Persen, Indonesia Tekan Angka Stunting 9 persen dalam Lima Tahun
Summary: Menteri Koordinator Bidang Pembangunan Manusia dan Kebudayaan (Menko PMK), Muhadjir Effendy, mengungkapkan keberhasilan Indonesia dalam mengurangi angka stunting atau pertumbuhan terhambat pada balita sebesar 9,63 persen dalam periode lima tahun (2018-2023). Muhadjir menyebut bahwa prevalensi stunting di Indonesia turun dari 30,8 persen pada 2018 menjadi 21,5 persen pada 2023, menurut Survei Kesehatan Indonesia (SKI). Hal ini disampaikan dalam Rapat Koordinasi Nasional (Rakornas) Percepatan Penurunan Stunting yang diadakan di Jakarta, Rabu 4 September 2024. "Menurut data SKI 2023, angka stunting adalah 21,5 persen. Berdasarkan standar Organisasi Kesehatan Dunia (WHO), prevalensi stunting yang ideal adalah 20 persen. Evaluasi ini dilakukan untuk memastikan data yang lebih akurat tentang balita dan ibu hamil, sehingga intervensi dapat tepat sasaran. Muhadjir mengapresiasi kerja keras semua pihak, baik dari pemerintah daerah maupun tenaga relawan, dalam upaya maksimal penurunan stunting di Indonesia.
Cosine Similarity: 0.20555861294269562

--------------------------------------------------
Title: Soal Polemik Running Text Azan Magrib, Jazuli PKS Cecar Menkominfo Budi Arie: Saya Yakin Paus Tak Minta Begitu
Summary: Anggota Komisi I DPR RI fraksi PKS, Jazuli Juwaini, meminta pemerintah tak perlu berlebihan soal adanya imbauan terkait siaran azan diganti running text saat penayangan misa Paus Fransiskus di Televisi. Awalnya, Jazuli curhat soal dirinya mendapatkan banyak panggilan telepon lantaran menanyakan soal adanya imbauan azan diganti running text. " Dari telepon yang masuk ke saya, tokoh dan ormas, itu menyayangkan ada surat dari Dirjen yang mengganti azan degnan running text," kata Jazuli. Sebenarnya kan jadi bagus, misanya berjalan ditayangkan dengan televisi, kemudian pas azan magrib, paling hanya dua menit, kasih azan magrib, abis itu terus-in lagi. Ia justru menyampaikan, jika Paus Fransiskus sendiri tak akan mau adanya kebijakan soal penggantian tayangan azan menjadi running text. " Saya yakin Paus-nya pun tidak minta begitu. Jadi kita tidak perlu berlebihan," katanya. "Jadi saya berharap mari kokohkan nilai Pancasila.
Cosine Similarity: 0.5331502556800842

--------------------------------------------------
Title: Tiba-tiba Batal Panggil Kaesang soal Kasus Pesawat Jet, KPK: Sama Sekali Tak Ada Tekanan
Summary: Komisi Pemberantasan Korupsi (KPK) membantah adanya tekanan dari pihak mana pun terkait batalnya putra bungsu Presiden Joko Widodo, Kaesang Pangarep diundang Direktorat Gratifikasi KPK untuk mengklarifikasi dugaan gratifikasi pada penggunaan pesawat jet pribadi. Sama sekali tidak ada tekanan," kata Tessa di Gedung Merag Putih KPK, Jakarta Selatan, Rabu 4 September 2024. " Fokusnya tidak ke sana lagi," kata Tessa. Menurut Tessa, Direktorat Gratifikasi saat ini membantu Direktorat PLPM dalam rangka mengumpulkan bukti terkait dugaan gratifikasi tersebut. " Terkait isu tersebut Direktorat Gratifikasi tidak berhenti. Mereka tetap kumpulkan data-data untuk di-supply ke temen-temen Direktorat PLPM. Yang jelas pelapor pasti diklarifikasi atau pihak-pihak terkait mungkin yang diduga ada kaitannya terhadap laporan tersebut, untuk kepastiannya tentu kita akan tunggu sama," tutur Tessa. Klarifikasi soal Pesawat Jet Sebelumnya, Wakil Ketua KPK Alexander Marwata mengatakan pihaknya akan menyampaikan surat undangan kepada Kaesang dalam menanggapi permintaan klarifikasi terhadap putra bungsu Presiden Jokowi perihal dugaan penerimaan gratifikasi tentang pesawat jet pribadi yang digunakan untuk bepergian ke Amerika Serikat. " Dia juga menjelaskan informasi dari masyarakat merupakan hal yang lumrah dan perlu untuk ditindaklanjuti lembaga antirasuah. " Kalau ada informasi dari masyarakat, kami biasa mengundang. Jadi, kalau terkait dengan laporan-laporan, penerimaan-penerimaan lewat Direktorat Gratifikasi dan Kedeputian Pencegahan, kami mengundang," ujar Alex. Namun, Alex menegaskan, hal tersebut belum tentu membatalkan permintaan klarifikasi dari Lembaga Antirasuah. " Kami si berharap ketika melakukan klarifikasi atau apapun untuk disampaikan bukti dong, misalnya, 'saya bayar sendiri lho ini bukti transfernya'. Diketahui, jet pribadi yang ditumpangi Kaesang dan Erina santer dibahas pengguna media sosial.
Cosine Similarity: 0.22022050619125366

--------------------------------------------------
Title: Haru sampai Berpelukan, Tangis Para Jemaat Pecah saat Lihat Wajah Paus Fransiskus di Katedral: Momen Bersejarah!

In [19]:
# List to store the results
results = []

# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # Mendapatkan judul yang sesuai dengan summary berdasarkan index
    title = data.loc[data['summary'] == index, 'title'].iloc[0]
    similarity_value = cosine_sim_df.loc[index, title]  # Mengakses nilai similarity

    # Menyimpan pasangan dan nilai similarity ke dalam list
    results.append([title, index, similarity_value])

# Membuat DataFrame untuk hasilnya
similarity_df = pd.DataFrame(results, columns=['Title', 'Summary', 'Cosine Similarity'])

In [20]:
similarity_df.head()

,Title,Summary,Cosine Similarity
0,Jokowi Beberkan 'Love-Hate' dengan Surya Paloh...,Presiden Joko Widodo atau Jokowi membeberkan b...,0.879543
1,"Ucap Terima Kasih, Surya Paloh Akui Belajar da...",Ketua Umum Partai NasDem Surya Paloh mengaku b...,0.945338
2,"Di Depan Jokowi, Surya Paloh: Bukan Cuma Masal...",Ketua Umum Partai NasDem Surya Paloh menegaska...,title ...
3,"Jokowi Muncul di Kongres III NasDem Malam Ini,...",Presiden Joko Widodo alias Jokowi menghadiri K...,0.828687
4,"Sebut Pemilu 2024 Paling Brutal, Cak Imin Usul...",Ketua Umum Dewan Pimpinan Pusat Partai Kebangk...,0.300576

## Save Similarity

In [21]:
# Menyimpan DataFrame ke file CSV di lokasi yang ditentukan
similarity_df.to_csv('/content/drive/MyDrive/File/CODES/Similarity/5_Similarity_Suara_Nasional_Base1/similarity_suara_nas_base1.csv', index=False)