# Install Library

In [ ]:
!pip install transformers
!pip install datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.12)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 12.1 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.0 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 8.8 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 6.2 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 9.3 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.5.1+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.5.1+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.2.0 dill-0.3.8 fsspec-2024.9.0 multiprocess-0.70.16 xxhash-3.5.0

# Import Library

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer
from google.colab import drive

# Connect to Drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Path folder tempat file CSV berada
folder_path = "/content/drive/MyDrive/File/CODES/Summarize/1_Summary_Detik_Berita_50_Base1/Sum_Detik_Berita_50_Base1"

# Mengambil semua file dengan ekstensi .csv dalam folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith(".csv")]

# Membaca dan menggabungkan semua file
dataframes = []
for file_name in csv_files:
    file_path = os.path.join(folder_path, file_name)
    df = pd.read_csv(file_path)
    dataframes.append(df)

# Menggabungkan semua DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

# # Menyimpan hasil penggabungan ke file baru
# output_path = os.path.join(folder_path, "/content/drive/MyDrive/0.SKRIPSI/CODES/Similarity/1_Similarity_Detik_Berita_Base1/detikberita_sum_50_base1_concat.csv")
# combined_df.to_csv(output_path, index=False)

In [ ]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13249 entries, 0 to 13248
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         13249 non-null  object
 1   category      13249 non-null  object
 2   publish_date  13249 non-null  object
 3   author        13249 non-null  object
 4   article_url   13249 non-null  object
 5   content       13249 non-null  object
 6   summary       13249 non-null  object
dtypes: object(7)
memory usage: 724.7+ KB

In [ ]:
combined_df.head()

,title,category,publish_date,author,article_url,content,summary
0,Prabowo Sarankan Otorita Prioritaskan Bangun G...,detikNews,2024-08-12,Eva Safitri,https://news.detik.com/berita/d-7486738/prabow...,Menhan sekaligus Presiden terpilih Prabowo Sub...,Menhan sekaligus Presiden terpilih Prabowo Sub...
1,Warga Sebut Mobil Nyangkut di Separator Margon...,detikNews,2024-08-12,Devi Puspitasari,https://news.detik.com/berita/d-7486696/warga-...,Mobil mengalami kecelakaan hingga tersangkut d...,Mobil mengalami kecelakaan hingga tersangkut d...
2,Penyidikan Kasus Surya Darmadi Dihentikan KPK ...,detikNews,2024-08-12,Adrial akbar,https://news.detik.com/berita/d-7486641/penyid...,Komisi Pemberantasan Korupsi (KPK) telah mener...,Komisi Pemberantasan Korupsi (KPK) telah mener...
3,Horor Korban Jambret Terseret Motor Dikira Rib...,detikNews,2024-08-12,Muchamad Sholihin,https://news.detik.com/berita/d-7486614/horor-...,Peristiwa horor dialami seorang wanita bernama...,Peristiwa horor dialami seorang wanita bernama...
4,KPK Periksa Eks Anggota DPR Miryam S Haryani T...,detikNews,2024-08-12,Adrial akbar,https://news.detik.com/berita/d-7486362/kpk-pe...,KPK menjadwalkan pemeriksaan mantan anggota DP...,KPK menjadwalkan pemeriksaan mantan anggota DP...

In [ ]:
nan_summary = combined_df[combined_df['summary'].isna()]


nan_summary

Empty DataFrame
Columns: [title, category, publish_date, author, article_url, content, summary]
Index: []

In [ ]:
combined_df=combined_df.dropna()

# Duplicate

In [ ]:
data = combined_df.copy()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13249 entries, 0 to 13248
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         13249 non-null  object
 1   category      13249 non-null  object
 2   publish_date  13249 non-null  object
 3   author        13249 non-null  object
 4   article_url   13249 non-null  object
 5   content       13249 non-null  object
 6   summary       13249 non-null  object
dtypes: object(7)
memory usage: 724.7+ KB

# Tokenize

In [ ]:
# tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p2", use_fast=True)
# tokenizer.add_tokens([ 'NaN' ])

In [ ]:
# def tokenize_function(text):
#     return tokenizer(text, padding='max_length', max_length=256, truncation=True)

# # Tokenisasi kolom 'title' dan 'summary'
# data['tokenized_title'] = data['title'].apply(lambda x: tokenize_function(x))
# data['tokenized_summary'] = data['summary'].apply(lambda x: tokenize_function(x))

In [ ]:
# data.head()

In [ ]:
# # Menampilkan hasil tokenisasi untuk 'tokenized_title' dan 'tokenized_content'
# print("Tokenized Title:")
# print(data[['title', 'tokenized_title']])

# print("\nTokenized summary:")
# print(data[['summary', 'tokenized_summary']])

# # Menampilkan hanya input_ids yang lebih mudah dibaca
# print("\nInput IDs for Tokenized Title:")
# print(data['tokenized_title'].apply(lambda x: x['input_ids']))

# print("\nInput IDs for Tokenized summary:")
# print(data['tokenized_summary'].apply(lambda x: x['input_ids']))

Mencoba kode lain agar tokenize lebih mudah di pahami

# Word Embedding

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch

# Memuat IndoBERT dan tokenizer
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1", use_fast=True)
model = AutoModel.from_pretrained("indobenchmark/indobert-base-p1")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

In [ ]:
# Fungsi untuk mendapatkan embedding dari IndoBERT
def get_embeddings(input_ids):
    with torch.no_grad():
        outputs = model(input_ids=input_ids)
    # Mengambil hidden states dari layer terakhir dan rata-rata embeddingsnya
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings

# Fungsi untuk mengonversi tokenized data ke dalam bentuk input_ids dan mendapatkan embedding
def get_input_ids_and_embeddings(data_column):
    input_ids_list = []
    embeddings_list = []

    for text in data_column:
        # Tokenisasi
        tokens = tokenizer(text, padding='max_length', max_length=256, truncation=True, return_tensors="pt")
        input_ids = tokens['input_ids']  # Ambil input_ids
        input_ids_list.append(input_ids)

        # Mendapatkan embeddings
        embedding = get_embeddings(input_ids)
        embeddings_list.append(embedding)

    return input_ids_list, embeddings_list

# Dapatkan input_ids dan embeddings untuk title dan summary
title_input_ids, title_embeddings = get_input_ids_and_embeddings(data['title'])
summary_input_ids, summary_embeddings = get_input_ids_and_embeddings(data['summary'])

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

## Mengubah embeddings menjadi array numpy

In [ ]:
# Mengubah embeddings menjadi array numpy agar bisa disimpan dalam DataFrame
title_embeddings_array = np.vstack([embedding.numpy() for embedding in title_embeddings])
summary_embeddings_array = np.vstack([embedding.numpy() for embedding in summary_embeddings])

# Membuat DataFrame baru dengan embeddings numerik
data_embeddings = pd.DataFrame({
    'title_embeddings': list(title_embeddings_array),
    'summary_embeddings': list(summary_embeddings_array)
})

# Menyimpan DataFrame embeddings ke dalam file CSV (atau format lain)
# data_embeddings.to_csv('/content/drive/MyDrive/File/CODES/Similarity/Detik Berita/detik_berita_embeddings.csv', index=False)

# Cosine Similarity

In [ ]:
# hitung cosine similarity pada matrix berita
cosine_sim = cosine_similarity(title_embeddings_array, summary_embeddings_array)
print(cosine_sim)

[[0.39743182 0.08263262 0.16272368 ... 0.88219666 0.4129303  0.8092322 ]
 [0.40136445 0.08776305 0.16605133 ... 0.8857981  0.41709837 0.8138304 ]
 [0.39535975 0.08522928 0.16942966 ... 0.8800826  0.41067275 0.80712414]
 ...
 [0.40607548 0.08772117 0.1685186  ... 0.8937255  0.42193395 0.82156384]
 [0.3931021  0.08393773 0.16293524 ... 0.87755513 0.41084927 0.80450904]
 [0.39085555 0.08555878 0.16440985 ... 0.8766229  0.40758425 0.8029333 ]]

In [ ]:
# membuat dataframe dari varible cosine similarity dengan baris dan kolom title
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['summary'], columns=data['title'])

print(cosine_sim_df.shape)

(13249, 13249)

## Check Similarity Result

In [ ]:
# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # The index is a summary, and you need to find the corresponding title
    # to access the similarity value. However, since you have both summaries
    # and titles as indices, you can access the similarity directly using
    # the index and the corresponding title from the 'data' DataFrame.

    title = data.loc[data['summary'] == index, 'title'].iloc[0] # Get the title for the current summary
    similarity_value = cosine_sim_df.loc[index, title]  # Access the similarity using both summary and title

    print(f"Title: {title}")
    print(f"Summary: {index}")
    print(f"Cosine Similarity: {similarity_value}\n")
    print("-" * 50)  # Pemisah antar pasangan

Streaming output truncated to the last 5000 lines.
Summary: Lomba 17 Agustus merupakan kegiatan wajib untuk memeriahkan peringatan HUT RI atau Hari Kemerdekaan RI. Berikut ini rekomendasi lomba 17 Agustus untuk anak-anak hingga orang dewasa. Sejumlah perlombaan bisa dijadikan pilihan saat momentum peringatan 17 Agustus. Perlombaan ini bisa dilakukan secara tim atau individu. Peserta memindahkan bendera dari satu tempat ke tempat lainnya. Dalam lomba ini, sebuah tim yang terdiri dari dua hingga empat orang harus berjoget sambil meletakkan balon di kepala atau perut mereka. Balon dijaga tanpa disentuh dan pastikan tidak jatuh. Perlombaan ini membutuhkan kelompok yang terdiri dari 4 sampai 6 orang. Apabila karet jatuh, harus diulang dari peserta pertama. Kelompok yang berhasil memindahkan karet dengan jumlah terbanyak, jadi pemenang. Perlombaan kelereng membutuhkan alat berupa sendok dan satu buah kelereng. Bakiak adalah permainan tradisional yang menggunakan sandal kayu panjang. Permainan ini membutuhkan kerjasama tim dan konsentrasi ketika menggerakkan bakiak. Lomba balap karung bisa melatih ketangkasan dan kecepatan anak. Pesertanya perlu mengumpulkan koin yang ditimbun dengan tepung di sebuah wadah. Saat lomba dimulai, peserta berlari ke garis finish, lalu masukkan pensil yang menggantung tersebut ke botol kosong. Pemenangnya adalah peserta yang berhasil memasukkan pensil terlebih dahulu. Pemenang berdasarkan kriteria yang ditentukan dewan juri. Peserta merupakan tim yang terdiri dari tiga sampai lima orang. Tim dengan poin terbanyak, menjadi pemenang. Peserta memanjat pohon pinang yang sudah dikuliti dan diberi pelicin, seperti oli bekas. Di atas pohon terdapat hadiah menarik yang bisa dibawa pulang oleh peserta jika berhasil sampai ke atas. Peserta pertama akan menghafal kata-kata tertentu yang nantinya diteruskan kepada teman-teman kelompoknya. Kelompok paling banyak menjawab dialah pemenangnya. Tantangannya adalah belut yang licin saat ditangkap sehingga memicu kelucuan dan keseruan. Peserta lomba terdiri dari pihak yang dirias (suami) dan perias (istri). Peserta akan merias wajah dengan mata tertutup. Penilaian dilakukan berdasarkan keindahan dan kerapian dari hasil tata rias yang dilakukan. Setiap peserta harus berjalan jongkok menggunakan karung yang diikat ke seluruh badan dan memakai helm. Peserta yang pertama mencapai garis finish, jadi pemenang. Perlombaan ini dapat diikuti oleh ibu-ibu. Para peserta harus mengumpulkan poin dengan cara memasukkan bola ke gawang menggunakan sapu. Permainan memasukkan benang ke jarum khusus untuk ibu-ibu atau bapak-bapak. Semakin banyak benang yang dimasukkan, maka itu pemenangnya. Setiap peserta akan diberi cokelat untuk dimakan dengan cara harus digerakkan dari kening hingga mulut. Jika cokelat jatuh, maka permainan diulang dengan cokelat baru. Lomba tebak harga dimainkan peserta bapak-bapak dengan cara menebak harga bahan pokok seperti beras, telur dan lainnya. Peserta akan memindahkan kacang hijau satu per satu dari wadah ke wadah lainnya dengan durasi yang ditentukan. Peserta paling banyak mengumpulkan kacang hijau adalah pemenangnya. Peserta harus mencari pasangan sepatu yang sesuai dan memakainya. Setiap peserta akan diberikan paku yang harus mereka masukkan ke dalam botol kosong.
Cosine Similarity: 0.22789216041564941

--------------------------------------------------
Title: Polisi Sita 3 Senjata Api-148 Peluru dari Pelaku Penembakan Pria di Bogor
Summary: Polisi menyita sejumlah barang bukti kasus penembakan salah sasaran terhadap pria inisial MAF (22) di Klapanunggal, Kabupaten Bogor, Jawa Barat. Di antaranya tiga senjata api (senpi) dan satu airsoft gun. " Kami melakukan penggeledahan terhadap AZ bahwa kami menyita 1 pucuk senpi laras panjang rakitan, 2 pucuk senpi laras pendek jenis pistol makarov dan revolver, salah satu senjata tersebut sebagai alat bukti penembakan, 1 pucuk airsoft gun laras panjang jenis makarov. Jadi airsoft gun ini diubah larasnya, diubah mesinnya menjadi senpi rakitan," kata Kapolres Bogor AKBP Rio Wahyu Anggoro, kepada wartawan di Cibinong, Selasa 6 Agustus 2024. Selain itu, polisi menyita lima buah magasin laras panjang. Ada juga alat-alat yang digunakan untuk merakit senpi. " Selanjutnya tersangka kedua adalah AZ (30). Dan SI (18) berperan sebagai eksekutor yang bertindak melakukan penembakan," terangnya.
Cosine Similarity: 0.5071318745613098

--------------------------------------------------
Title: Lalin Mampang Arah Kuningan Jaksel Macet, Mobil-Motor Terobos Jalur TransJ
Summary: Kemacetan terjadi di Jalan Mampang Prapatan Raya, Jakarta Selatan. Pantauan detikcom, Senin 5 Agustus 2024 sampai pukul 09.20 WIB kemacetan masih berlangsung di kawasan itu. Terlihat ada pengendara motor maupun mobil yang nekat menerobos jalur TransJakarta di Jalan Mampang Prapatan. Suara klakson kendaraan kerap terdengar bersahutan. Penyempitan jalan di kawasan itu membuat jalan tidak maksimal untuk kendaraan.
Cosine Similarity: 0.9735069274902344

--------------------------------------------------
Title: Lalin di Pancoran Jaksel Arah Semanggi Macet, Pengendara Adu Klakson
Summary: Kemacetan lalu lintas terjadi di Jalan Gatot Subroto, Jakarta Selatan, arah Semanggi. Para pengendara terdengar saling adu klakson di tengah macet. Sejumlah pengemudi ojek online terlihat berhenti di pinggir jalan untuk naik dan turun penumpang. Selain itu, terlihat antrean bus TransJakarta yang hendak menuju Halte Pancoran. Laju bus TransJakarta kembali lancar setelah masuk ke lajur khususnya. Kemacetan di kawasan ini dipicu pertemuan kendaraan dari Tol Dalam Kota dengan kendaraan dari jalur arteri Jalan Gatot Subroto. Simak juga Video 'Usul Jusuf Hamka: Sudirman-Bundaran HI Dibangun Flyover untuk Urai Macet':
Cosine Similarity: 0.9262107014656067

--------------------------------------------------
Title: 4 Fakta Bocah Ugal-ugalan Nyetir Rush di Kemang Hingga Tabrak Sana-sini
Summary: Seorang bocah berinisial MP (9) hampir dihajar warga di Kemang, Jakarta Selatan. Pengunggah menyebutkan mobil yang dibawa kabur bocah tersebut menabrak beberapa kendaraan. Warga sekitar juga disebut sempat akan memukuli sopir mobil tersebut. Mendapatkan laporan dari warga adanya seorang anak kecil yang membawa mobil menabrak tiang lampu merah TL restoran cepat saji Kemang," kata Ade Ary kepada wartawan. Apa saja fakta yang sudah diketahui terkait insiden ini? Bocah itu lalu membawa kabur mobil tersebut. " Anak kecil tersebut mengambil kunci mobil dari rumah pemilik mobil yang sebelumnya memarkirkan mobilnya di pinggir jalan setelah mengantar pemilik pulang. Selanjutnya mobil dibawa dari Perumahan Destap, Jalan Bangka VIII A, Kelurahan Pela Mampang, mengarah ke TL restoran cepat saji Kemang," jelasnya.
Cosine Similarity: 0.8028366565704346

--------------------------------------------------
Title: Info Titik Kepadatan Lalin di Tol Arah Jakarta Pagi Ini
Summary: Jasa Marga melaporkan titik-titik kepadatan lalu lintas di jalan tol pagi ini. Kepadatan lalu lintas terjadi di tol yang mengarah ke Jakarta. Mayoritas kepadatan ini terjadi karena volume lalin. Tol Dalam Kota    Titik pertama kepadatan di Tol Dalam Kota itu terjadi di simpang susun Cawang. Kemudian di titik Tebet arah Pancoran dan juga yang mengarah ke Senayan. "# Kuningan KM 06 - Semanggi KM 07 PADAT, kepadatan volume lalin," katanya. " Tol Janger Untuk di Tol Jakarta-Tangerang (Janger), kepadatan terjadi di arah Tomang. Tol Janger Tangerang KM 16 - Kunciran KM 14 arah Tomang PADAT, kepadatan volume lalin. Kunciran - Karang Tengah PADAT, kepadatan volume lalin. Selain itu, di Kebon Jeruk Km 03 juga ada penanganan truk gangguan. Tol_Janger HATI-HATI di Kebon Jeruk KM 03 arah Tomang, ada kendaraan Dump Truk gangguan ban di bahu luar/kiri," katanya. Selanjutnya, lalin yang mengarah Cawang juga padat. Di Tol Japek juga dilaporkan ada kecelakaan tunggal truk. Saat ini sudah dalam penanganan petugas. " Lalin arah Kalicipinang juga dilaporkan padat. " Lalin lancar mulai dari Cawang hingga Ciawi.
Cosine Similarity: title
Info Titik Kepadatan Lalin di Tol Arah Jakarta Pagi Ini    0.721634
Info Titik Kepadatan Lalin di Tol Arah Jakarta Pagi Ini    0.171734
Name: Jasa Marga melaporkan titik-titik kepadatan lalu lintas di jalan tol pagi ini. Kepadatan lalu lintas terjadi di tol yang mengarah ke Jakarta. Mayoritas kepadatan ini terjadi karena volume lalin. Tol Dalam Kota    Titik pertama kepadatan di Tol Dalam Kota itu terjadi di simpang susun Cawang. Kemudian di titik Tebet arah Pancoran dan juga yang mengarah ke Senayan. "# Kuningan KM 06 - Semanggi KM 07 PADAT, kepadatan volume lalin," katanya. " Tol Janger Untuk di Tol Jakarta-Tangerang (Janger), kepadatan terjadi di arah Tomang. Tol Janger Tangerang KM 16 - Kunciran KM 14 arah Tomang PADAT, kepadatan volume lalin. Kunciran - Karang Tengah PADAT, kepadatan volume lalin. Selain itu, di Kebon Jeruk Km 03 juga ada penanganan truk gangguan. Tol_Janger HATI-HATI di Kebon Jeruk KM 03 arah Tomang, ada kendaraan Dump Truk gangguan ban di bahu luar/kiri," katanya. Selanjutnya, lalin yang mengarah Cawang juga padat. Di Tol Japek juga dilaporkan ada kecelakaan tunggal truk. Saat ini sudah dalam penanganan petugas. " Lalin arah Kalicipinang juga dilaporkan padat. " Lalin lancar mulai dari Cawang hingga Ciawi., dtype: float32

--------------------------------------------------
Title: Cerita Pemilik Sumur Bor Semburkan Air 20 Meter di Madura Sembelih 3 Kambing
Summary: Pemilik sumur bor di Desa Pandan, Kecamatan Omben, Sampang menyembelih 3 ekor kambing untuk selametan saat semburan air 20 meter keluar. Dilansir detikJatim, Senin 5 Agustus 2024 pemilik sumur bor, Rokib (35) mengaku ruwatan itu biasanya dilakukan sebelum melakuan pengeboran dan selesai pengeboran. Rokib mengungkapkan ruwatan yang digelar sebagai sedekah dan bentuk syukur atas ditemukan air di daerah yang tandus tersebut. Semoga setelah ini airnya bisa dimanfaatkan oleh keluarga dan warga di sini," imbuhnya. Pengeboran itu dilakukan selama 38 hari hingga Kamis 1 Agustus 2024 malam dihentikan. Tukang yang mengerjakan pengeboran itu merasa sudah mencapai titik sumber air. Sebelum air menyembur Rokib dan keluarga sempat panik karena mendengar desing angin seperti deru mesin pesawat disertai 2 kali letusan. Simak Video 'Penampakan Semburan Air Sumur Bor Bercampur Gas Setinggi 20 Meter':
Cosine Similarity: 0.579232931137085

--------------------------------------------------
Title: Pemotor Tewas Diseruduk Truk 100 Meter di Gianyar Bali, Sopir Ditangkap
Summary: Seorang pengendara motor di Gianyar,Bali bernama Agus diseruduk truk. Truk yang dikemudikan Muzahar (42) asal Lombok, tiba-tiba menabrak sepeda motor yang dikendarai Agus dan terseret jauh dan meninggal di tempat," katanya Suarta saat dikonfirmasi Minggu 4 Agustus 2024 malam. Sementara korban terpental dan motornya hancur. " Motornya juga hancur terpental keluar jalur jalan," terangnya. Polisi langsung mengamankan sopir tersebut. " Kami menduga pengemudi truk lalai dan tidak memperhatikan kondisi lalu lintas di sekitarnya, sopir sudah diamankan di Polres Gianyar," ujar Suarta.
Cosine Similarity: 0.9243098497390747

--------------------------------------------------
Title: Semburan Air Sumur Bor di Madura Surut, Polisi-TNI Tetap Siaga di Lokasi
Summary: Semburan air di Desa Pandan, Kecamatan Omben, Sampang, telah surut. Sejak surut tadi malam sampai hari ini pukul 13.00 WIB, di sini (Sumur bor) yang sempat viral, tidak lagi mengeluarkan semburan air ataupun bau gas dan lainnya," kata Budi kepada detikJatim, Minggu 4 Agustus 2024. Polisi bersama TNI serta warga melakukan sterilisasi lokasi guna menghindari hal yang tidak diinginkan terjadi. Jalan menuju rumah dipasang portal dari bambu dan di sekitar lokasi sumur bor dipasang pagar pembatas menggunakan bambu. " Ini dilakukan untuk sementara waktu untuk memberikan rasa aman dan antisipasi hal-hal lain," imbuhnya.
Cosine Similarity: 0.9010181427001953

--------------------------------------------------
Title: Mahasiswi Tabrak IRT hingga Tewas di Pekan Baru Habis Pulang Dugem
Summary: Mahasiswi Marisa Putri (21) ditetapkan sebagai tersangka usai menabrak ibu rumah tangga (IRT), Renti (46) di Pekan Baru. Tersangka diketahui baru pulang dugem saat kjadian. Setelah gelar perkara, pelaku inisial MP kita tetapkan jadi tersangka," terang Kapolresta Pekanbaru Kombes Jeki Rahmat Mustika di Mapolresta, Minggu 4 Agustus 2024. Tiba di sana korban dikasih narkotika jenis pil ekstasi dan minuman keras sampai Subuh. Sekitar pukul 05.00 WIB korban pulang dan mengemudikan mobil dalam pengaruh alkohol dan narkoba," kata Jeki. Saat mengendarai mobil di Jalan Tuanku Tambusai Pekanbaru, dari arah yang bersamaan, mahasiswa Universitas Abdurab Pekanbaru itu menabrak sepeda motor Yamaha Vega ZR. Akibatnya korban meninggal dunia di lokasi kejadian karena luka berat di kepala," kata Jeki.
Cosine Similarity: 0.6517705917358398

--------------------------------------------------
Title: Mahasiswi di Tulungagung Nekat Melahirkan Sendiri di Kos, Bayi Tewas
Summary: Seorang mahasiswi di Tulungagung inisial AR (23) melahirkan sendiri di kamar mandi kosnya. Atas aksi nekatnya itu, sang bayi tewas dan mahasiswi itu pingsan. Hal itu guna mengetahui penyebab kematian bayi. " Apakah ada unsur pidana atau tidak," ujar Nur Said, dilansir detikJatim, Selasa 6 Agustus 2024. Saat itu ibu bayi itu pingsan (saat melahirkan). Sekitar pukul 13.00 WIB kakak AR tiba di kos dan langsung memberikan pertolongan dengan membawa AR dan bayinya ke Puskemas Beji guna mendapatkan perawatan medis.
Cosine Similarity: 0.9376633167266846

--------------------------------------------------
Title: Andre Rosiade-Mahyeldi Bertemu PUPR, Lelang Jalan Air Dingin Dipastikan Oktober 2024
Summary: Anggota DPR RI asal Sumatra Barat (Sumbar) Andre Rosiade bersama Gubernur Sumbar Mahyeldi Ansharullah bertemu dengan Direktur Jenderal (Dirjen) Bina Marga Kementerian Pekerjaan Umum dan Perumahan Rakyat (PUPR) Rachman Arief Dienaputra. Dalam pertemuan itu dipastikan soal perbaikan Jalan Air Dingin di Sumbar akan dilelang pada Oktober 2024. Andre Rosiade menyebutkan pertemuan itu membahas soal tender Fly Over Sitinjau Lauik, dan lelang perbaikan Jalan Air Dingin. Pengerjaan sudah bisa dilakukan pada tahun 2025. " Selain fly over dan perbaikan jalan Air Dingin, kami juga meminta kepada Pak Dirjen Bina Marga PUPR untuk memastikan Inpres Jalan Daerah bisa diberikan untuk membantu Pemprov Sumbar memperbaiki jalan-jalan yang rusak," kata Andre pada pertemuan, di Kantor Kementerian PUPR, seperti dalam keterangannya, Selasa 6 Agustus 2024. Andre menyampaikan, jalan dari Payakumbuh menuju Batusangkar, dan dari Batusangkar ke Sijunjung rusak parah. Perbaikan harus dilakukan oleh pemerintah pusat karena jalan tersebut adalah jalan negara, dan membutuhkan anggaran besar. " Terima kasih kepada pak Andre Rosiade yang telah membantu memfasilitasi pertemuan ini, dan juga begitu getol memperjuangkan pembangunan Sumbar," kata Mahyeldi. Mahyeldi meminta Kementerian PUPR segera memperbaiki kerusakan jalan di Sumbar. " Anggaran tersebut akan digelontorkan secara bertahap. " Direktur Preservasi Jalan dan Jembatan Wilayah I Nyoman Suaryana menambahkan, untuk Jalan Air Dingin sudah ada paket pemeliharaan rutinnya. " Rencana yang sudah pasti di jembatan pas lokasi quary (tambang) dengan nilai Rp119 miliar. Akan diusulkan bertahap pada dua sampai tiga tahun," katanya.
Cosine Similarity: 0.21427029371261597

--------------------------------------------------
Title: Indeks Ketimpangan Gender RI Dinilai Stagnan, Bamsoet: Masih Banyak PR
Summary: Ketua MPR RI Bambang Soesatyo menuturkan di tengah laju modernitas dan kemajuan zaman, ternyata isu ketimpangan gender masih menjadi persoalan klasik yang mengemuka. Isu ketimpangan gender bahkan hampir selalu menjadi bagian dari dinamika kehidupan berbangsa dan mewarnai setiap periodisasi pemerintahan. Tahun 2011 Indonesia mendapatkan IKG sebesar 0,481, dan pada tahun 2023 sebesar 0,447. Artinya, tidak banyak perubahan yang berarti, selama kurun waktu dua belas tahun tersebut. Meskipun ada penurunan, namun angkanya tidak terlalu signifikan. " Peringkat ini menunjukkan bahwa kita masih memiliki banyak pekerjaan rumah yang harus diselesaikan untuk mengurangi kesenjangan gender. Misalnya, masih kuatnya budaya patriarki dan seksisme, serta masih berkembangnya pola pikir yang cenderung menempatkan posisi kaum perempuan berada di bawah laki-laki. Faktor lain misalnya adanya kesenjangan dalam memperoleh akses pendidikan dan pekerjaan. Kesenjangan gender juga tercermin dari akses perlindungan hukum. Secara global, menurut catatan Bank Dunia tahun 2024, akses perlindungan hukum yang diperoleh perempuan hanya sebesar dua per tiga atau sekitar 67 persen dari yang diterima laki-laki. " Ketua Dewan Pembina Depinas SOKSI (Ormas Pendiri Partai Golkar) dan Kepala Badan Polhukam KADIN Indonesia ini menerangkan, untuk mencapai keadilan dan kesetaraan gender perlu dilakukan perubahan pada berbagai fase. Pertama, diperlukan kebijakan yang lebih inklusif untuk memastikan bahwa hak-hak perempuan dihormati dan dilindungi. Kedua, penting disadari bahwa kebijakan dan undang-undang saja tidak akan cukup. Ketiga, sektor swasta juga memiliki peran penting dalam mendukung kesetaraan gender. Program-program seperti kebijakan cuti melahirkan yang lebih baik, fleksibilitas kerja, dan dukungan bagi perempuan dalam posisi kepemimpinan adalah contoh upaya positif yang dapat diadopsi lebih luas," pungkas Bamsoet.
Cosine Similarity: 0.13842272758483887

--------------------------------------------------
Title: Ketua RT Ungkap Awal Mula Akses Rumah Warga di Cililitan Jaktim Ditembok
Summary: Akses jalan rumah milik Puji (49) di Gang Jati, RT 09 RW 09, Cililitan, Jakarta Timur (Jaktim), tertutup tembok bangunan. Ketua RT setempat, Harsono, menjelaskan awal mula akses jalan ke luar rumah milik Puji ditutup oleh pihak Sidik selaku pemilik tanah. Yang satu lagi (Puji), saya dikasih (almarhum Haji Ali) suruh jalan ke sini, dari omongan Pak Haji Ali," kata Harsono, Ketua RT 09, saat ditemui di rumahnya, Selasa 6 Agustus 2024. Dia juga menjelaskan mulanya pihak Sidik tidak menutup akses jalan rumah Puji secara menyeluruh. Yang punya tanah ini, Sidik ini, bilang, 'Pak RT, Bu Puji lapor ke sana. Nah, sampai sekarang udah mau ya itu mau di-share suratnya tadi. Tetap dia nggak mau akhirnya udah bikin rame Bu Puji. Puji (49), warga yang akses rumahnya ditutup tembok di Cililitan, Jakarta Timur (Jaktim), mengungkap kronologi awal penutupan. Saya tanya, 'Sidik, ada masalah apa dengan keluarga saya? Kamu nggak mikirin kita orang di dalem?', ' Ya terserah, kan tanah tanahnya, terserah saya mau ditutup' kata dia gitu, udah," ucap Puji. Kemudian barulah pihak Puji dan Sidik dimediasi. " Dari situ saya nggak bisa bilang apa-apa ya. Dibuatlah mediasi-mediasi tapi ya nihil," ujar Puji. Dia menjelaskan, pada Februari, penutupan akses jalan dilakukan hanya sebagian dengan kisaran 60 cm. Dia pun tahu aksesnya ditutup setelah diberi tahu anaknya yang melihat seorang tukang bangunan sedang mendirikan tembok. " Dia pun menjelaskan akses yang ditutup ini menjadi satu-satunya untuk bisa ke jalan utama. Iya (akses satu-satunya), tadi masuk lihat sendiri, kan? Apa iya mungkin saya tiap hari dan bertahun-tahun akan lewat kamar orang?" detikcom berupaya meminta keterangan kepada pihak yang mendirikan tembok.
Cosine Similarity: 0.22320424020290375

--------------------------------------------------
Title: Andre Rosiade-Gubernur Sumbar Temui Dirjen Binamarga, Pemenang Tender Flyover Sitinjau Lauik Diumumkan 13 September

In [ ]:
# List to store the results
results = []

# Menampilkan pasangan similarity antara 'title' dan 'summary' yang sesuai dengan urutan
for index, row in cosine_sim_df.iterrows():
    # Mendapatkan judul yang sesuai dengan summary berdasarkan index
    title = data.loc[data['summary'] == index, 'title'].iloc[0]
    similarity_value = cosine_sim_df.loc[index, title]  # Mengakses nilai similarity

    # Menyimpan pasangan dan nilai similarity ke dalam list
    results.append([title, index, similarity_value])

# Membuat DataFrame untuk hasilnya
similarity_df = pd.DataFrame(results, columns=['Title', 'Summary', 'Cosine Similarity'])

In [ ]:
similarity_df.head()

,Title,Summary,Cosine Similarity
0,Prabowo Sarankan Otorita Prioritaskan Bangun G...,Menhan sekaligus Presiden terpilih Prabowo Sub...,0.397432
1,Warga Sebut Mobil Nyangkut di Separator Margon...,Mobil mengalami kecelakaan hingga tersangkut d...,0.087763
2,Penyidikan Kasus Surya Darmadi Dihentikan KPK ...,Komisi Pemberantasan Korupsi (KPK) telah mener...,0.16943
3,Horor Korban Jambret Terseret Motor Dikira Rib...,Peristiwa horor dialami seorang wanita bernama...,0.122731
4,KPK Periksa Eks Anggota DPR Miryam S Haryani T...,KPK menjadwalkan pemeriksaan mantan anggota DP...,0.160098

## Save Similarity

In [ ]:
# Menyimpan DataFrame ke file CSV di lokasi yang ditentukan
similarity_df.to_csv('/content/drive/MyDrive/File/CODES/Similarity/1_Similarity_Detik_Berita_Base1/similarity_detik_berita_base1.csv', index=False)